import "./web/turbo.es2017-esm.js";
import { Application } from "./web/stimulus.js";
import DialogController from "./ui/dialog.js";
import PlayerController from "./view/player.js";
import ListController from "./ui/list.js";
import SidebarController from "./view/sidebar/sidebar.js";
import AddTorrentController from "./view/add-torrent.js";
import NotePortController from "./ui/note-port.js";
import SelectController from "./ui/select.js";
import SettingsTextFieldController from "./ui/settings-text-field.js";
import SettingsToggleController from "./ui/settings-toggle.js";
import TopbarController from "./view/topbar.js";

window.Stimulus = Application.start();
Stimulus.register("dialog", DialogController);
Stimulus.register("player", PlayerController);
Stimulus.register("list", ListController);
Stimulus.register("sidebar", SidebarController);
Stimulus.register("add-torrent", AddTorrentController);
Stimulus.register("note-port", NotePortController);
Stimulus.register("select", SelectController);
Stimulus.register("settings-text-field", SettingsTextFieldController);
Stimulus.register("settings-toggle", SettingsToggleController);
Stimulus.register("topbar", TopbarController);
