import "./web/turbo.es2017-esm.js";
import { Application } from "./web/stimulus.js";
import DialogController from "./view/dialog-controller.js";
import PlayerController from "./view/player-controller.js";
import ListController from "./ui/list.js";
import SidebarController from "./view/sidebar/sidebar-controller.js";
import AddTorrentController from "./view/add-torrent-controller.js";
import NotePortController from "./ui/note-port.js";
import SelectController from "./ui/select.js";
import ToggleController from "./ui/toggle.js";
import TopbarController from "./view/topbar-controller.js";

window.Stimulus = Application.start();
Stimulus.register("dialog", DialogController);
Stimulus.register("player", PlayerController);
Stimulus.register("list", ListController);
Stimulus.register("sidebar", SidebarController);
Stimulus.register("add-torrent", AddTorrentController);
Stimulus.register("note-port", NotePortController);
Stimulus.register("select", SelectController);
Stimulus.register("toggle", ToggleController);
Stimulus.register("topbar", TopbarController);
