import "./web/turbo.es2017-esm.js";
import "./ui/turbo/action.js";
import { Application } from "./web/stimulus.js";
import ActionButtonController from "./ui/action-button.js";
import DialogController from "./ui/dialog.js";
import DialogTriggerController from "./ui/dialog-trigger.js";
import PopoverController from "./ui/popover.js";
import PopoverTriggerController from "./ui/popover-trigger.js";
import PickerController from "./ui/picker.js";
import PlayableController from "./view/playable.js";
import PlayerController from "./view/player.js";
import ListController from "./ui/list.js";
import SidebarController from "./view/sidebar/sidebar.js";
import UploadController from "./view/upload.js";
import UploadProgressController from "./view/upload-progress.js";
import NotePortController from "./ui/note-port.js";
import SelectController from "./ui/select.js";
import SettingsButtonRowController from "./ui/settings-button-row.js";
import SettingsTextAreaController from "./ui/settings-text-area.js";
import SettingsTextFieldController from "./ui/settings-text-field.js";
import SettingsToggleController from "./ui/settings-toggle.js";
import SeasonTitleController from "./view/season-title.js";
import CollectionController from "./view/theater-collections.js";
import Series from "./view/theater-series.js";
import EpisodeAttachController from "./view/episode-attach.js";
import HomeController from "./view/home.js";
import SortableController from "./ui/sortable.js";
import "./view/wash.js";

window.Stimulus = Application.start();
Stimulus.register("action-button", ActionButtonController);
Stimulus.register("dialog", DialogController);
Stimulus.register("dialog-trigger", DialogTriggerController);
Stimulus.register("popover", PopoverController);
Stimulus.register("popover-trigger", PopoverTriggerController);
Stimulus.register("picker", PickerController);
Stimulus.register("playable", PlayableController);
Stimulus.register("player", PlayerController);
Stimulus.register("list", ListController);
Stimulus.register("sidebar", SidebarController);
Stimulus.register("upload", UploadController);
Stimulus.register("upload-progress", UploadProgressController);
Stimulus.register("note-port", NotePortController);
Stimulus.register("season-title", SeasonTitleController);
Stimulus.register("select", SelectController);
Stimulus.register("sortable", SortableController);
Stimulus.register("settings-button-row", SettingsButtonRowController);
Stimulus.register("settings-text-area", SettingsTextAreaController);
Stimulus.register("settings-text-field", SettingsTextFieldController);
Stimulus.register("settings-toggle", SettingsToggleController);
Stimulus.register("collection", CollectionController);
Stimulus.register("episode-attach", EpisodeAttachController);
Stimulus.register("series", Series);
Stimulus.register("home", HomeController);
