// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package schema

type AudioRendition struct {
	ID           string
	VideoID      string
	AudioTrackID string
	Channels     int64
	Bitrate      int64
	Codec        string
	Key          string
	Playlist     string
	Priority     int64
	SortKey      int64
}

type AudioTrack struct {
	ID            string
	VideoID       string
	StreamIndex   int64
	Language      string
	Title         string
	Channels      int64
	ChannelLayout string
	SampleRate    int64
	Codec         string
	Profile       string
}

type Collection struct {
	ID        string
	Slug      string
	Title     string
	BannerID  string
	DeletedAt *int64
}

type CollectionMovie struct {
	CollectionID string
	MovieID      string
	DeletedAt    *int64
}

type CollectionSeries struct {
	CollectionID string
	SeriesID     string
	DeletedAt    *int64
}

type Download struct {
	InfoHash        string
	Createdat       int64
	LastActivityAt  int64
	State           string
	Title           string
	Error           string
	Torrent         []byte
	Progress        float64
	Autoimport      int64
	MovieEditionID  *string
	SeriesEditionID *string
	DeletedAt       *int64
}

type Episode struct {
	ID          string
	Title       string
	Summary     string
	Type        string
	Airdate     string
	Runtime     int64
	ThumbnailID string
	DeletedAt   *int64
}

type EpisodeVideo struct {
	EpisodeID string
	VideoID   string
	Active    int64
	DeletedAt *int64
}

type Image struct {
	ID          string
	OriginalKey string
	Type        string
}

type ImageRendition struct {
	Key     string
	ImageID string
	Type    string
	Width   int64
	Height  int64
}

type Movie struct {
	ID        string
	Slug      string
	TMDBID    *int64
	IMDBID    *string
	DeletedAt *int64
}

type MovieEdition struct {
	ID          string
	MovieID     string
	Slug        string
	Title       string
	Label       string
	Summary     string
	ReleaseDate string
	Runtime     int64
	PosterID    string
	DeletedAt   *int64
}

type MovieVideo struct {
	MovieEditionID string
	VideoID        string
	Active         int64
	DeletedAt      *int64
}

type Rendition struct {
	ID            string
	VideoID       string
	Purpose       string
	Remux         int64
	Codec         string
	TargetBitrate int64
	MaxHeight     int64
	MaxFPS        int64
	Key           string
	Playlist      string
	Priority      int64
}

type Schema struct {
	Single  int64
	Version string
	Digest  string
}

type Season struct {
	ID        string
	EditionID string
	SortKey   string
	Title     string
	Number    int64
	DeletedAt *int64
}

type SeasonEpisode struct {
	EditionID string
	SeasonID  string
	EpisodeID string
	SortKey   int64
	Label     string
	Number    int64
	Slug      string
	DeletedAt *int64
}

type Series struct {
	ID          string
	Slug        string
	Title       string
	Status      string
	PremieredOn string
	EndedOn     string
	TVmazeID    *int64
	IMDBID      *string
	TVDBID      *int64
	TVRageID    *int64
	DeletedAt   *int64
}

type SeriesEdition struct {
	ID        string
	SeriesID  string
	Slug      string
	Label     string
	Summary   string
	PosterID  string
	DeletedAt *int64
}

type Setting struct {
	Key   string
	Group string
	Value string
}

type Slug struct {
	Slug   string
	Kind   string
	Target string
}

type SubtitleTrack struct {
	ID            string
	VideoID       string
	StreamIndex   int64
	Language      string
	Title         string
	OriginalCodec string
	OriginalKey   string
	WebVTTKey     string
	Forced        int64
}

type Task struct {
	ID          string
	Type        string
	Args        string
	Failures    int64
	NextRun     int64
	FailureDesc *string
	Priority    int64
	Queue       string
	State       string
}

type Trash struct {
	ID        string
	Title     string
	Subtitle  string
	DeletedAt int64
	CascadeOf *string
}

type User struct {
	ID   string
	Name string
}

type Video struct {
	ID                 string
	InfoHash           *string
	Name               string
	State              string
	OriginalKey        string
	OriginalType       string
	Format             string
	Duration           int64
	Width              int64
	Height             int64
	FrameRateNum       int64
	FrameRateDen       int64
	VideoPacketCount   int64
	VideoDurationTicks int64
	VideoTimebaseNum   int64
	VideoTimebaseDen   int64
	VideoKeyframes     string
	DolbyVisionProfile int64
	ColorTransfer      string
	Playable           int64
	ContentHash        []byte
	DeletedAt          *int64
}
