// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package schema

type AudioTrack struct {
	ID            string
	VideoID       string
	StreamIndex   int64
	Language      string
	Title         string
	Channels      int64
	ChannelLayout string
	Codec         string
}

type Download struct {
	ID                  string
	Createdat           int64
	State               string
	Title               string
	Error               string
	Torrent             []byte
	InfoHash            string
	Progress            float64
	Autoimport          int64
	PlanSeriesEditionID *string
	PlanMovieEditionID  *string
}

type DownloadPlan struct {
	DownloadID     string
	Path           string
	EpisodeID      *string
	MovieEditionID *string
	State          string
}

type Episode struct {
	ID             string
	Slug           string
	Title          string
	Summary        string
	Type           string
	Airdate        string
	Runtime        int64
	TVmazeImageURL string
}

type EpisodeVideo struct {
	EpisodeID string
	VideoID   string
}

type Movie struct {
	ID     string
	Slug   string
	TMDBID *int64
	IMDBID *string
}

type MovieEdition struct {
	ID       string
	MovieID  string
	Slug     string
	Title    string
	Label    string
	Summary  string
	Year     string
	Runtime  int64
	ImageURL string
}

type MovieVideo struct {
	MovieEditionID string
	VideoID        string
}

type Release struct {
	ID       string
	Name     string
	InfoHash *string
}

type RenditionForStreaming struct {
	ID            string
	VideoID       string
	Remux         int64
	Codec         string
	TargetBitrate int64
	MaxHeight     int64
	MaxFPS        int64
	CopyAudio     int64
	SurroundAudio int64
	Hash          string
	Playlist      string
	Priority      int64
}

type Schema struct {
	Single  int64
	Version string
	Digest  string
}

type Season struct {
	ID        string
	EditionID string
	SortKey   string
	Name      string
	Number    int64
}

type SeasonEpisode struct {
	SeasonID  string
	EpisodeID string
	SortKey   string
	Label     string
	Number    int64
}

type Series struct {
	ID          string
	Slug        string
	Title       string
	Status      string
	PremieredOn *string
	EndedOn     *string
	TVmazeID    *int64
	IMDBID      *string
	TVDBID      *int64
	TVRageID    *int64
}

type SeriesEdition struct {
	ID             string
	SeriesID       string
	Slug           string
	Label          string
	Summary        string
	TVmazeImageURL string
}

type Seriesgenre struct {
	SeriesID  string
	GenreName string
}

type Setting struct {
	Key   string
	Group string
	Value string
}

type Storage struct {
	Path     string
	Contents string
}

type Tag struct {
	ID      string
	Name    string
	OwnerID *int64
}

type Tagmovie struct {
	TagID   string
	MovieID string
}

type Tagseries struct {
	TagID    string
	SeriesID string
}

type Task struct {
	ID          string
	Type        string
	Args        string
	Failures    int64
	NextRun     int64
	FailureDesc *string
	Priority    int64
	Queue       string
	Running     int64
}

type User struct {
	ID   string
	Name string
}

type Video struct {
	ID           string
	ReleaseID    string
	ReleasePath  string
	OriginalHash string
	MVPlaylist   string
}
