// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package schema

type AudioTrack struct {
	ID            string
	VideoID       string
	StreamIndex   int64
	Language      string
	Title         string
	Channels      int64
	ChannelLayout string
	Codec         string
}

type Collection struct {
	ID       string
	Slug     string
	Title    string
	BannerID string
}

type CollectionMovie struct {
	CollectionID string
	MovieID      string
}

type CollectionSeries struct {
	CollectionID string
	SeriesID     string
}

type Download struct {
	InfoHash            string
	Createdat           int64
	State               string
	Title               string
	Error               string
	Torrent             []byte
	Progress            float64
	Autoimport          int64
	PlanSeriesEditionID *string
	PlanMovieEditionID  *string
}

type Episode struct {
	ID          string
	Title       string
	Summary     string
	Type        string
	Airdate     string
	Runtime     int64
	ThumbnailID string
}

type EpisodeVideo struct {
	EpisodeID string
	VideoID   string
}

type Image struct {
	ID   string
	Key  string
	Type string
}

type ImageRendition struct {
	Key     string
	ImageID string
	Type    string
	Width   int64
	Height  int64
}

type Movie struct {
	ID     string
	Slug   string
	TMDBID *int64
	IMDBID *string
}

type MovieEdition struct {
	ID       string
	MovieID  string
	Slug     string
	Title    string
	Label    string
	Summary  string
	Year     string
	Runtime  int64
	PosterID string
}

type MovieVideo struct {
	MovieEditionID string
	VideoID        string
}

type RenditionForStreaming struct {
	ID            string
	VideoID       string
	Remux         int64
	Codec         string
	TargetBitrate int64
	MaxHeight     int64
	MaxFPS        int64
	CopyAudio     int64
	SurroundAudio int64
	Key           string
	Playlist      string
	Priority      int64
}

type Schema struct {
	Single  int64
	Version string
	Digest  string
}

type Season struct {
	ID        string
	EditionID string
	SortKey   string
	Title     string
	Number    int64
}

type SeasonEpisode struct {
	EditionID string
	SeasonID  string
	EpisodeID string
	SortKey   int64
	Label     string
	Number    int64
	Slug      string
}

type Series struct {
	ID          string
	Slug        string
	Title       string
	Status      string
	PremieredOn string
	EndedOn     string
	TVmazeID    *int64
	IMDBID      *string
	TVDBID      *int64
	TVRageID    *int64
}

type SeriesEdition struct {
	ID       string
	SeriesID string
	Slug     string
	Label    string
	Summary  string
	PosterID string
}

type Setting struct {
	Key   string
	Group string
	Value string
}

type Slug struct {
	Slug   string
	Kind   string
	Target string
}

type Task struct {
	ID          string
	Type        string
	Args        string
	Failures    int64
	NextRun     int64
	FailureDesc *string
	Priority    int64
	Queue       string
	Running     int64
}

type User struct {
	ID   string
	Name string
}

type Video struct {
	ID          string
	InfoHash    *string
	Name        string
	State       string
	OriginalKey string
	MVPlaylist  string
}
