// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package schema

import (
	"context"
	"strings"
)

const audioTrackCreate = `-- name: AudioTrackCreate :one

INSERT INTO AudioTrack (
	VideoID, StreamIndex, Language, Title,
	Channels, ChannelLayout, Codec
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, videoid, streamindex, language, title, channels, channellayout, codec
`

type AudioTrackCreateParams struct {
	VideoID       string
	StreamIndex   int64
	Language      string
	Title         string
	Channels      int64
	ChannelLayout string
	Codec         string
}

// keep sorted by name
func (q *Queries) AudioTrackCreate(ctx context.Context, arg AudioTrackCreateParams) (AudioTrack, error) {
	row := q.db.QueryRowContext(ctx, audioTrackCreate,
		arg.VideoID,
		arg.StreamIndex,
		arg.Language,
		arg.Title,
		arg.Channels,
		arg.ChannelLayout,
		arg.Codec,
	)
	var i AudioTrack
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.StreamIndex,
		&i.Language,
		&i.Title,
		&i.Channels,
		&i.ChannelLayout,
		&i.Codec,
	)
	return i, err
}

const audioTrackDeleteByVideoID = `-- name: AudioTrackDeleteByVideoID :exec
DELETE FROM AudioTrack WHERE VideoID = ?
`

func (q *Queries) AudioTrackDeleteByVideoID(ctx context.Context, videoid string) error {
	_, err := q.db.ExecContext(ctx, audioTrackDeleteByVideoID, videoid)
	return err
}

const audioTrackListByVideoID = `-- name: AudioTrackListByVideoID :many
SELECT id, videoid, streamindex, language, title, channels, channellayout, codec FROM AudioTrack
WHERE VideoID = ?
ORDER BY StreamIndex
`

func (q *Queries) AudioTrackListByVideoID(ctx context.Context, videoid string) ([]AudioTrack, error) {
	rows, err := q.db.QueryContext(ctx, audioTrackListByVideoID, videoid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AudioTrack
	for rows.Next() {
		var i AudioTrack
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.StreamIndex,
			&i.Language,
			&i.Title,
			&i.Channels,
			&i.ChannelLayout,
			&i.Codec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorCreate = `-- name: AuthorCreate :one
INSERT INTO User (Name) VALUES (?)
RETURNING ID
`

func (q *Queries) AuthorCreate(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, authorCreate, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const authorDelete = `-- name: AuthorDelete :exec
DELETE FROM User
WHERE ID = ?
`

func (q *Queries) AuthorDelete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, authorDelete, id)
	return err
}

const authorGet = `-- name: AuthorGet :one
SELECT id, name FROM User
WHERE ID = ?
LIMIT 1
`

func (q *Queries) AuthorGet(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, authorGet, id)
	var i User
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const authorList = `-- name: AuthorList :many
SELECT id, name FROM User
ORDER BY Name
`

func (q *Queries) AuthorList(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, authorList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectionCreate = `-- name: CollectionCreate :one
INSERT INTO Collection (Slug, Title)
VALUES (?, ?)
RETURNING id, slug, title, bannerid
`

type CollectionCreateParams struct {
	Slug  string
	Title string
}

func (q *Queries) CollectionCreate(ctx context.Context, arg CollectionCreateParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, collectionCreate, arg.Slug, arg.Title)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.BannerID,
	)
	return i, err
}

const collectionGet = `-- name: CollectionGet :one
SELECT id, slug, title, bannerid FROM Collection WHERE ID = ?
`

func (q *Queries) CollectionGet(ctx context.Context, id string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, collectionGet, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.BannerID,
	)
	return i, err
}

const collectionGetBySlug = `-- name: CollectionGetBySlug :one
SELECT id, slug, title, bannerid FROM Collection WHERE Slug = ?
`

func (q *Queries) CollectionGetBySlug(ctx context.Context, slug string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, collectionGetBySlug, slug)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.BannerID,
	)
	return i, err
}

const collectionGetStats = `-- name: CollectionGetStats :one
SELECT COUNT(*) AS ItemCount, CAST(COALESCE(SUM(Runtime), 0) AS INTEGER) AS RuntimeMinutes FROM (
	SELECT MovieEdition.Runtime FROM MovieEdition
	WHERE MovieEdition.Slug = '' AND MovieEdition.MovieID IN (
		SELECT CollectionMovie.MovieID FROM CollectionMovie WHERE CollectionMovie.CollectionID = ?1
	)
	UNION ALL
	SELECT Episode.Runtime FROM Episode
	WHERE Episode.Type != 'insignificant_special' AND Episode.ID IN (
		SELECT SeasonEpisode.EpisodeID FROM SeasonEpisode WHERE SeasonEpisode.SeasonID IN (
			SELECT Season.ID FROM Season WHERE Season.EditionID IN (
				SELECT SeriesEdition.ID FROM SeriesEdition WHERE SeriesEdition.Slug = '' AND SeriesEdition.SeriesID IN (
					SELECT CollectionSeries.SeriesID FROM CollectionSeries WHERE CollectionSeries.CollectionID = ?1
				)
			)
		)
	)
)
`

type CollectionGetStatsRow struct {
	Itemcount      int64
	Runtimeminutes int64
}

func (q *Queries) CollectionGetStats(ctx context.Context, id string) (CollectionGetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, collectionGetStats, id)
	var i CollectionGetStatsRow
	err := row.Scan(&i.Itemcount, &i.Runtimeminutes)
	return i, err
}

const collectionList = `-- name: CollectionList :many
SELECT id, slug, title, bannerid FROM Collection
ORDER BY Title
`

func (q *Queries) CollectionList(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, collectionList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.BannerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectionMovieAdd = `-- name: CollectionMovieAdd :exec
INSERT INTO CollectionMovie (CollectionID, MovieID)
VALUES (?, ?)
`

type CollectionMovieAddParams struct {
	CollectionID string
	MovieID      string
}

func (q *Queries) CollectionMovieAdd(ctx context.Context, arg CollectionMovieAddParams) error {
	_, err := q.db.ExecContext(ctx, collectionMovieAdd, arg.CollectionID, arg.MovieID)
	return err
}

const collectionMovieDelete = `-- name: CollectionMovieDelete :exec
DELETE FROM CollectionMovie WHERE CollectionID = ? AND MovieID = ?
`

type CollectionMovieDeleteParams struct {
	CollectionID string
	MovieID      string
}

func (q *Queries) CollectionMovieDelete(ctx context.Context, arg CollectionMovieDeleteParams) error {
	_, err := q.db.ExecContext(ctx, collectionMovieDelete, arg.CollectionID, arg.MovieID)
	return err
}

const collectionMovieList = `-- name: CollectionMovieList :many
SELECT m.id, m.slug, m.tmdbid, m.imdbid FROM Movie m
JOIN CollectionMovie cm ON cm.MovieID = m.ID
WHERE cm.CollectionID = ?
ORDER BY m.Slug
`

func (q *Queries) CollectionMovieList(ctx context.Context, collectionid string) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, collectionMovieList, collectionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TMDBID,
			&i.IMDBID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectionSeriesAdd = `-- name: CollectionSeriesAdd :exec
INSERT INTO CollectionSeries (CollectionID, SeriesID)
VALUES (?, ?)
`

type CollectionSeriesAddParams struct {
	CollectionID string
	SeriesID     string
}

func (q *Queries) CollectionSeriesAdd(ctx context.Context, arg CollectionSeriesAddParams) error {
	_, err := q.db.ExecContext(ctx, collectionSeriesAdd, arg.CollectionID, arg.SeriesID)
	return err
}

const collectionSeriesDelete = `-- name: CollectionSeriesDelete :exec
DELETE FROM CollectionSeries WHERE CollectionID = ? AND SeriesID = ?
`

type CollectionSeriesDeleteParams struct {
	CollectionID string
	SeriesID     string
}

func (q *Queries) CollectionSeriesDelete(ctx context.Context, arg CollectionSeriesDeleteParams) error {
	_, err := q.db.ExecContext(ctx, collectionSeriesDelete, arg.CollectionID, arg.SeriesID)
	return err
}

const collectionSeriesList = `-- name: CollectionSeriesList :many
SELECT s.id, s.slug, s.title, s.status, s.premieredon, s.endedon, s.tvmazeid, s.imdbid, s.tvdbid, s.tvrageid FROM Series s
JOIN CollectionSeries cs ON cs.SeriesID = s.ID
WHERE cs.CollectionID = ?
ORDER BY s.Title
`

func (q *Queries) CollectionSeriesList(ctx context.Context, collectionid string) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, collectionSeriesList, collectionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeID,
			&i.IMDBID,
			&i.TVDBID,
			&i.TVRageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectionSetBannerID = `-- name: CollectionSetBannerID :exec
UPDATE Collection SET BannerID = ? WHERE ID = ?
`

type CollectionSetBannerIDParams struct {
	BannerID string
	ID       string
}

func (q *Queries) CollectionSetBannerID(ctx context.Context, arg CollectionSetBannerIDParams) error {
	_, err := q.db.ExecContext(ctx, collectionSetBannerID, arg.BannerID, arg.ID)
	return err
}

const collectionSetSlug = `-- name: CollectionSetSlug :exec
UPDATE Collection SET Slug = ? WHERE ID = ?
`

type CollectionSetSlugParams struct {
	Slug string
	ID   string
}

func (q *Queries) CollectionSetSlug(ctx context.Context, arg CollectionSetSlugParams) error {
	_, err := q.db.ExecContext(ctx, collectionSetSlug, arg.Slug, arg.ID)
	return err
}

const collectionSetTitle = `-- name: CollectionSetTitle :exec
UPDATE Collection SET Title = ? WHERE ID = ?
`

type CollectionSetTitleParams struct {
	Title string
	ID    string
}

func (q *Queries) CollectionSetTitle(ctx context.Context, arg CollectionSetTitleParams) error {
	_, err := q.db.ExecContext(ctx, collectionSetTitle, arg.Title, arg.ID)
	return err
}

const downloadCreate = `-- name: DownloadCreate :one
INSERT INTO Download
(
	InfoHash,
	State,
	Title,
	Torrent
)
VALUES (?, ?, ?, ?)
RETURNING infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadCreateParams struct {
	InfoHash string
	State    string
	Title    string
	Torrent  []byte
}

func (q *Queries) DownloadCreate(ctx context.Context, arg DownloadCreateParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadCreate,
		arg.InfoHash,
		arg.State,
		arg.Title,
		arg.Torrent,
	)
	var i Download
	err := row.Scan(
		&i.InfoHash,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadGet = `-- name: DownloadGet :one
SELECT infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid FROM Download WHERE InfoHash = ?
`

func (q *Queries) DownloadGet(ctx context.Context, infohash string) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadGet, infohash)
	var i Download
	err := row.Scan(
		&i.InfoHash,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadList = `-- name: DownloadList :many
SELECT infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid FROM Download
ORDER BY CreatedAt DESC
`

func (q *Queries) DownloadList(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, downloadList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.InfoHash,
			&i.Createdat,
			&i.State,
			&i.Title,
			&i.Error,
			&i.Torrent,
			&i.Progress,
			&i.Autoimport,
			&i.PlanSeriesEditionID,
			&i.PlanMovieEditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadListByPlanMovieEditionID = `-- name: DownloadListByPlanMovieEditionID :many
SELECT infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid FROM Download
WHERE PlanMovieEditionID = ?
ORDER BY CreatedAt DESC
`

func (q *Queries) DownloadListByPlanMovieEditionID(ctx context.Context, planmovieeditionid *string) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, downloadListByPlanMovieEditionID, planmovieeditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.InfoHash,
			&i.Createdat,
			&i.State,
			&i.Title,
			&i.Error,
			&i.Torrent,
			&i.Progress,
			&i.Autoimport,
			&i.PlanSeriesEditionID,
			&i.PlanMovieEditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadListByPlanSeriesEditionID = `-- name: DownloadListByPlanSeriesEditionID :many
SELECT infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid FROM Download
WHERE PlanSeriesEditionID = ?
ORDER BY CreatedAt DESC
`

func (q *Queries) DownloadListByPlanSeriesEditionID(ctx context.Context, planserieseditionid *string) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, downloadListByPlanSeriesEditionID, planserieseditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.InfoHash,
			&i.Createdat,
			&i.State,
			&i.Title,
			&i.Error,
			&i.Torrent,
			&i.Progress,
			&i.Autoimport,
			&i.PlanSeriesEditionID,
			&i.PlanMovieEditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadListInfoHashesDownloading = `-- name: DownloadListInfoHashesDownloading :many
SELECT InfoHash FROM Download
WHERE State = 'downloading'
`

func (q *Queries) DownloadListInfoHashesDownloading(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, downloadListInfoHashesDownloading)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var infohash string
		if err := rows.Scan(&infohash); err != nil {
			return nil, err
		}
		items = append(items, infohash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadPlanCountActiveByInfoHash = `-- name: DownloadPlanCountActiveByInfoHash :one
SELECT COUNT(*) FROM DownloadPlan WHERE InfoHash = ? AND State != 'imported'
`

func (q *Queries) DownloadPlanCountActiveByInfoHash(ctx context.Context, infohash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, downloadPlanCountActiveByInfoHash, infohash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const downloadPlanCountByInfoHash = `-- name: DownloadPlanCountByInfoHash :one
SELECT COUNT(*) FROM DownloadPlan WHERE InfoHash = ?
`

func (q *Queries) DownloadPlanCountByInfoHash(ctx context.Context, infohash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, downloadPlanCountByInfoHash, infohash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const downloadPlanCreate = `-- name: DownloadPlanCreate :exec
INSERT INTO DownloadPlan (InfoHash, Path, EpisodeID, MovieEditionID)
VALUES (?, ?, ?, ?)
`

type DownloadPlanCreateParams struct {
	InfoHash       string
	Path           string
	EpisodeID      *string
	MovieEditionID *string
}

func (q *Queries) DownloadPlanCreate(ctx context.Context, arg DownloadPlanCreateParams) error {
	_, err := q.db.ExecContext(ctx, downloadPlanCreate,
		arg.InfoHash,
		arg.Path,
		arg.EpisodeID,
		arg.MovieEditionID,
	)
	return err
}

const downloadPlanDeleteByInfoHash = `-- name: DownloadPlanDeleteByInfoHash :exec
DELETE FROM DownloadPlan WHERE InfoHash = ?
`

func (q *Queries) DownloadPlanDeleteByInfoHash(ctx context.Context, infohash string) error {
	_, err := q.db.ExecContext(ctx, downloadPlanDeleteByInfoHash, infohash)
	return err
}

const downloadPlanListByInfoHash = `-- name: DownloadPlanListByInfoHash :many
SELECT infohash, path, episodeid, movieeditionid, state FROM DownloadPlan WHERE InfoHash = ?
`

func (q *Queries) DownloadPlanListByInfoHash(ctx context.Context, infohash string) ([]DownloadPlan, error) {
	rows, err := q.db.QueryContext(ctx, downloadPlanListByInfoHash, infohash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DownloadPlan
	for rows.Next() {
		var i DownloadPlan
		if err := rows.Scan(
			&i.InfoHash,
			&i.Path,
			&i.EpisodeID,
			&i.MovieEditionID,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadPlanUpdateState = `-- name: DownloadPlanUpdateState :exec
UPDATE DownloadPlan SET State = ? WHERE InfoHash = ? AND Path = ?
`

type DownloadPlanUpdateStateParams struct {
	State    string
	InfoHash string
	Path     string
}

func (q *Queries) DownloadPlanUpdateState(ctx context.Context, arg DownloadPlanUpdateStateParams) error {
	_, err := q.db.ExecContext(ctx, downloadPlanUpdateState, arg.State, arg.InfoHash, arg.Path)
	return err
}

const downloadUpdateAutoImport = `-- name: DownloadUpdateAutoImport :one
UPDATE Download SET AutoImport = ? WHERE InfoHash = ? RETURNING infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdateAutoImportParams struct {
	Autoimport int64
	InfoHash   string
}

func (q *Queries) DownloadUpdateAutoImport(ctx context.Context, arg DownloadUpdateAutoImportParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdateAutoImport, arg.Autoimport, arg.InfoHash)
	var i Download
	err := row.Scan(
		&i.InfoHash,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadUpdateError = `-- name: DownloadUpdateError :one
UPDATE Download SET State = 'error', Error = ? WHERE InfoHash = ? RETURNING infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdateErrorParams struct {
	Error    string
	InfoHash string
}

func (q *Queries) DownloadUpdateError(ctx context.Context, arg DownloadUpdateErrorParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdateError, arg.Error, arg.InfoHash)
	var i Download
	err := row.Scan(
		&i.InfoHash,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadUpdatePlanMovie = `-- name: DownloadUpdatePlanMovie :one
UPDATE Download SET
	PlanMovieEditionID = ?
WHERE InfoHash = ?
RETURNING infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdatePlanMovieParams struct {
	PlanMovieEditionID *string
	InfoHash           string
}

func (q *Queries) DownloadUpdatePlanMovie(ctx context.Context, arg DownloadUpdatePlanMovieParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdatePlanMovie, arg.PlanMovieEditionID, arg.InfoHash)
	var i Download
	err := row.Scan(
		&i.InfoHash,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadUpdatePlanSeries = `-- name: DownloadUpdatePlanSeries :one
UPDATE Download SET
	PlanSeriesEditionID = ?
WHERE InfoHash = ?
RETURNING infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdatePlanSeriesParams struct {
	PlanSeriesEditionID *string
	InfoHash            string
}

func (q *Queries) DownloadUpdatePlanSeries(ctx context.Context, arg DownloadUpdatePlanSeriesParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdatePlanSeries, arg.PlanSeriesEditionID, arg.InfoHash)
	var i Download
	err := row.Scan(
		&i.InfoHash,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadUpdateProgress = `-- name: DownloadUpdateProgress :one
UPDATE Download SET
	State = ?,
	Progress = ?,
	Error = ''
WHERE InfoHash = ? RETURNING infohash, createdat, state, title, error, torrent, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdateProgressParams struct {
	State    string
	Progress float64
	InfoHash string
}

func (q *Queries) DownloadUpdateProgress(ctx context.Context, arg DownloadUpdateProgressParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdateProgress, arg.State, arg.Progress, arg.InfoHash)
	var i Download
	err := row.Scan(
		&i.InfoHash,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const episodeAirdateSet = `-- name: EpisodeAirdateSet :exec
UPDATE Episode SET Airdate = ? WHERE ID = ?
`

type EpisodeAirdateSetParams struct {
	Airdate string
	ID      string
}

func (q *Queries) EpisodeAirdateSet(ctx context.Context, arg EpisodeAirdateSetParams) error {
	_, err := q.db.ExecContext(ctx, episodeAirdateSet, arg.Airdate, arg.ID)
	return err
}

const episodeCreate = `-- name: EpisodeCreate :one
INSERT INTO Episode
(
	Title,
	Summary,
	Type,
	Airdate,
	Runtime
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title, summary, type, airdate, runtime, thumbnailid
`

type EpisodeCreateParams struct {
	Title   string
	Summary string
	Type    string
	Airdate string
	Runtime int64
}

func (q *Queries) EpisodeCreate(ctx context.Context, arg EpisodeCreateParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, episodeCreate,
		arg.Title,
		arg.Summary,
		arg.Type,
		arg.Airdate,
		arg.Runtime,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Type,
		&i.Airdate,
		&i.Runtime,
		&i.ThumbnailID,
	)
	return i, err
}

const episodeGet = `-- name: EpisodeGet :one
SELECT id, title, summary, type, airdate, runtime, thumbnailid FROM Episode WHERE ID = ?
`

func (q *Queries) EpisodeGet(ctx context.Context, id string) (Episode, error) {
	row := q.db.QueryRowContext(ctx, episodeGet, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Type,
		&i.Airdate,
		&i.Runtime,
		&i.ThumbnailID,
	)
	return i, err
}

const episodeListByEditionID = `-- name: EpisodeListByEditionID :many
SELECT id, title, summary, type, airdate, runtime, thumbnailid FROM Episode
WHERE ID IN (
	SELECT EpisodeID FROM SeasonEpisode WHERE EditionID = ?
)
ORDER BY ID
`

func (q *Queries) EpisodeListByEditionID(ctx context.Context, editionid string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, episodeListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Type,
			&i.Airdate,
			&i.Runtime,
			&i.ThumbnailID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeListBySeriesID = `-- name: EpisodeListBySeriesID :many
SELECT id, title, summary, type, airdate, runtime, thumbnailid FROM Episode
WHERE ID IN (
	SELECT EpisodeID FROM SeasonEpisode
	WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
)
ORDER BY ID
`

func (q *Queries) EpisodeListBySeriesID(ctx context.Context, seriesid string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, episodeListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Type,
			&i.Airdate,
			&i.Runtime,
			&i.ThumbnailID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeSummarySet = `-- name: EpisodeSummarySet :exec
UPDATE Episode SET Summary = ? WHERE ID = ?
`

type EpisodeSummarySetParams struct {
	Summary string
	ID      string
}

func (q *Queries) EpisodeSummarySet(ctx context.Context, arg EpisodeSummarySetParams) error {
	_, err := q.db.ExecContext(ctx, episodeSummarySet, arg.Summary, arg.ID)
	return err
}

const episodeThumbnailIDSet = `-- name: EpisodeThumbnailIDSet :exec
UPDATE Episode SET ThumbnailID = ? WHERE ID = ?
`

type EpisodeThumbnailIDSetParams struct {
	ThumbnailID string
	ID          string
}

func (q *Queries) EpisodeThumbnailIDSet(ctx context.Context, arg EpisodeThumbnailIDSetParams) error {
	_, err := q.db.ExecContext(ctx, episodeThumbnailIDSet, arg.ThumbnailID, arg.ID)
	return err
}

const episodeTitleSet = `-- name: EpisodeTitleSet :exec
UPDATE Episode SET Title = ? WHERE ID = ?
`

type EpisodeTitleSetParams struct {
	Title string
	ID    string
}

func (q *Queries) EpisodeTitleSet(ctx context.Context, arg EpisodeTitleSetParams) error {
	_, err := q.db.ExecContext(ctx, episodeTitleSet, arg.Title, arg.ID)
	return err
}

const episodeTypeSet = `-- name: EpisodeTypeSet :exec
UPDATE Episode SET Type = ? WHERE ID = ?
`

type EpisodeTypeSetParams struct {
	Type string
	ID   string
}

func (q *Queries) EpisodeTypeSet(ctx context.Context, arg EpisodeTypeSetParams) error {
	_, err := q.db.ExecContext(ctx, episodeTypeSet, arg.Type, arg.ID)
	return err
}

const episodeVideoCreate = `-- name: EpisodeVideoCreate :one
INSERT INTO EpisodeVideo (EpisodeID, VideoID)
VALUES (?, ?)
RETURNING episodeid, videoid
`

type EpisodeVideoCreateParams struct {
	EpisodeID string
	VideoID   string
}

func (q *Queries) EpisodeVideoCreate(ctx context.Context, arg EpisodeVideoCreateParams) (EpisodeVideo, error) {
	row := q.db.QueryRowContext(ctx, episodeVideoCreate, arg.EpisodeID, arg.VideoID)
	var i EpisodeVideo
	err := row.Scan(&i.EpisodeID, &i.VideoID)
	return i, err
}

const episodeVideoListByEditionID = `-- name: EpisodeVideoListByEditionID :many
SELECT episodeid, videoid FROM EpisodeVideo
WHERE EpisodeID IN (
	SELECT EpisodeID FROM SeasonEpisode WHERE EditionID = ?
)
`

func (q *Queries) EpisodeVideoListByEditionID(ctx context.Context, editionid string) ([]EpisodeVideo, error) {
	rows, err := q.db.QueryContext(ctx, episodeVideoListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeVideo
	for rows.Next() {
		var i EpisodeVideo
		if err := rows.Scan(&i.EpisodeID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeVideoListBySeriesID = `-- name: EpisodeVideoListBySeriesID :many
SELECT episodeid, videoid FROM EpisodeVideo
WHERE EpisodeID IN (
	SELECT EpisodeID FROM SeasonEpisode
	WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
)
`

func (q *Queries) EpisodeVideoListBySeriesID(ctx context.Context, seriesid string) ([]EpisodeVideo, error) {
	rows, err := q.db.QueryContext(ctx, episodeVideoListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeVideo
	for rows.Next() {
		var i EpisodeVideo
		if err := rows.Scan(&i.EpisodeID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeVideoListByVideoID = `-- name: EpisodeVideoListByVideoID :many
SELECT episodeid, videoid FROM EpisodeVideo
WHERE VideoID = ?
`

func (q *Queries) EpisodeVideoListByVideoID(ctx context.Context, videoid string) ([]EpisodeVideo, error) {
	rows, err := q.db.QueryContext(ctx, episodeVideoListByVideoID, videoid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeVideo
	for rows.Next() {
		var i EpisodeVideo
		if err := rows.Scan(&i.EpisodeID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieCreate = `-- name: MovieCreate :one
INSERT INTO Movie (ID, Slug, TMDBID, IMDBID)
VALUES (?, ?, ?, ?)
RETURNING id, slug, tmdbid, imdbid
`

type MovieCreateParams struct {
	ID     string
	Slug   string
	TMDBID *int64
	IMDBID *string
}

func (q *Queries) MovieCreate(ctx context.Context, arg MovieCreateParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, movieCreate,
		arg.ID,
		arg.Slug,
		arg.TMDBID,
		arg.IMDBID,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TMDBID,
		&i.IMDBID,
	)
	return i, err
}

const movieEditionCreate = `-- name: MovieEditionCreate :one
INSERT INTO MovieEdition (Title, Label, Slug, MovieID, Summary, Year, Runtime)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, movieid, slug, title, label, summary, year, runtime, posterid
`

type MovieEditionCreateParams struct {
	Title   string
	Label   string
	Slug    string
	MovieID string
	Summary string
	Year    string
	Runtime int64
}

func (q *Queries) MovieEditionCreate(ctx context.Context, arg MovieEditionCreateParams) (MovieEdition, error) {
	row := q.db.QueryRowContext(ctx, movieEditionCreate,
		arg.Title,
		arg.Label,
		arg.Slug,
		arg.MovieID,
		arg.Summary,
		arg.Year,
		arg.Runtime,
	)
	var i MovieEdition
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Slug,
		&i.Title,
		&i.Label,
		&i.Summary,
		&i.Year,
		&i.Runtime,
		&i.PosterID,
	)
	return i, err
}

const movieEditionGet = `-- name: MovieEditionGet :one
SELECT id, movieid, slug, title, label, summary, year, runtime, posterid FROM MovieEdition WHERE ID = ?
`

func (q *Queries) MovieEditionGet(ctx context.Context, id string) (MovieEdition, error) {
	row := q.db.QueryRowContext(ctx, movieEditionGet, id)
	var i MovieEdition
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Slug,
		&i.Title,
		&i.Label,
		&i.Summary,
		&i.Year,
		&i.Runtime,
		&i.PosterID,
	)
	return i, err
}

const movieEditionGetDefault = `-- name: MovieEditionGetDefault :one
SELECT id, movieid, slug, title, label, summary, year, runtime, posterid FROM MovieEdition WHERE MovieID = ? AND Slug = ''
`

func (q *Queries) MovieEditionGetDefault(ctx context.Context, movieid string) (MovieEdition, error) {
	row := q.db.QueryRowContext(ctx, movieEditionGetDefault, movieid)
	var i MovieEdition
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Slug,
		&i.Title,
		&i.Label,
		&i.Summary,
		&i.Year,
		&i.Runtime,
		&i.PosterID,
	)
	return i, err
}

const movieEditionLabelSet = `-- name: MovieEditionLabelSet :exec
UPDATE MovieEdition SET Label = ? WHERE ID = ?
`

type MovieEditionLabelSetParams struct {
	Label string
	ID    string
}

func (q *Queries) MovieEditionLabelSet(ctx context.Context, arg MovieEditionLabelSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionLabelSet, arg.Label, arg.ID)
	return err
}

const movieEditionListByMovieID = `-- name: MovieEditionListByMovieID :many
SELECT id, movieid, slug, title, label, summary, year, runtime, posterid FROM MovieEdition WHERE MovieID = ?
`

func (q *Queries) MovieEditionListByMovieID(ctx context.Context, movieid string) ([]MovieEdition, error) {
	rows, err := q.db.QueryContext(ctx, movieEditionListByMovieID, movieid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieEdition
	for rows.Next() {
		var i MovieEdition
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Slug,
			&i.Title,
			&i.Label,
			&i.Summary,
			&i.Year,
			&i.Runtime,
			&i.PosterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieEditionListDefault = `-- name: MovieEditionListDefault :many
SELECT id, movieid, slug, title, label, summary, year, runtime, posterid FROM MovieEdition WHERE Slug = ''
`

func (q *Queries) MovieEditionListDefault(ctx context.Context) ([]MovieEdition, error) {
	rows, err := q.db.QueryContext(ctx, movieEditionListDefault)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieEdition
	for rows.Next() {
		var i MovieEdition
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Slug,
			&i.Title,
			&i.Label,
			&i.Summary,
			&i.Year,
			&i.Runtime,
			&i.PosterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieEditionPosterIDSet = `-- name: MovieEditionPosterIDSet :exec
UPDATE MovieEdition SET PosterID = ? WHERE ID = ?
`

type MovieEditionPosterIDSetParams struct {
	PosterID string
	ID       string
}

func (q *Queries) MovieEditionPosterIDSet(ctx context.Context, arg MovieEditionPosterIDSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionPosterIDSet, arg.PosterID, arg.ID)
	return err
}

const movieEditionRuntimeSet = `-- name: MovieEditionRuntimeSet :exec
UPDATE MovieEdition SET Runtime = ? WHERE ID = ?
`

type MovieEditionRuntimeSetParams struct {
	Runtime int64
	ID      string
}

func (q *Queries) MovieEditionRuntimeSet(ctx context.Context, arg MovieEditionRuntimeSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionRuntimeSet, arg.Runtime, arg.ID)
	return err
}

const movieEditionSlugExists = `-- name: MovieEditionSlugExists :one
SELECT COUNT(*) FROM MovieEdition WHERE MovieID = ? AND Slug = ?
`

type MovieEditionSlugExistsParams struct {
	MovieID string
	Slug    string
}

func (q *Queries) MovieEditionSlugExists(ctx context.Context, arg MovieEditionSlugExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, movieEditionSlugExists, arg.MovieID, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const movieEditionSlugSet = `-- name: MovieEditionSlugSet :exec
UPDATE MovieEdition SET Slug = ? WHERE ID = ?
`

type MovieEditionSlugSetParams struct {
	Slug string
	ID   string
}

func (q *Queries) MovieEditionSlugSet(ctx context.Context, arg MovieEditionSlugSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionSlugSet, arg.Slug, arg.ID)
	return err
}

const movieEditionSummarySet = `-- name: MovieEditionSummarySet :exec
UPDATE MovieEdition SET Summary = ? WHERE ID = ?
`

type MovieEditionSummarySetParams struct {
	Summary string
	ID      string
}

func (q *Queries) MovieEditionSummarySet(ctx context.Context, arg MovieEditionSummarySetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionSummarySet, arg.Summary, arg.ID)
	return err
}

const movieEditionTitleSet = `-- name: MovieEditionTitleSet :exec
UPDATE MovieEdition SET Title = ? WHERE ID = ?
`

type MovieEditionTitleSetParams struct {
	Title string
	ID    string
}

func (q *Queries) MovieEditionTitleSet(ctx context.Context, arg MovieEditionTitleSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionTitleSet, arg.Title, arg.ID)
	return err
}

const movieEditionYearSet = `-- name: MovieEditionYearSet :exec
UPDATE MovieEdition SET Year = ? WHERE ID = ?
`

type MovieEditionYearSetParams struct {
	Year string
	ID   string
}

func (q *Queries) MovieEditionYearSet(ctx context.Context, arg MovieEditionYearSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionYearSet, arg.Year, arg.ID)
	return err
}

const movieGet = `-- name: MovieGet :one
SELECT id, slug, tmdbid, imdbid FROM Movie WHERE ID = ?
`

func (q *Queries) MovieGet(ctx context.Context, id string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, movieGet, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TMDBID,
		&i.IMDBID,
	)
	return i, err
}

const movieGetByEditionID = `-- name: MovieGetByEditionID :one
SELECT id, slug, tmdbid, imdbid FROM Movie
WHERE ID IN (SELECT MovieID FROM MovieEdition WHERE MovieEdition.ID = ?)
`

func (q *Queries) MovieGetByEditionID(ctx context.Context, id string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, movieGetByEditionID, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TMDBID,
		&i.IMDBID,
	)
	return i, err
}

const movieGetBySlug = `-- name: MovieGetBySlug :one
SELECT id, slug, tmdbid, imdbid FROM Movie WHERE Slug = ?
`

func (q *Queries) MovieGetBySlug(ctx context.Context, slug string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, movieGetBySlug, slug)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TMDBID,
		&i.IMDBID,
	)
	return i, err
}

const movieList = `-- name: MovieList :many
SELECT id, slug, tmdbid, imdbid FROM Movie
ORDER BY Slug
`

func (q *Queries) MovieList(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, movieList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TMDBID,
			&i.IMDBID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieListByTMDBID = `-- name: MovieListByTMDBID :many
SELECT id, slug, tmdbid, imdbid FROM Movie WHERE TMDBID IN (/*SLICE:ids*/?)
`

func (q *Queries) MovieListByTMDBID(ctx context.Context, ids []*int64) ([]Movie, error) {
	query := movieListByTMDBID
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TMDBID,
			&i.IMDBID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieSlugExists = `-- name: MovieSlugExists :one
SELECT COUNT(*) FROM Movie WHERE Slug = ?
`

func (q *Queries) MovieSlugExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, movieSlugExists, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const movieSlugSet = `-- name: MovieSlugSet :exec
UPDATE Movie SET Slug = ? WHERE ID = ?
`

type MovieSlugSetParams struct {
	Slug string
	ID   string
}

func (q *Queries) MovieSlugSet(ctx context.Context, arg MovieSlugSetParams) error {
	_, err := q.db.ExecContext(ctx, movieSlugSet, arg.Slug, arg.ID)
	return err
}

const movieVideoCreate = `-- name: MovieVideoCreate :one
INSERT INTO MovieVideo (MovieEditionID, VideoID)
VALUES (?, ?)
RETURNING movieeditionid, videoid
`

type MovieVideoCreateParams struct {
	MovieEditionID string
	VideoID        string
}

func (q *Queries) MovieVideoCreate(ctx context.Context, arg MovieVideoCreateParams) (MovieVideo, error) {
	row := q.db.QueryRowContext(ctx, movieVideoCreate, arg.MovieEditionID, arg.VideoID)
	var i MovieVideo
	err := row.Scan(&i.MovieEditionID, &i.VideoID)
	return i, err
}

const movieVideoListByMovieEditionID = `-- name: MovieVideoListByMovieEditionID :many
SELECT movieeditionid, videoid FROM MovieVideo
WHERE MovieEditionID = ?
`

func (q *Queries) MovieVideoListByMovieEditionID(ctx context.Context, movieeditionid string) ([]MovieVideo, error) {
	rows, err := q.db.QueryContext(ctx, movieVideoListByMovieEditionID, movieeditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieVideo
	for rows.Next() {
		var i MovieVideo
		if err := rows.Scan(&i.MovieEditionID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieVideoListByMovieID = `-- name: MovieVideoListByMovieID :many
SELECT movieeditionid, videoid FROM MovieVideo
WHERE MovieEditionID IN (SELECT ID FROM MovieEdition WHERE MovieID = ?)
`

func (q *Queries) MovieVideoListByMovieID(ctx context.Context, movieid string) ([]MovieVideo, error) {
	rows, err := q.db.QueryContext(ctx, movieVideoListByMovieID, movieid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieVideo
	for rows.Next() {
		var i MovieVideo
		if err := rows.Scan(&i.MovieEditionID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingCountUnencoded = `-- name: RenditionForStreamingCountUnencoded :one
SELECT COUNT(*) FROM RenditionForStreaming
WHERE VideoID = ? AND Hash = ''
`

func (q *Queries) RenditionForStreamingCountUnencoded(ctx context.Context, videoid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingCountUnencoded, videoid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const renditionForStreamingCreate = `-- name: RenditionForStreamingCreate :one
INSERT INTO RenditionForStreaming (
	VideoID,
	Remux,
	Codec,
	TargetBitrate,
	MaxHeight,
	MaxFPS,
	CopyAudio,
	SurroundAudio,
	Priority
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority
`

type RenditionForStreamingCreateParams struct {
	VideoID       string
	Remux         int64
	Codec         string
	TargetBitrate int64
	MaxHeight     int64
	MaxFPS        int64
	CopyAudio     int64
	SurroundAudio int64
	Priority      int64
}

func (q *Queries) RenditionForStreamingCreate(ctx context.Context, arg RenditionForStreamingCreateParams) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingCreate,
		arg.VideoID,
		arg.Remux,
		arg.Codec,
		arg.TargetBitrate,
		arg.MaxHeight,
		arg.MaxFPS,
		arg.CopyAudio,
		arg.SurroundAudio,
		arg.Priority,
	)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.SurroundAudio,
		&i.Hash,
		&i.Playlist,
		&i.Priority,
	)
	return i, err
}

const renditionForStreamingDeleteByVideoID = `-- name: RenditionForStreamingDeleteByVideoID :exec
DELETE FROM RenditionForStreaming WHERE VideoID = ?
`

func (q *Queries) RenditionForStreamingDeleteByVideoID(ctx context.Context, videoid string) error {
	_, err := q.db.ExecContext(ctx, renditionForStreamingDeleteByVideoID, videoid)
	return err
}

const renditionForStreamingGet = `-- name: RenditionForStreamingGet :one
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE ID = ?
`

func (q *Queries) RenditionForStreamingGet(ctx context.Context, id string) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingGet, id)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.SurroundAudio,
		&i.Hash,
		&i.Playlist,
		&i.Priority,
	)
	return i, err
}

const renditionForStreamingListByMovieEditionID = `-- name: RenditionForStreamingListByMovieEditionID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID IN (SELECT VideoID FROM MovieVideo WHERE MovieEditionID = ?)
`

func (q *Queries) RenditionForStreamingListByMovieEditionID(ctx context.Context, movieeditionid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListByMovieEditionID, movieeditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingListByMovieID = `-- name: RenditionForStreamingListByMovieID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID IN (
	SELECT VideoID FROM MovieVideo
	WHERE MovieEditionID IN (SELECT ID FROM MovieEdition WHERE MovieID = ?)
)
`

func (q *Queries) RenditionForStreamingListByMovieID(ctx context.Context, movieid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListByMovieID, movieid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingListByVideoID = `-- name: RenditionForStreamingListByVideoID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID  IN (SELECT VideoID FROM EpisodeVideo WHERE EpisodeID = ?)
`

func (q *Queries) RenditionForStreamingListByVideoID(ctx context.Context, episodeid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListByVideoID, episodeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingListDirectByVideoID = `-- name: RenditionForStreamingListDirectByVideoID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID = ?
`

func (q *Queries) RenditionForStreamingListDirectByVideoID(ctx context.Context, videoid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListDirectByVideoID, videoid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingListEncodedByVideoID = `-- name: RenditionForStreamingListEncodedByVideoID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID = ? AND Hash != ''
`

func (q *Queries) RenditionForStreamingListEncodedByVideoID(ctx context.Context, videoid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListEncodedByVideoID, videoid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingNextUnencoded = `-- name: RenditionForStreamingNextUnencoded :one
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID = ? AND Hash = ''
ORDER BY Priority ASC LIMIT 1
`

func (q *Queries) RenditionForStreamingNextUnencoded(ctx context.Context, videoid string) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingNextUnencoded, videoid)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.SurroundAudio,
		&i.Hash,
		&i.Playlist,
		&i.Priority,
	)
	return i, err
}

const renditionForStreamingUpdateEncode = `-- name: RenditionForStreamingUpdateEncode :one
UPDATE RenditionForStreaming
SET Hash = ?, Playlist = ?
WHERE ID = ?
RETURNING id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority
`

type RenditionForStreamingUpdateEncodeParams struct {
	Hash     string
	Playlist string
	ID       string
}

func (q *Queries) RenditionForStreamingUpdateEncode(ctx context.Context, arg RenditionForStreamingUpdateEncodeParams) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingUpdateEncode, arg.Hash, arg.Playlist, arg.ID)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.SurroundAudio,
		&i.Hash,
		&i.Playlist,
		&i.Priority,
	)
	return i, err
}

const schemaVersionGet = `-- name: SchemaVersionGet :one
SELECT version, digest FROM schema LIMIT 1
`

type SchemaVersionGetRow struct {
	Version string
	Digest  string
}

func (q *Queries) SchemaVersionGet(ctx context.Context) (SchemaVersionGetRow, error) {
	row := q.db.QueryRowContext(ctx, schemaVersionGet)
	var i SchemaVersionGetRow
	err := row.Scan(&i.Version, &i.Digest)
	return i, err
}

const schemaVersionSet = `-- name: SchemaVersionSet :exec
UPDATE schema SET version = ?, digest = ?
`

type SchemaVersionSetParams struct {
	Version string
	Digest  string
}

func (q *Queries) SchemaVersionSet(ctx context.Context, arg SchemaVersionSetParams) error {
	_, err := q.db.ExecContext(ctx, schemaVersionSet, arg.Version, arg.Digest)
	return err
}

const seasonCreate = `-- name: SeasonCreate :one
INSERT INTO Season
(
	EditionID,
	SortKey,
	Title,
	Number
)
VALUES (?, ?, ?, ?)
RETURNING id, editionid, sortkey, title, number
`

type SeasonCreateParams struct {
	EditionID string
	SortKey   string
	Title     string
	Number    int64
}

func (q *Queries) SeasonCreate(ctx context.Context, arg SeasonCreateParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, seasonCreate,
		arg.EditionID,
		arg.SortKey,
		arg.Title,
		arg.Number,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.SortKey,
		&i.Title,
		&i.Number,
	)
	return i, err
}

const seasonEpisodeCreate = `-- name: SeasonEpisodeCreate :exec
INSERT INTO SeasonEpisode (EditionID, SeasonID, EpisodeID, SortKey, Label, Number, Slug)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type SeasonEpisodeCreateParams struct {
	EditionID string
	SeasonID  string
	EpisodeID string
	SortKey   int64
	Label     string
	Number    int64
	Slug      string
}

func (q *Queries) SeasonEpisodeCreate(ctx context.Context, arg SeasonEpisodeCreateParams) error {
	_, err := q.db.ExecContext(ctx, seasonEpisodeCreate,
		arg.EditionID,
		arg.SeasonID,
		arg.EpisodeID,
		arg.SortKey,
		arg.Label,
		arg.Number,
		arg.Slug,
	)
	return err
}

const seasonEpisodeDelete = `-- name: SeasonEpisodeDelete :exec
DELETE FROM SeasonEpisode WHERE SeasonID = ? AND EpisodeID = ?
`

type SeasonEpisodeDeleteParams struct {
	SeasonID  string
	EpisodeID string
}

func (q *Queries) SeasonEpisodeDelete(ctx context.Context, arg SeasonEpisodeDeleteParams) error {
	_, err := q.db.ExecContext(ctx, seasonEpisodeDelete, arg.SeasonID, arg.EpisodeID)
	return err
}

const seasonEpisodeDeleteBySeasonID = `-- name: SeasonEpisodeDeleteBySeasonID :exec
DELETE FROM SeasonEpisode WHERE SeasonID = ?
`

func (q *Queries) SeasonEpisodeDeleteBySeasonID(ctx context.Context, seasonid string) error {
	_, err := q.db.ExecContext(ctx, seasonEpisodeDeleteBySeasonID, seasonid)
	return err
}

const seasonEpisodeGet = `-- name: SeasonEpisodeGet :one
SELECT editionid, seasonid, episodeid, sortkey, label, number, slug FROM SeasonEpisode WHERE SeasonID = ? AND EpisodeID = ?
`

type SeasonEpisodeGetParams struct {
	SeasonID  string
	EpisodeID string
}

func (q *Queries) SeasonEpisodeGet(ctx context.Context, arg SeasonEpisodeGetParams) (SeasonEpisode, error) {
	row := q.db.QueryRowContext(ctx, seasonEpisodeGet, arg.SeasonID, arg.EpisodeID)
	var i SeasonEpisode
	err := row.Scan(
		&i.EditionID,
		&i.SeasonID,
		&i.EpisodeID,
		&i.SortKey,
		&i.Label,
		&i.Number,
		&i.Slug,
	)
	return i, err
}

const seasonEpisodeGetBySlug = `-- name: SeasonEpisodeGetBySlug :one
SELECT editionid, seasonid, episodeid, sortkey, label, number, slug FROM SeasonEpisode WHERE EditionID = ? AND Slug = ?
`

type SeasonEpisodeGetBySlugParams struct {
	EditionID string
	Slug      string
}

func (q *Queries) SeasonEpisodeGetBySlug(ctx context.Context, arg SeasonEpisodeGetBySlugParams) (SeasonEpisode, error) {
	row := q.db.QueryRowContext(ctx, seasonEpisodeGetBySlug, arg.EditionID, arg.Slug)
	var i SeasonEpisode
	err := row.Scan(
		&i.EditionID,
		&i.SeasonID,
		&i.EpisodeID,
		&i.SortKey,
		&i.Label,
		&i.Number,
		&i.Slug,
	)
	return i, err
}

const seasonEpisodeListByEditionID = `-- name: SeasonEpisodeListByEditionID :many
SELECT editionid, seasonid, episodeid, sortkey, label, number, slug FROM SeasonEpisode
WHERE EditionID = ?
ORDER BY SortKey
`

func (q *Queries) SeasonEpisodeListByEditionID(ctx context.Context, editionid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.EditionID,
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonEpisodeListByEpisodeID = `-- name: SeasonEpisodeListByEpisodeID :many
SELECT editionid, seasonid, episodeid, sortkey, label, number, slug FROM SeasonEpisode WHERE EpisodeID = ?
`

func (q *Queries) SeasonEpisodeListByEpisodeID(ctx context.Context, episodeid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListByEpisodeID, episodeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.EditionID,
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonEpisodeListBySeasonID = `-- name: SeasonEpisodeListBySeasonID :many
SELECT editionid, seasonid, episodeid, sortkey, label, number, slug FROM SeasonEpisode
WHERE SeasonID = ?
ORDER BY SortKey
`

func (q *Queries) SeasonEpisodeListBySeasonID(ctx context.Context, seasonid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListBySeasonID, seasonid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.EditionID,
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonEpisodeListBySeriesID = `-- name: SeasonEpisodeListBySeriesID :many
SELECT editionid, seasonid, episodeid, sortkey, label, number, slug FROM SeasonEpisode
WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
ORDER BY SortKey
`

func (q *Queries) SeasonEpisodeListBySeriesID(ctx context.Context, seriesid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.EditionID,
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonEpisodeNumberingSet = `-- name: SeasonEpisodeNumberingSet :exec
UPDATE SeasonEpisode SET Number = ?, Label = ?, Slug = ? WHERE SeasonID = ? AND EpisodeID = ?
`

type SeasonEpisodeNumberingSetParams struct {
	Number    int64
	Label     string
	Slug      string
	SeasonID  string
	EpisodeID string
}

func (q *Queries) SeasonEpisodeNumberingSet(ctx context.Context, arg SeasonEpisodeNumberingSetParams) error {
	_, err := q.db.ExecContext(ctx, seasonEpisodeNumberingSet,
		arg.Number,
		arg.Label,
		arg.Slug,
		arg.SeasonID,
		arg.EpisodeID,
	)
	return err
}

const seasonEpisodeSlugExists = `-- name: SeasonEpisodeSlugExists :one
SELECT COUNT(*) FROM SeasonEpisode WHERE EditionID = ? AND Slug = ?
`

type SeasonEpisodeSlugExistsParams struct {
	EditionID string
	Slug      string
}

func (q *Queries) SeasonEpisodeSlugExists(ctx context.Context, arg SeasonEpisodeSlugExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, seasonEpisodeSlugExists, arg.EditionID, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seasonEpisodeSlugSet = `-- name: SeasonEpisodeSlugSet :exec
UPDATE SeasonEpisode SET Slug = ? WHERE SeasonID = ? AND EpisodeID = ?
`

type SeasonEpisodeSlugSetParams struct {
	Slug      string
	SeasonID  string
	EpisodeID string
}

func (q *Queries) SeasonEpisodeSlugSet(ctx context.Context, arg SeasonEpisodeSlugSetParams) error {
	_, err := q.db.ExecContext(ctx, seasonEpisodeSlugSet, arg.Slug, arg.SeasonID, arg.EpisodeID)
	return err
}

const seasonGet = `-- name: SeasonGet :one
SELECT id, editionid, sortkey, title, number FROM Season WHERE ID = ?
`

func (q *Queries) SeasonGet(ctx context.Context, id string) (Season, error) {
	row := q.db.QueryRowContext(ctx, seasonGet, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.SortKey,
		&i.Title,
		&i.Number,
	)
	return i, err
}

const seasonListByEditionID = `-- name: SeasonListByEditionID :many
SELECT id, editionid, sortkey, title, number FROM Season WHERE EditionID = ?
ORDER BY SortKey
`

func (q *Queries) SeasonListByEditionID(ctx context.Context, editionid string) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, seasonListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.SortKey,
			&i.Title,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonListBySeriesID = `-- name: SeasonListBySeriesID :many
SELECT id, editionid, sortkey, title, number FROM Season
WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
ORDER BY SortKey
`

func (q *Queries) SeasonListBySeriesID(ctx context.Context, seriesid string) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, seasonListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.SortKey,
			&i.Title,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonTitleSet = `-- name: SeasonTitleSet :exec
UPDATE Season SET Title = ? WHERE ID = ?
`

type SeasonTitleSetParams struct {
	Title string
	ID    string
}

func (q *Queries) SeasonTitleSet(ctx context.Context, arg SeasonTitleSetParams) error {
	_, err := q.db.ExecContext(ctx, seasonTitleSet, arg.Title, arg.ID)
	return err
}

const seriesCreate = `-- name: SeriesCreate :one
INSERT INTO Series
(
	ID,
	Slug,
	Title,
	Status,
	PremieredOn,
	EndedOn,
	TVmazeID,
	IMDBID,
	TVDBID,
	TVRageID
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, title, status, premieredon, endedon, tvmazeid, imdbid, tvdbid, tvrageid
`

type SeriesCreateParams struct {
	ID          string
	Slug        string
	Title       string
	Status      string
	PremieredOn string
	EndedOn     string
	TVmazeID    *int64
	IMDBID      *string
	TVDBID      *int64
	TVRageID    *int64
}

func (q *Queries) SeriesCreate(ctx context.Context, arg SeriesCreateParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesCreate,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Status,
		arg.PremieredOn,
		arg.EndedOn,
		arg.TVmazeID,
		arg.IMDBID,
		arg.TVDBID,
		arg.TVRageID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesEditionCreate = `-- name: SeriesEditionCreate :one
INSERT INTO SeriesEdition (Label, Slug, SeriesID, Summary)
VALUES (?, ?, ?, ?)
RETURNING id, seriesid, slug, label, summary, posterid
`

type SeriesEditionCreateParams struct {
	Label    string
	Slug     string
	SeriesID string
	Summary  string
}

func (q *Queries) SeriesEditionCreate(ctx context.Context, arg SeriesEditionCreateParams) (SeriesEdition, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionCreate,
		arg.Label,
		arg.Slug,
		arg.SeriesID,
		arg.Summary,
	)
	var i SeriesEdition
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Slug,
		&i.Label,
		&i.Summary,
		&i.PosterID,
	)
	return i, err
}

const seriesEditionGet = `-- name: SeriesEditionGet :one
SELECT id, seriesid, slug, label, summary, posterid FROM SeriesEdition WHERE ID = ?
`

func (q *Queries) SeriesEditionGet(ctx context.Context, id string) (SeriesEdition, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionGet, id)
	var i SeriesEdition
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Slug,
		&i.Label,
		&i.Summary,
		&i.PosterID,
	)
	return i, err
}

const seriesEditionGetBySlug = `-- name: SeriesEditionGetBySlug :one
SELECT seriesedition.id, seriesedition.seriesid, seriesedition.slug, seriesedition.label, seriesedition.summary, seriesedition.posterid FROM SeriesEdition
JOIN Series ON Series.ID = SeriesEdition.SeriesID
WHERE Series.Slug = ?1 AND SeriesEdition.Slug = ?2
`

type SeriesEditionGetBySlugParams struct {
	SeriesSlug  string
	EditionSlug string
}

func (q *Queries) SeriesEditionGetBySlug(ctx context.Context, arg SeriesEditionGetBySlugParams) (SeriesEdition, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionGetBySlug, arg.SeriesSlug, arg.EditionSlug)
	var i SeriesEdition
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Slug,
		&i.Label,
		&i.Summary,
		&i.PosterID,
	)
	return i, err
}

const seriesEditionLabelSet = `-- name: SeriesEditionLabelSet :exec
UPDATE SeriesEdition SET Label = ? WHERE ID = ?
`

type SeriesEditionLabelSetParams struct {
	Label string
	ID    string
}

func (q *Queries) SeriesEditionLabelSet(ctx context.Context, arg SeriesEditionLabelSetParams) error {
	_, err := q.db.ExecContext(ctx, seriesEditionLabelSet, arg.Label, arg.ID)
	return err
}

const seriesEditionListBySeriesID = `-- name: SeriesEditionListBySeriesID :many
SELECT id, seriesid, slug, label, summary, posterid FROM SeriesEdition WHERE SeriesID = ?
`

func (q *Queries) SeriesEditionListBySeriesID(ctx context.Context, seriesid string) ([]SeriesEdition, error) {
	rows, err := q.db.QueryContext(ctx, seriesEditionListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesEdition
	for rows.Next() {
		var i SeriesEdition
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Slug,
			&i.Label,
			&i.Summary,
			&i.PosterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesEditionListDefault = `-- name: SeriesEditionListDefault :many
SELECT id, seriesid, slug, label, summary, posterid FROM SeriesEdition WHERE Slug = ''
`

func (q *Queries) SeriesEditionListDefault(ctx context.Context) ([]SeriesEdition, error) {
	rows, err := q.db.QueryContext(ctx, seriesEditionListDefault)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesEdition
	for rows.Next() {
		var i SeriesEdition
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Slug,
			&i.Label,
			&i.Summary,
			&i.PosterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesEditionPosterIDSet = `-- name: SeriesEditionPosterIDSet :exec
UPDATE SeriesEdition SET PosterID = ? WHERE ID = ?
`

type SeriesEditionPosterIDSetParams struct {
	PosterID string
	ID       string
}

func (q *Queries) SeriesEditionPosterIDSet(ctx context.Context, arg SeriesEditionPosterIDSetParams) error {
	_, err := q.db.ExecContext(ctx, seriesEditionPosterIDSet, arg.PosterID, arg.ID)
	return err
}

const seriesEditionSlugExists = `-- name: SeriesEditionSlugExists :one
SELECT COUNT(*) FROM SeriesEdition WHERE SeriesID = ? AND Slug = ?
`

type SeriesEditionSlugExistsParams struct {
	SeriesID string
	Slug     string
}

func (q *Queries) SeriesEditionSlugExists(ctx context.Context, arg SeriesEditionSlugExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionSlugExists, arg.SeriesID, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seriesEditionSlugSet = `-- name: SeriesEditionSlugSet :exec
UPDATE SeriesEdition SET Slug = ? WHERE ID = ?
`

type SeriesEditionSlugSetParams struct {
	Slug string
	ID   string
}

func (q *Queries) SeriesEditionSlugSet(ctx context.Context, arg SeriesEditionSlugSetParams) error {
	_, err := q.db.ExecContext(ctx, seriesEditionSlugSet, arg.Slug, arg.ID)
	return err
}

const seriesEditionSummarySet = `-- name: SeriesEditionSummarySet :exec
UPDATE SeriesEdition SET Summary = ? WHERE ID = ?
`

type SeriesEditionSummarySetParams struct {
	Summary string
	ID      string
}

func (q *Queries) SeriesEditionSummarySet(ctx context.Context, arg SeriesEditionSummarySetParams) error {
	_, err := q.db.ExecContext(ctx, seriesEditionSummarySet, arg.Summary, arg.ID)
	return err
}

const seriesGet = `-- name: SeriesGet :one
SELECT id, slug, title, status, premieredon, endedon, tvmazeid, imdbid, tvdbid, tvrageid FROM Series WHERE ID = ?
`

func (q *Queries) SeriesGet(ctx context.Context, id string) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGet, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesGetByEditionID = `-- name: SeriesGetByEditionID :one
SELECT id, slug, title, status, premieredon, endedon, tvmazeid, imdbid, tvdbid, tvrageid FROM Series
WHERE ID IN (SELECT SeriesID FROM SeriesEdition WHERE SeriesEdition.ID = ?)
`

func (q *Queries) SeriesGetByEditionID(ctx context.Context, id string) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGetByEditionID, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesGetBySlug = `-- name: SeriesGetBySlug :one
SELECT id, slug, title, status, premieredon, endedon, tvmazeid, imdbid, tvdbid, tvrageid FROM Series WHERE Slug = ?
`

func (q *Queries) SeriesGetBySlug(ctx context.Context, slug string) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGetBySlug, slug)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesGetByTVmazeID = `-- name: SeriesGetByTVmazeID :one
SELECT id, slug, title, status, premieredon, endedon, tvmazeid, imdbid, tvdbid, tvrageid FROM Series WHERE TVmazeID = ?
`

func (q *Queries) SeriesGetByTVmazeID(ctx context.Context, tvmazeid *int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGetByTVmazeID, tvmazeid)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesList = `-- name: SeriesList :many
SELECT id, slug, title, status, premieredon, endedon, tvmazeid, imdbid, tvdbid, tvrageid FROM Series
`

func (q *Queries) SeriesList(ctx context.Context) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, seriesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeID,
			&i.IMDBID,
			&i.TVDBID,
			&i.TVRageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesListByTVmazeID = `-- name: SeriesListByTVmazeID :many
SELECT id, slug, title, status, premieredon, endedon, tvmazeid, imdbid, tvdbid, tvrageid FROM Series WHERE TVmazeID IN (/*SLICE:ids*/?)
`

func (q *Queries) SeriesListByTVmazeID(ctx context.Context, ids []*int64) ([]Series, error) {
	query := seriesListByTVmazeID
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeID,
			&i.IMDBID,
			&i.TVDBID,
			&i.TVRageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesSlugExists = `-- name: SeriesSlugExists :one
SELECT COUNT(*) FROM Series WHERE Slug = ?
`

func (q *Queries) SeriesSlugExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, seriesSlugExists, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seriesSlugSet = `-- name: SeriesSlugSet :exec
UPDATE Series SET Slug = ? WHERE ID = ?
`

type SeriesSlugSetParams struct {
	Slug string
	ID   string
}

func (q *Queries) SeriesSlugSet(ctx context.Context, arg SeriesSlugSetParams) error {
	_, err := q.db.ExecContext(ctx, seriesSlugSet, arg.Slug, arg.ID)
	return err
}

const seriesTitleSet = `-- name: SeriesTitleSet :exec
UPDATE Series SET Title = ? WHERE ID = ?
`

type SeriesTitleSetParams struct {
	Title string
	ID    string
}

func (q *Queries) SeriesTitleSet(ctx context.Context, arg SeriesTitleSetParams) error {
	_, err := q.db.ExecContext(ctx, seriesTitleSet, arg.Title, arg.ID)
	return err
}

const settingListByGroup = `-- name: SettingListByGroup :many
SELECT "key", "Group", value FROM Setting WHERE "Group" = ?
`

func (q *Queries) SettingListByGroup(ctx context.Context, group string) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, settingListByGroup, group)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Group, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settingSet = `-- name: SettingSet :exec
INSERT INTO Setting (Key, "Group", Value) VALUES (?, ?, ?)
ON CONFLICT (Key) DO UPDATE SET Value = ?3
`

type SettingSetParams struct {
	Key   string
	Group string
	Value string
}

func (q *Queries) SettingSet(ctx context.Context, arg SettingSetParams) error {
	_, err := q.db.ExecContext(ctx, settingSet, arg.Key, arg.Group, arg.Value)
	return err
}

const slugCreate = `-- name: SlugCreate :exec
INSERT INTO Slug (Slug, Kind, Target) VALUES (?, ?, ?)
`

type SlugCreateParams struct {
	Slug   string
	Kind   string
	Target string
}

func (q *Queries) SlugCreate(ctx context.Context, arg SlugCreateParams) error {
	_, err := q.db.ExecContext(ctx, slugCreate, arg.Slug, arg.Kind, arg.Target)
	return err
}

const slugDelete = `-- name: SlugDelete :exec
DELETE FROM Slug WHERE Target = ?
`

func (q *Queries) SlugDelete(ctx context.Context, target string) error {
	_, err := q.db.ExecContext(ctx, slugDelete, target)
	return err
}

const slugExists = `-- name: SlugExists :one
SELECT COUNT(*) FROM Slug WHERE Slug = ?
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, slugExists, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const slugGet = `-- name: SlugGet :one
SELECT slug, kind, target FROM Slug WHERE Slug = ?
`

func (q *Queries) SlugGet(ctx context.Context, slug string) (Slug, error) {
	row := q.db.QueryRowContext(ctx, slugGet, slug)
	var i Slug
	err := row.Scan(&i.Slug, &i.Kind, &i.Target)
	return i, err
}

const slugUpdate = `-- name: SlugUpdate :exec
UPDATE Slug SET Slug = ? WHERE Target = ?
`

type SlugUpdateParams struct {
	Slug   string
	Target string
}

func (q *Queries) SlugUpdate(ctx context.Context, arg SlugUpdateParams) error {
	_, err := q.db.ExecContext(ctx, slugUpdate, arg.Slug, arg.Target)
	return err
}

const taskCountError = `-- name: TaskCountError :one
SELECT COUNT(*) FROM Task WHERE Failures > 0
`

func (q *Queries) TaskCountError(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, taskCountError)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const taskCountQueued = `-- name: TaskCountQueued :one
SELECT COUNT(*) FROM Task WHERE Running = 0
`

func (q *Queries) TaskCountQueued(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, taskCountQueued)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const taskCreate = `-- name: TaskCreate :one
INSERT INTO Task (Type, Args, Priority, Queue, NextRun) VALUES (?, ?, ?, ?, ?)
RETURNING id, type, args, failures, nextrun, failuredesc, priority, queue, running
`

type TaskCreateParams struct {
	Type     string
	Args     string
	Priority int64
	Queue    string
	NextRun  int64
}

func (q *Queries) TaskCreate(ctx context.Context, arg TaskCreateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskCreate,
		arg.Type,
		arg.Args,
		arg.Priority,
		arg.Queue,
		arg.NextRun,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskDelete = `-- name: TaskDelete :exec
DELETE FROM Task WHERE ID = ?
`

func (q *Queries) TaskDelete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, taskDelete, id)
	return err
}

const taskGet = `-- name: TaskGet :one
SELECT id, type, args, failures, nextrun, failuredesc, priority, queue, running FROM Task WHERE ID = ?
`

func (q *Queries) TaskGet(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskGet, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskList = `-- name: TaskList :many
SELECT id, type, args, failures, nextrun, failuredesc, priority, queue, running FROM Task
WHERE Running = 0
`

func (q *Queries) TaskList(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, taskList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Args,
			&i.Failures,
			&i.NextRun,
			&i.FailureDesc,
			&i.Priority,
			&i.Queue,
			&i.Running,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskLock = `-- name: TaskLock :one
UPDATE Task SET Running = 1
WHERE ID = ? AND Running = 0
RETURNING id, type, args, failures, nextrun, failuredesc, priority, queue, running
`

func (q *Queries) TaskLock(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskLock, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskNext = `-- name: TaskNext :one
SELECT id, type, args, failures, nextrun, failuredesc, priority, queue, running FROM Task
WHERE Queue = ? AND Running = 0 AND NextRun <= ?
ORDER BY Priority, ID
LIMIT 1
`

type TaskNextParams struct {
	Queue   string
	NextRun int64
}

func (q *Queries) TaskNext(ctx context.Context, arg TaskNextParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskNext, arg.Queue, arg.NextRun)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskReschedule = `-- name: TaskReschedule :one
UPDATE Task SET
	Failures = ?,
	NextRun = ?,
	FailureDesc = ?
WHERE ID = ?
RETURNING id, type, args, failures, nextrun, failuredesc, priority, queue, running
`

type TaskRescheduleParams struct {
	Failures    int64
	NextRun     int64
	FailureDesc *string
	ID          string
}

func (q *Queries) TaskReschedule(ctx context.Context, arg TaskRescheduleParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskReschedule,
		arg.Failures,
		arg.NextRun,
		arg.FailureDesc,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskResetRunning = `-- name: TaskResetRunning :exec
UPDATE Task SET Running = 0 WHERE Running = 1
`

func (q *Queries) TaskResetRunning(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, taskResetRunning)
	return err
}

const taskSaveOneOff = `-- name: TaskSaveOneOff :exec
UPDATE Task SET
	Failures = ?,
	FailureDesc = ?
WHERE ID = ?
`

type TaskSaveOneOffParams struct {
	Failures    int64
	FailureDesc *string
	ID          string
}

func (q *Queries) TaskSaveOneOff(ctx context.Context, arg TaskSaveOneOffParams) error {
	_, err := q.db.ExecContext(ctx, taskSaveOneOff, arg.Failures, arg.FailureDesc, arg.ID)
	return err
}

const taskSetNextRun = `-- name: TaskSetNextRun :exec
UPDATE Task SET NextRun = ? WHERE ID = ?
`

type TaskSetNextRunParams struct {
	NextRun int64
	ID      string
}

func (q *Queries) TaskSetNextRun(ctx context.Context, arg TaskSetNextRunParams) error {
	_, err := q.db.ExecContext(ctx, taskSetNextRun, arg.NextRun, arg.ID)
	return err
}

const taskUnlock = `-- name: TaskUnlock :exec
UPDATE Task SET Running = 0 WHERE ID = ?
`

func (q *Queries) TaskUnlock(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, taskUnlock, id)
	return err
}

const videoCreate = `-- name: VideoCreate :one
INSERT INTO Video
(
	InfoHash,
	Name
)
VALUES (?, ?)
RETURNING id, infohash, name, originalhash, mvplaylist
`

type VideoCreateParams struct {
	InfoHash *string
	Name     string
}

func (q *Queries) VideoCreate(ctx context.Context, arg VideoCreateParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoCreate, arg.InfoHash, arg.Name)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.InfoHash,
		&i.Name,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}

const videoGet = `-- name: VideoGet :one
SELECT id, infohash, name, originalhash, mvplaylist FROM Video WHERE ID = ?
`

func (q *Queries) VideoGet(ctx context.Context, id string) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoGet, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.InfoHash,
		&i.Name,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}

const videoGetByName = `-- name: VideoGetByName :one
SELECT id, infohash, name, originalhash, mvplaylist FROM Video WHERE InfoHash = ? AND Name = ?
`

type VideoGetByNameParams struct {
	InfoHash *string
	Name     string
}

func (q *Queries) VideoGetByName(ctx context.Context, arg VideoGetByNameParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoGetByName, arg.InfoHash, arg.Name)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.InfoHash,
		&i.Name,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}

const videoListByEditionID = `-- name: VideoListByEditionID :many
SELECT id, infohash, name, originalhash, mvplaylist FROM Video
WHERE ID IN (
	SELECT VideoID FROM EpisodeVideo
	WHERE EpisodeID IN (
		SELECT EpisodeID FROM SeasonEpisode WHERE EditionID = ?
	)
)
`

func (q *Queries) VideoListByEditionID(ctx context.Context, editionid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.InfoHash,
			&i.Name,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoListByEpisodeID = `-- name: VideoListByEpisodeID :many
SELECT id, infohash, name, originalhash, mvplaylist FROM Video
WHERE ID IN (SELECT VideoID FROM EpisodeVideo WHERE EpisodeID = ?)
`

func (q *Queries) VideoListByEpisodeID(ctx context.Context, episodeid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListByEpisodeID, episodeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.InfoHash,
			&i.Name,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoListByMovieEditionID = `-- name: VideoListByMovieEditionID :many
SELECT id, infohash, name, originalhash, mvplaylist FROM Video
WHERE ID IN (SELECT VideoID FROM MovieVideo WHERE MovieEditionID = ?)
`

func (q *Queries) VideoListByMovieEditionID(ctx context.Context, movieeditionid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListByMovieEditionID, movieeditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.InfoHash,
			&i.Name,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoListByMovieID = `-- name: VideoListByMovieID :many
SELECT id, infohash, name, originalhash, mvplaylist FROM Video
WHERE ID IN (
	SELECT VideoID FROM MovieVideo
	WHERE MovieEditionID IN (SELECT ID FROM MovieEdition WHERE MovieID = ?)
)
`

func (q *Queries) VideoListByMovieID(ctx context.Context, movieid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListByMovieID, movieid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.InfoHash,
			&i.Name,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoListBySeriesID = `-- name: VideoListBySeriesID :many
SELECT id, infohash, name, originalhash, mvplaylist FROM Video
WHERE ID IN (
	SELECT VideoID FROM EpisodeVideo
	WHERE EpisodeID IN (
		SELECT EpisodeID FROM SeasonEpisode
		WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
	)
)
`

func (q *Queries) VideoListBySeriesID(ctx context.Context, seriesid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.InfoHash,
			&i.Name,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoUpdateMVPlaylist = `-- name: VideoUpdateMVPlaylist :one
UPDATE Video SET MVPlaylist = ? WHERE ID = ?
RETURNING id, infohash, name, originalhash, mvplaylist
`

type VideoUpdateMVPlaylistParams struct {
	MVPlaylist string
	ID         string
}

func (q *Queries) VideoUpdateMVPlaylist(ctx context.Context, arg VideoUpdateMVPlaylistParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoUpdateMVPlaylist, arg.MVPlaylist, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.InfoHash,
		&i.Name,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}

const videoUpdateOriginalHash = `-- name: VideoUpdateOriginalHash :one
UPDATE Video SET OriginalHash = ? WHERE ID = ?
RETURNING id, infohash, name, originalhash, mvplaylist
`

type VideoUpdateOriginalHashParams struct {
	OriginalHash string
	ID           string
}

func (q *Queries) VideoUpdateOriginalHash(ctx context.Context, arg VideoUpdateOriginalHashParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoUpdateOriginalHash, arg.OriginalHash, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.InfoHash,
		&i.Name,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}
