// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package schema

import (
	"context"
	"strings"
)

const authorCreate = `-- name: AuthorCreate :one
INSERT INTO User (Name) VALUES (?)
RETURNING ID
`

func (q *Queries) AuthorCreate(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, authorCreate, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const authorDelete = `-- name: AuthorDelete :exec
DELETE FROM User
WHERE ID = ?
`

func (q *Queries) AuthorDelete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, authorDelete, id)
	return err
}

const authorGet = `-- name: AuthorGet :one
SELECT id, name FROM User
WHERE ID = ?
LIMIT 1
`

func (q *Queries) AuthorGet(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, authorGet, id)
	var i User
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const authorList = `-- name: AuthorList :many
SELECT id, name FROM User
ORDER BY Name
`

func (q *Queries) AuthorList(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, authorList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadCreate = `-- name: DownloadCreate :one
INSERT INTO Download
(
	State,
	Title,
	Torrent,
	InfoHash,
	PlanSeriesEditionID,
	Plan
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, createdat, state, title, error, torrent, infohash, progress, planserieseditionid, "plan"
`

type DownloadCreateParams struct {
	State               string
	Title               string
	Torrent             []byte
	InfoHash            string
	PlanSeriesEditionID *string
	Plan                string
}

func (q *Queries) DownloadCreate(ctx context.Context, arg DownloadCreateParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadCreate,
		arg.State,
		arg.Title,
		arg.Torrent,
		arg.InfoHash,
		arg.PlanSeriesEditionID,
		arg.Plan,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.PlanSeriesEditionID,
		&i.Plan,
	)
	return i, err
}

const downloadGet = `-- name: DownloadGet :one
SELECT id, createdat, state, title, error, torrent, infohash, progress, planserieseditionid, "plan" FROM Download WHERE ID = ?
`

func (q *Queries) DownloadGet(ctx context.Context, id string) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadGet, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.PlanSeriesEditionID,
		&i.Plan,
	)
	return i, err
}

const downloadGetByInfoHash = `-- name: DownloadGetByInfoHash :one
SELECT id, createdat, state, title, error, torrent, infohash, progress, planserieseditionid, "plan" FROM Download WHERE InfoHash = ?
`

func (q *Queries) DownloadGetByInfoHash(ctx context.Context, infohash string) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadGetByInfoHash, infohash)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.PlanSeriesEditionID,
		&i.Plan,
	)
	return i, err
}

const downloadList = `-- name: DownloadList :many
SELECT id, createdat, state, title, error, torrent, infohash, progress, planserieseditionid, "plan" FROM Download
ORDER BY ID DESC
`

func (q *Queries) DownloadList(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, downloadList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.State,
			&i.Title,
			&i.Error,
			&i.Torrent,
			&i.InfoHash,
			&i.Progress,
			&i.PlanSeriesEditionID,
			&i.Plan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadListByPlanSeriesEditionID = `-- name: DownloadListByPlanSeriesEditionID :many
SELECT id, createdat, state, title, error, torrent, infohash, progress, planserieseditionid, "plan" FROM Download
WHERE PlanSeriesEditionID = ?
ORDER BY ID DESC
`

func (q *Queries) DownloadListByPlanSeriesEditionID(ctx context.Context, planserieseditionid *string) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, downloadListByPlanSeriesEditionID, planserieseditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.State,
			&i.Title,
			&i.Error,
			&i.Torrent,
			&i.InfoHash,
			&i.Progress,
			&i.PlanSeriesEditionID,
			&i.Plan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadListInfoHashesActive = `-- name: DownloadListInfoHashesActive :many
SELECT InfoHash FROM Download
WHERE State = 'active'
`

func (q *Queries) DownloadListInfoHashesActive(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, downloadListInfoHashesActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var infohash string
		if err := rows.Scan(&infohash); err != nil {
			return nil, err
		}
		items = append(items, infohash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadUpdateError = `-- name: DownloadUpdateError :one
UPDATE Download SET State = 'error', Error = ? WHERE ID = ? RETURNING id, createdat, state, title, error, torrent, infohash, progress, planserieseditionid, "plan"
`

type DownloadUpdateErrorParams struct {
	Error string
	ID    string
}

func (q *Queries) DownloadUpdateError(ctx context.Context, arg DownloadUpdateErrorParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdateError, arg.Error, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.PlanSeriesEditionID,
		&i.Plan,
	)
	return i, err
}

const downloadUpdatePlan = `-- name: DownloadUpdatePlan :one
UPDATE Download SET
	PlanSeriesEditionID = ?,
	Plan = ?
WHERE ID = ?
RETURNING id, createdat, state, title, error, torrent, infohash, progress, planserieseditionid, "plan"
`

type DownloadUpdatePlanParams struct {
	PlanSeriesEditionID *string
	Plan                string
	ID                  string
}

func (q *Queries) DownloadUpdatePlan(ctx context.Context, arg DownloadUpdatePlanParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdatePlan, arg.PlanSeriesEditionID, arg.Plan, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.PlanSeriesEditionID,
		&i.Plan,
	)
	return i, err
}

const downloadUpdateProgress = `-- name: DownloadUpdateProgress :one
UPDATE Download SET
	State = ?,
	Plan = ?,
	Progress = ?,
	Error = ''
WHERE ID = ? RETURNING id, createdat, state, title, error, torrent, infohash, progress, planserieseditionid, "plan"
`

type DownloadUpdateProgressParams struct {
	State    string
	Plan     string
	Progress float64
	ID       string
}

func (q *Queries) DownloadUpdateProgress(ctx context.Context, arg DownloadUpdateProgressParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdateProgress,
		arg.State,
		arg.Plan,
		arg.Progress,
		arg.ID,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.PlanSeriesEditionID,
		&i.Plan,
	)
	return i, err
}

const episodeCreate = `-- name: EpisodeCreate :one
INSERT INTO Episode
(
	Title,
	Summary,
	Type,
	Airdate,
	Runtime,
	TVmazeURL,
	TVmazeImageURL
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, summary, type, airdate, runtime, tvmazeurl, tvmazeimageurl
`

type EpisodeCreateParams struct {
	Title          string
	Summary        string
	Type           string
	Airdate        *string
	Runtime        int64
	TVmazeURL      *string
	TVmazeImageURL string
}

func (q *Queries) EpisodeCreate(ctx context.Context, arg EpisodeCreateParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, episodeCreate,
		arg.Title,
		arg.Summary,
		arg.Type,
		arg.Airdate,
		arg.Runtime,
		arg.TVmazeURL,
		arg.TVmazeImageURL,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Type,
		&i.Airdate,
		&i.Runtime,
		&i.TVmazeURL,
		&i.TVmazeImageURL,
	)
	return i, err
}

const episodeGet = `-- name: EpisodeGet :one
SELECT id, title, summary, type, airdate, runtime, tvmazeurl, tvmazeimageurl FROM Episode WHERE ID = ?
`

func (q *Queries) EpisodeGet(ctx context.Context, id string) (Episode, error) {
	row := q.db.QueryRowContext(ctx, episodeGet, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Type,
		&i.Airdate,
		&i.Runtime,
		&i.TVmazeURL,
		&i.TVmazeImageURL,
	)
	return i, err
}

const episodeListByEditionID = `-- name: EpisodeListByEditionID :many
SELECT id, title, summary, type, airdate, runtime, tvmazeurl, tvmazeimageurl FROM Episode
WHERE ID IN (
	SELECT ID FROM SeasonEpisode
	WHERE SeasonID IN (SELECT ID FROM Season WHERE EditionID = ?)
)
ORDER BY ID
`

func (q *Queries) EpisodeListByEditionID(ctx context.Context, editionid string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, episodeListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Type,
			&i.Airdate,
			&i.Runtime,
			&i.TVmazeURL,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeListBySeriesID = `-- name: EpisodeListBySeriesID :many
SELECT id, title, summary, type, airdate, runtime, tvmazeurl, tvmazeimageurl FROM Episode
WHERE ID IN (
	SELECT ID FROM SeasonEpisode
	WHERE SeasonID IN (
		SELECT ID FROM Season
		WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
	)
)
ORDER BY ID
`

func (q *Queries) EpisodeListBySeriesID(ctx context.Context, seriesid string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, episodeListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Type,
			&i.Airdate,
			&i.Runtime,
			&i.TVmazeURL,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeVideoCreate = `-- name: EpisodeVideoCreate :one
INSERT INTO EpisodeVideo (EpisodeID, VideoID)
VALUES (?, ?)
RETURNING episodeid, videoid
`

type EpisodeVideoCreateParams struct {
	EpisodeID string
	VideoID   string
}

func (q *Queries) EpisodeVideoCreate(ctx context.Context, arg EpisodeVideoCreateParams) (EpisodeVideo, error) {
	row := q.db.QueryRowContext(ctx, episodeVideoCreate, arg.EpisodeID, arg.VideoID)
	var i EpisodeVideo
	err := row.Scan(&i.EpisodeID, &i.VideoID)
	return i, err
}

const movieList = `-- name: MovieList :many
SELECT ID, Title, ArtworkKey FROM Movie
`

func (q *Queries) MovieList(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, movieList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(&i.ID, &i.Title, &i.ArtworkKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseCreate = `-- name: ReleaseCreate :one
INSERT INTO Release
(
	Name,
	InfoHash
)
VALUES (?, ?)
RETURNING id, name, infohash
`

type ReleaseCreateParams struct {
	Name     string
	InfoHash *string
}

func (q *Queries) ReleaseCreate(ctx context.Context, arg ReleaseCreateParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, releaseCreate, arg.Name, arg.InfoHash)
	var i Release
	err := row.Scan(&i.ID, &i.Name, &i.InfoHash)
	return i, err
}

const releaseGetByInfoHash = `-- name: ReleaseGetByInfoHash :one
SELECT id, name, infohash FROM Release WHERE InfoHash = ?
`

func (q *Queries) ReleaseGetByInfoHash(ctx context.Context, infohash *string) (Release, error) {
	row := q.db.QueryRowContext(ctx, releaseGetByInfoHash, infohash)
	var i Release
	err := row.Scan(&i.ID, &i.Name, &i.InfoHash)
	return i, err
}

const renditionForStreamingCreate = `-- name: RenditionForStreamingCreate :one
INSERT INTO RenditionForStreaming (
	VideoID,
	Remux,
	Codec,
	TargetBitrate,
	MaxHeight,
	MaxFPS,
	CopyAudio
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, hash, playlist
`

type RenditionForStreamingCreateParams struct {
	VideoID       string
	Remux         int64
	Codec         string
	TargetBitrate int64
	MaxHeight     int64
	MaxFPS        int64
	CopyAudio     int64
}

func (q *Queries) RenditionForStreamingCreate(ctx context.Context, arg RenditionForStreamingCreateParams) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingCreate,
		arg.VideoID,
		arg.Remux,
		arg.Codec,
		arg.TargetBitrate,
		arg.MaxHeight,
		arg.MaxFPS,
		arg.CopyAudio,
	)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.Hash,
		&i.Playlist,
	)
	return i, err
}

const renditionForStreamingListByVideoID = `-- name: RenditionForStreamingListByVideoID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, hash, playlist FROM RenditionForStreaming
WHERE VideoID  IN (SELECT VideoID FROM EpisodeVideo WHERE EpisodeID = ?)
`

func (q *Queries) RenditionForStreamingListByVideoID(ctx context.Context, episodeid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListByVideoID, episodeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.Hash,
			&i.Playlist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingListDirectByVideoID = `-- name: RenditionForStreamingListDirectByVideoID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, hash, playlist FROM RenditionForStreaming
WHERE VideoID = ?
`

func (q *Queries) RenditionForStreamingListDirectByVideoID(ctx context.Context, videoid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListDirectByVideoID, videoid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.Hash,
			&i.Playlist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingUpdateEncode = `-- name: RenditionForStreamingUpdateEncode :one
UPDATE RenditionForStreaming
SET Hash = ?, Playlist = ?
WHERE ID = ?
RETURNING id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, hash, playlist
`

type RenditionForStreamingUpdateEncodeParams struct {
	Hash     string
	Playlist string
	ID       string
}

func (q *Queries) RenditionForStreamingUpdateEncode(ctx context.Context, arg RenditionForStreamingUpdateEncodeParams) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingUpdateEncode, arg.Hash, arg.Playlist, arg.ID)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.Hash,
		&i.Playlist,
	)
	return i, err
}

const schemaVersionGet = `-- name: SchemaVersionGet :one
SELECT version, digest FROM schema LIMIT 1
`

type SchemaVersionGetRow struct {
	Version string
	Digest  string
}

func (q *Queries) SchemaVersionGet(ctx context.Context) (SchemaVersionGetRow, error) {
	row := q.db.QueryRowContext(ctx, schemaVersionGet)
	var i SchemaVersionGetRow
	err := row.Scan(&i.Version, &i.Digest)
	return i, err
}

const schemaVersionSet = `-- name: SchemaVersionSet :exec
UPDATE schema SET version = ?, digest = ?
`

type SchemaVersionSetParams struct {
	Version string
	Digest  string
}

func (q *Queries) SchemaVersionSet(ctx context.Context, arg SchemaVersionSetParams) error {
	_, err := q.db.ExecContext(ctx, schemaVersionSet, arg.Version, arg.Digest)
	return err
}

const seasonCreate = `-- name: SeasonCreate :one
INSERT INTO Season
(
	EditionID,
	SortKey,
	Name,
	Number,
	TVmazeURL,
	Summary,
	EpisodeOrder,
	PremieredOn,
	EndedOn,
	TVmazeImageURL
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, editionid, sortkey, name, number, tvmazeurl, summary, episodeorder, premieredon, endedon, tvmazeimageurl
`

type SeasonCreateParams struct {
	EditionID      string
	SortKey        string
	Name           string
	Number         int64
	TVmazeURL      *string
	Summary        string
	EpisodeOrder   int64
	PremieredOn    *string
	EndedOn        *string
	TVmazeImageURL string
}

func (q *Queries) SeasonCreate(ctx context.Context, arg SeasonCreateParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, seasonCreate,
		arg.EditionID,
		arg.SortKey,
		arg.Name,
		arg.Number,
		arg.TVmazeURL,
		arg.Summary,
		arg.EpisodeOrder,
		arg.PremieredOn,
		arg.EndedOn,
		arg.TVmazeImageURL,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.SortKey,
		&i.Name,
		&i.Number,
		&i.TVmazeURL,
		&i.Summary,
		&i.EpisodeOrder,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeImageURL,
	)
	return i, err
}

const seasonEpisodeCreate = `-- name: SeasonEpisodeCreate :exec
INSERT INTO SeasonEpisode (SeasonID, EpisodeID, SortKey, Label, Number)
VALUES (?, ?, ?, ?, ?)
`

type SeasonEpisodeCreateParams struct {
	SeasonID  string
	EpisodeID string
	SortKey   string
	Label     string
	Number    *int64
}

func (q *Queries) SeasonEpisodeCreate(ctx context.Context, arg SeasonEpisodeCreateParams) error {
	_, err := q.db.ExecContext(ctx, seasonEpisodeCreate,
		arg.SeasonID,
		arg.EpisodeID,
		arg.SortKey,
		arg.Label,
		arg.Number,
	)
	return err
}

const seasonEpisodeListByEditionID = `-- name: SeasonEpisodeListByEditionID :many
SELECT seasonid, episodeid, sortkey, label, number FROM SeasonEpisode
WHERE SeasonID IN (SELECT ID FROM Season WHERE EditionID = ?)
ORDER BY SortKey
`

func (q *Queries) SeasonEpisodeListByEditionID(ctx context.Context, editionid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonEpisodeListByEpisodeID = `-- name: SeasonEpisodeListByEpisodeID :many
SELECT seasonid, episodeid, sortkey, label, number FROM SeasonEpisode WHERE EpisodeID = ?
`

func (q *Queries) SeasonEpisodeListByEpisodeID(ctx context.Context, episodeid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListByEpisodeID, episodeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonEpisodeListBySeriesID = `-- name: SeasonEpisodeListBySeriesID :many
SELECT seasonid, episodeid, sortkey, label, number FROM SeasonEpisode
WHERE SeasonID IN (
	SELECT ID FROM Season
	WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
)
ORDER BY SortKey
`

func (q *Queries) SeasonEpisodeListBySeriesID(ctx context.Context, seriesid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonGet = `-- name: SeasonGet :one
SELECT id, editionid, sortkey, name, number, tvmazeurl, summary, episodeorder, premieredon, endedon, tvmazeimageurl FROM Season WHERE ID = ?
`

func (q *Queries) SeasonGet(ctx context.Context, id string) (Season, error) {
	row := q.db.QueryRowContext(ctx, seasonGet, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.SortKey,
		&i.Name,
		&i.Number,
		&i.TVmazeURL,
		&i.Summary,
		&i.EpisodeOrder,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeImageURL,
	)
	return i, err
}

const seasonListByEditionID = `-- name: SeasonListByEditionID :many
SELECT id, editionid, sortkey, name, number, tvmazeurl, summary, episodeorder, premieredon, endedon, tvmazeimageurl FROM Season WHERE EditionID = ?
ORDER BY SortKey
`

func (q *Queries) SeasonListByEditionID(ctx context.Context, editionid string) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, seasonListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.SortKey,
			&i.Name,
			&i.Number,
			&i.TVmazeURL,
			&i.Summary,
			&i.EpisodeOrder,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonListBySeriesID = `-- name: SeasonListBySeriesID :many
SELECT id, editionid, sortkey, name, number, tvmazeurl, summary, episodeorder, premieredon, endedon, tvmazeimageurl FROM Season
WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
ORDER BY SortKey
`

func (q *Queries) SeasonListBySeriesID(ctx context.Context, seriesid string) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, seasonListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.SortKey,
			&i.Name,
			&i.Number,
			&i.TVmazeURL,
			&i.Summary,
			&i.EpisodeOrder,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesCreate = `-- name: SeriesCreate :one
INSERT INTO Series
(
	Title,
	Summary,
	Status,
	Language,
	PremieredOn,
	EndedOn,
	TVmazeID,
	TVmazeURL,
	TVmazeImageURL,
	TVmazeUpdatedAt,
	IMDBID,
	TVDBID,
	TVRageID
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, summary, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeimageurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid
`

type SeriesCreateParams struct {
	Title           string
	Summary         string
	Status          string
	Language        string
	PremieredOn     *string
	EndedOn         *string
	TVmazeID        *int64
	TVmazeURL       *string
	TVmazeImageURL  string
	TVmazeUpdatedAt int64
	IMDBID          *string
	TVDBID          *int64
	TVRageID        *int64
}

func (q *Queries) SeriesCreate(ctx context.Context, arg SeriesCreateParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesCreate,
		arg.Title,
		arg.Summary,
		arg.Status,
		arg.Language,
		arg.PremieredOn,
		arg.EndedOn,
		arg.TVmazeID,
		arg.TVmazeURL,
		arg.TVmazeImageURL,
		arg.TVmazeUpdatedAt,
		arg.IMDBID,
		arg.TVDBID,
		arg.TVRageID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.Language,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.TVmazeURL,
		&i.TVmazeImageURL,
		&i.TVmazeUpdatedAt,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesEditionCreate = `-- name: SeriesEditionCreate :one
INSERT INTO SeriesEdition (Title, SeriesID) VALUES (?, ?)
RETURNING id, title, seriesid
`

type SeriesEditionCreateParams struct {
	Title    string
	SeriesID string
}

func (q *Queries) SeriesEditionCreate(ctx context.Context, arg SeriesEditionCreateParams) (SeriesEdition, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionCreate, arg.Title, arg.SeriesID)
	var i SeriesEdition
	err := row.Scan(&i.ID, &i.Title, &i.SeriesID)
	return i, err
}

const seriesEditionGet = `-- name: SeriesEditionGet :one
SELECT id, title, seriesid FROM SeriesEdition WHERE ID = ?
`

func (q *Queries) SeriesEditionGet(ctx context.Context, id string) (SeriesEdition, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionGet, id)
	var i SeriesEdition
	err := row.Scan(&i.ID, &i.Title, &i.SeriesID)
	return i, err
}

const seriesEditionListBySeriesID = `-- name: SeriesEditionListBySeriesID :many
SELECT id, title, seriesid FROM SeriesEdition WHERE SeriesID = ?
`

func (q *Queries) SeriesEditionListBySeriesID(ctx context.Context, seriesid string) ([]SeriesEdition, error) {
	rows, err := q.db.QueryContext(ctx, seriesEditionListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesEdition
	for rows.Next() {
		var i SeriesEdition
		if err := rows.Scan(&i.ID, &i.Title, &i.SeriesID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesGenreAdd = `-- name: SeriesGenreAdd :exec
INSERT INTO SeriesGenre (SeriesID, GenreName) VALUES (?, ?)
`

type SeriesGenreAddParams struct {
	SeriesID  string
	GenreName string
}

func (q *Queries) SeriesGenreAdd(ctx context.Context, arg SeriesGenreAddParams) error {
	_, err := q.db.ExecContext(ctx, seriesGenreAdd, arg.SeriesID, arg.GenreName)
	return err
}

const seriesGenreList = `-- name: SeriesGenreList :many
SELECT GenreName FROM SeriesGenre WHERE SeriesID = ?
`

func (q *Queries) SeriesGenreList(ctx context.Context, seriesid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, seriesGenreList, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var genrename string
		if err := rows.Scan(&genrename); err != nil {
			return nil, err
		}
		items = append(items, genrename)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesGet = `-- name: SeriesGet :one
SELECT id, title, summary, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeimageurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series WHERE ID = ?
`

func (q *Queries) SeriesGet(ctx context.Context, id string) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGet, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.Language,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.TVmazeURL,
		&i.TVmazeImageURL,
		&i.TVmazeUpdatedAt,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesGetByEditionID = `-- name: SeriesGetByEditionID :one
SELECT id, title, summary, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeimageurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series
WHERE ID IN (SELECT SeriesID FROM SeriesEdition WHERE SeriesEdition.ID = ?)
`

func (q *Queries) SeriesGetByEditionID(ctx context.Context, id string) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGetByEditionID, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.Language,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.TVmazeURL,
		&i.TVmazeImageURL,
		&i.TVmazeUpdatedAt,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesGetByTVmazeID = `-- name: SeriesGetByTVmazeID :one
SELECT id, title, summary, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeimageurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series WHERE TVmazeID = ?
`

func (q *Queries) SeriesGetByTVmazeID(ctx context.Context, tvmazeid *int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGetByTVmazeID, tvmazeid)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.Language,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.TVmazeURL,
		&i.TVmazeImageURL,
		&i.TVmazeUpdatedAt,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesList = `-- name: SeriesList :many
SELECT id, title, summary, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeimageurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series
`

func (q *Queries) SeriesList(ctx context.Context) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, seriesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Status,
			&i.Language,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeID,
			&i.TVmazeURL,
			&i.TVmazeImageURL,
			&i.TVmazeUpdatedAt,
			&i.IMDBID,
			&i.TVDBID,
			&i.TVRageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesListByTVmazeID = `-- name: SeriesListByTVmazeID :many
SELECT id, title, summary, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeimageurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series WHERE TVmazeID IN (/*SLICE:ids*/?)
`

func (q *Queries) SeriesListByTVmazeID(ctx context.Context, ids []*int64) ([]Series, error) {
	query := seriesListByTVmazeID
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Status,
			&i.Language,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeID,
			&i.TVmazeURL,
			&i.TVmazeImageURL,
			&i.TVmazeUpdatedAt,
			&i.IMDBID,
			&i.TVDBID,
			&i.TVRageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageCreate = `-- name: StorageCreate :exec
INSERT INTO Storage (Path, Contents) VALUES (?, ?)
`

type StorageCreateParams struct {
	Path     string
	Contents string
}

func (q *Queries) StorageCreate(ctx context.Context, arg StorageCreateParams) error {
	_, err := q.db.ExecContext(ctx, storageCreate, arg.Path, arg.Contents)
	return err
}

const storageList = `-- name: StorageList :many
SELECT path, contents FROM Storage
`

func (q *Queries) StorageList(ctx context.Context) ([]Storage, error) {
	rows, err := q.db.QueryContext(ctx, storageList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storage
	for rows.Next() {
		var i Storage
		if err := rows.Scan(&i.Path, &i.Contents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskCreate = `-- name: TaskCreate :one
INSERT INTO Task (Type, Args) VALUES (?, ?)
RETURNING id, type, args, failures, nextrun, failuredesc
`

type TaskCreateParams struct {
	Type string
	Args string
}

func (q *Queries) TaskCreate(ctx context.Context, arg TaskCreateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskCreate, arg.Type, arg.Args)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
	)
	return i, err
}

const taskDelete = `-- name: TaskDelete :exec
DELETE FROM Task WHERE ID = ?
`

func (q *Queries) TaskDelete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, taskDelete, id)
	return err
}

const taskGet = `-- name: TaskGet :one
SELECT id, type, args, failures, nextrun, failuredesc FROM Task WHERE ID = ?
`

func (q *Queries) TaskGet(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskGet, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
	)
	return i, err
}

const taskList = `-- name: TaskList :many
SELECT id, type, args, failures, nextrun, failuredesc FROM Task
`

func (q *Queries) TaskList(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, taskList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Args,
			&i.Failures,
			&i.NextRun,
			&i.FailureDesc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskReschedule = `-- name: TaskReschedule :one
UPDATE Task SET
	Failures = ?,
	NextRun = ?,
	FailureDesc = ?
WHERE ID = ?
RETURNING id, type, args, failures, nextrun, failuredesc
`

type TaskRescheduleParams struct {
	Failures    int64
	NextRun     int64
	FailureDesc *string
	ID          string
}

func (q *Queries) TaskReschedule(ctx context.Context, arg TaskRescheduleParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskReschedule,
		arg.Failures,
		arg.NextRun,
		arg.FailureDesc,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
	)
	return i, err
}

const taskSaveOneOff = `-- name: TaskSaveOneOff :exec
UPDATE Task SET
	Failures = ?,
	FailureDesc = ?
WHERE ID = ?
`

type TaskSaveOneOffParams struct {
	Failures    int64
	FailureDesc *string
	ID          string
}

func (q *Queries) TaskSaveOneOff(ctx context.Context, arg TaskSaveOneOffParams) error {
	_, err := q.db.ExecContext(ctx, taskSaveOneOff, arg.Failures, arg.FailureDesc, arg.ID)
	return err
}

const transmissionGet = `-- name: TransmissionGet :one
SELECT Path, BaseURL FROM ConfigTransmission LIMIT 1
`

type TransmissionGetRow struct {
	Path    string
	BaseURL string
}

func (q *Queries) TransmissionGet(ctx context.Context) (TransmissionGetRow, error) {
	row := q.db.QueryRowContext(ctx, transmissionGet)
	var i TransmissionGetRow
	err := row.Scan(&i.Path, &i.BaseURL)
	return i, err
}

const transmissionSet = `-- name: TransmissionSet :exec
INSERT INTO ConfigTransmission (Single, Path, BaseURL) VALUES (0, ?1, ?2)
ON CONFLICT (Single) DO UPDATE SET Path = ?1, BaseURL = ?2
`

type TransmissionSetParams struct {
	Path    string
	BaseURL string
}

func (q *Queries) TransmissionSet(ctx context.Context, arg TransmissionSetParams) error {
	_, err := q.db.ExecContext(ctx, transmissionSet, arg.Path, arg.BaseURL)
	return err
}

const videoCreate = `-- name: VideoCreate :one
INSERT INTO Video
(
	ReleaseID,
	ReleasePath
)
VALUES (?, ?)
RETURNING id, releaseid, releasepath, originalhash, mvplaylist
`

type VideoCreateParams struct {
	ReleaseID   string
	ReleasePath string
}

func (q *Queries) VideoCreate(ctx context.Context, arg VideoCreateParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoCreate, arg.ReleaseID, arg.ReleasePath)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.Mvplaylist,
	)
	return i, err
}

const videoGet = `-- name: VideoGet :one
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video WHERE ID = ?
`

func (q *Queries) VideoGet(ctx context.Context, id string) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoGet, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.Mvplaylist,
	)
	return i, err
}

const videoGetByReleasePath = `-- name: VideoGetByReleasePath :one
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video WHERE ReleaseID = ? AND ReleasePath = ?
`

type VideoGetByReleasePathParams struct {
	ReleaseID   string
	ReleasePath string
}

func (q *Queries) VideoGetByReleasePath(ctx context.Context, arg VideoGetByReleasePathParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoGetByReleasePath, arg.ReleaseID, arg.ReleasePath)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.Mvplaylist,
	)
	return i, err
}

const videoListByEpisodeID = `-- name: VideoListByEpisodeID :many
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video
WHERE ID IN (SELECT VideoID FROM EpisodeVideo WHERE EpisodeID = ?)
`

func (q *Queries) VideoListByEpisodeID(ctx context.Context, episodeid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListByEpisodeID, episodeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ReleasePath,
			&i.OriginalHash,
			&i.Mvplaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoUpdateMVPlaylist = `-- name: VideoUpdateMVPlaylist :one
UPDATE Video SET MVPlaylist = ? WHERE ID = ?
RETURNING id, releaseid, releasepath, originalhash, mvplaylist
`

type VideoUpdateMVPlaylistParams struct {
	Mvplaylist string
	ID         string
}

func (q *Queries) VideoUpdateMVPlaylist(ctx context.Context, arg VideoUpdateMVPlaylistParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoUpdateMVPlaylist, arg.Mvplaylist, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.Mvplaylist,
	)
	return i, err
}

const videoUpdateOriginalHash = `-- name: VideoUpdateOriginalHash :one
UPDATE Video SET OriginalHash = ? WHERE ID = ?
RETURNING id, releaseid, releasepath, originalhash, mvplaylist
`

type VideoUpdateOriginalHashParams struct {
	OriginalHash string
	ID           string
}

func (q *Queries) VideoUpdateOriginalHash(ctx context.Context, arg VideoUpdateOriginalHashParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoUpdateOriginalHash, arg.OriginalHash, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.Mvplaylist,
	)
	return i, err
}
