// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package schema

import (
	"context"
	"strings"
)

const audioTrackCreate = `-- name: AudioTrackCreate :one

INSERT INTO AudioTrack (
	VideoID, StreamIndex, Language, Title,
	Channels, ChannelLayout, Codec
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, videoid, streamindex, language, title, channels, channellayout, codec
`

type AudioTrackCreateParams struct {
	VideoID       string
	StreamIndex   int64
	Language      string
	Title         string
	Channels      int64
	ChannelLayout string
	Codec         string
}

// keep sorted by name
func (q *Queries) AudioTrackCreate(ctx context.Context, arg AudioTrackCreateParams) (AudioTrack, error) {
	row := q.db.QueryRowContext(ctx, audioTrackCreate,
		arg.VideoID,
		arg.StreamIndex,
		arg.Language,
		arg.Title,
		arg.Channels,
		arg.ChannelLayout,
		arg.Codec,
	)
	var i AudioTrack
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.StreamIndex,
		&i.Language,
		&i.Title,
		&i.Channels,
		&i.ChannelLayout,
		&i.Codec,
	)
	return i, err
}

const audioTrackDeleteByVideoID = `-- name: AudioTrackDeleteByVideoID :exec
DELETE FROM AudioTrack WHERE VideoID = ?
`

func (q *Queries) AudioTrackDeleteByVideoID(ctx context.Context, videoid string) error {
	_, err := q.db.ExecContext(ctx, audioTrackDeleteByVideoID, videoid)
	return err
}

const audioTrackListByVideoID = `-- name: AudioTrackListByVideoID :many
SELECT id, videoid, streamindex, language, title, channels, channellayout, codec FROM AudioTrack
WHERE VideoID = ?
ORDER BY StreamIndex
`

func (q *Queries) AudioTrackListByVideoID(ctx context.Context, videoid string) ([]AudioTrack, error) {
	rows, err := q.db.QueryContext(ctx, audioTrackListByVideoID, videoid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AudioTrack
	for rows.Next() {
		var i AudioTrack
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.StreamIndex,
			&i.Language,
			&i.Title,
			&i.Channels,
			&i.ChannelLayout,
			&i.Codec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorCreate = `-- name: AuthorCreate :one
INSERT INTO User (Name) VALUES (?)
RETURNING ID
`

func (q *Queries) AuthorCreate(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, authorCreate, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const authorDelete = `-- name: AuthorDelete :exec
DELETE FROM User
WHERE ID = ?
`

func (q *Queries) AuthorDelete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, authorDelete, id)
	return err
}

const authorGet = `-- name: AuthorGet :one
SELECT id, name FROM User
WHERE ID = ?
LIMIT 1
`

func (q *Queries) AuthorGet(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, authorGet, id)
	var i User
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const authorList = `-- name: AuthorList :many
SELECT id, name FROM User
ORDER BY Name
`

func (q *Queries) AuthorList(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, authorList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadCreate = `-- name: DownloadCreate :one
INSERT INTO Download
(
	State,
	Title,
	Torrent,
	InfoHash
)
VALUES (?, ?, ?, ?)
RETURNING id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadCreateParams struct {
	State    string
	Title    string
	Torrent  []byte
	InfoHash string
}

func (q *Queries) DownloadCreate(ctx context.Context, arg DownloadCreateParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadCreate,
		arg.State,
		arg.Title,
		arg.Torrent,
		arg.InfoHash,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadGet = `-- name: DownloadGet :one
SELECT id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid FROM Download WHERE ID = ?
`

func (q *Queries) DownloadGet(ctx context.Context, id string) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadGet, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadGetByInfoHash = `-- name: DownloadGetByInfoHash :one
SELECT id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid FROM Download WHERE InfoHash = ?
`

func (q *Queries) DownloadGetByInfoHash(ctx context.Context, infohash string) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadGetByInfoHash, infohash)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadList = `-- name: DownloadList :many
SELECT id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid FROM Download
ORDER BY ID DESC
`

func (q *Queries) DownloadList(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, downloadList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.State,
			&i.Title,
			&i.Error,
			&i.Torrent,
			&i.InfoHash,
			&i.Progress,
			&i.Autoimport,
			&i.PlanSeriesEditionID,
			&i.PlanMovieEditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadListByPlanMovieEditionID = `-- name: DownloadListByPlanMovieEditionID :many
SELECT id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid FROM Download
WHERE PlanMovieEditionID = ?
ORDER BY ID DESC
`

func (q *Queries) DownloadListByPlanMovieEditionID(ctx context.Context, planmovieeditionid *string) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, downloadListByPlanMovieEditionID, planmovieeditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.State,
			&i.Title,
			&i.Error,
			&i.Torrent,
			&i.InfoHash,
			&i.Progress,
			&i.Autoimport,
			&i.PlanSeriesEditionID,
			&i.PlanMovieEditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadListByPlanSeriesEditionID = `-- name: DownloadListByPlanSeriesEditionID :many
SELECT id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid FROM Download
WHERE PlanSeriesEditionID = ?
ORDER BY ID DESC
`

func (q *Queries) DownloadListByPlanSeriesEditionID(ctx context.Context, planserieseditionid *string) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, downloadListByPlanSeriesEditionID, planserieseditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Createdat,
			&i.State,
			&i.Title,
			&i.Error,
			&i.Torrent,
			&i.InfoHash,
			&i.Progress,
			&i.Autoimport,
			&i.PlanSeriesEditionID,
			&i.PlanMovieEditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadListInfoHashesDownloading = `-- name: DownloadListInfoHashesDownloading :many
SELECT InfoHash FROM Download
WHERE State = 'downloading'
`

func (q *Queries) DownloadListInfoHashesDownloading(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, downloadListInfoHashesDownloading)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var infohash string
		if err := rows.Scan(&infohash); err != nil {
			return nil, err
		}
		items = append(items, infohash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadPlanCountActiveByDownloadID = `-- name: DownloadPlanCountActiveByDownloadID :one
SELECT COUNT(*) FROM DownloadPlan WHERE DownloadID = ? AND State != 'imported'
`

func (q *Queries) DownloadPlanCountActiveByDownloadID(ctx context.Context, downloadid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, downloadPlanCountActiveByDownloadID, downloadid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const downloadPlanCountByDownloadID = `-- name: DownloadPlanCountByDownloadID :one
SELECT COUNT(*) FROM DownloadPlan WHERE DownloadID = ?
`

func (q *Queries) DownloadPlanCountByDownloadID(ctx context.Context, downloadid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, downloadPlanCountByDownloadID, downloadid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const downloadPlanCreate = `-- name: DownloadPlanCreate :exec
INSERT INTO DownloadPlan (DownloadID, Path, EpisodeID, MovieEditionID)
VALUES (?, ?, ?, ?)
`

type DownloadPlanCreateParams struct {
	DownloadID     string
	Path           string
	EpisodeID      *string
	MovieEditionID *string
}

func (q *Queries) DownloadPlanCreate(ctx context.Context, arg DownloadPlanCreateParams) error {
	_, err := q.db.ExecContext(ctx, downloadPlanCreate,
		arg.DownloadID,
		arg.Path,
		arg.EpisodeID,
		arg.MovieEditionID,
	)
	return err
}

const downloadPlanDeleteByDownloadID = `-- name: DownloadPlanDeleteByDownloadID :exec
DELETE FROM DownloadPlan WHERE DownloadID = ?
`

func (q *Queries) DownloadPlanDeleteByDownloadID(ctx context.Context, downloadid string) error {
	_, err := q.db.ExecContext(ctx, downloadPlanDeleteByDownloadID, downloadid)
	return err
}

const downloadPlanListByDownloadID = `-- name: DownloadPlanListByDownloadID :many
SELECT downloadid, path, episodeid, movieeditionid, state FROM DownloadPlan WHERE DownloadID = ?
`

func (q *Queries) DownloadPlanListByDownloadID(ctx context.Context, downloadid string) ([]DownloadPlan, error) {
	rows, err := q.db.QueryContext(ctx, downloadPlanListByDownloadID, downloadid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DownloadPlan
	for rows.Next() {
		var i DownloadPlan
		if err := rows.Scan(
			&i.DownloadID,
			&i.Path,
			&i.EpisodeID,
			&i.MovieEditionID,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const downloadPlanUpdateState = `-- name: DownloadPlanUpdateState :exec
UPDATE DownloadPlan SET State = ? WHERE DownloadID = ? AND Path = ?
`

type DownloadPlanUpdateStateParams struct {
	State      string
	DownloadID string
	Path       string
}

func (q *Queries) DownloadPlanUpdateState(ctx context.Context, arg DownloadPlanUpdateStateParams) error {
	_, err := q.db.ExecContext(ctx, downloadPlanUpdateState, arg.State, arg.DownloadID, arg.Path)
	return err
}

const downloadUpdateAutoImport = `-- name: DownloadUpdateAutoImport :one
UPDATE Download SET AutoImport = ? WHERE ID = ? RETURNING id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdateAutoImportParams struct {
	Autoimport int64
	ID         string
}

func (q *Queries) DownloadUpdateAutoImport(ctx context.Context, arg DownloadUpdateAutoImportParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdateAutoImport, arg.Autoimport, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadUpdateError = `-- name: DownloadUpdateError :one
UPDATE Download SET State = 'error', Error = ? WHERE ID = ? RETURNING id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdateErrorParams struct {
	Error string
	ID    string
}

func (q *Queries) DownloadUpdateError(ctx context.Context, arg DownloadUpdateErrorParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdateError, arg.Error, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadUpdatePlanMovie = `-- name: DownloadUpdatePlanMovie :one
UPDATE Download SET
	PlanMovieEditionID = ?
WHERE ID = ?
RETURNING id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdatePlanMovieParams struct {
	PlanMovieEditionID *string
	ID                 string
}

func (q *Queries) DownloadUpdatePlanMovie(ctx context.Context, arg DownloadUpdatePlanMovieParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdatePlanMovie, arg.PlanMovieEditionID, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadUpdatePlanSeries = `-- name: DownloadUpdatePlanSeries :one
UPDATE Download SET
	PlanSeriesEditionID = ?
WHERE ID = ?
RETURNING id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdatePlanSeriesParams struct {
	PlanSeriesEditionID *string
	ID                  string
}

func (q *Queries) DownloadUpdatePlanSeries(ctx context.Context, arg DownloadUpdatePlanSeriesParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdatePlanSeries, arg.PlanSeriesEditionID, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const downloadUpdateProgress = `-- name: DownloadUpdateProgress :one
UPDATE Download SET
	State = ?,
	Progress = ?,
	Error = ''
WHERE ID = ? RETURNING id, createdat, state, title, error, torrent, infohash, progress, autoimport, planserieseditionid, planmovieeditionid
`

type DownloadUpdateProgressParams struct {
	State    string
	Progress float64
	ID       string
}

func (q *Queries) DownloadUpdateProgress(ctx context.Context, arg DownloadUpdateProgressParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, downloadUpdateProgress, arg.State, arg.Progress, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.State,
		&i.Title,
		&i.Error,
		&i.Torrent,
		&i.InfoHash,
		&i.Progress,
		&i.Autoimport,
		&i.PlanSeriesEditionID,
		&i.PlanMovieEditionID,
	)
	return i, err
}

const episodeCreate = `-- name: EpisodeCreate :one
INSERT INTO Episode
(
	Slug,
	Title,
	Summary,
	Type,
	Airdate,
	Runtime,
	TVmazeURL,
	TVmazeImageURL
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, title, summary, type, airdate, runtime, tvmazeurl, tvmazeimageurl
`

type EpisodeCreateParams struct {
	Slug           string
	Title          string
	Summary        string
	Type           string
	Airdate        string
	Runtime        int64
	TVmazeURL      *string
	TVmazeImageURL string
}

func (q *Queries) EpisodeCreate(ctx context.Context, arg EpisodeCreateParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, episodeCreate,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.Type,
		arg.Airdate,
		arg.Runtime,
		arg.TVmazeURL,
		arg.TVmazeImageURL,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Type,
		&i.Airdate,
		&i.Runtime,
		&i.TVmazeURL,
		&i.TVmazeImageURL,
	)
	return i, err
}

const episodeGet = `-- name: EpisodeGet :one
SELECT id, slug, title, summary, type, airdate, runtime, tvmazeurl, tvmazeimageurl FROM Episode WHERE ID = ?
`

func (q *Queries) EpisodeGet(ctx context.Context, id string) (Episode, error) {
	row := q.db.QueryRowContext(ctx, episodeGet, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Type,
		&i.Airdate,
		&i.Runtime,
		&i.TVmazeURL,
		&i.TVmazeImageURL,
	)
	return i, err
}

const episodeGetBySlug = `-- name: EpisodeGetBySlug :one
SELECT id, slug, title, summary, type, airdate, runtime, tvmazeurl, tvmazeimageurl FROM Episode WHERE Slug = ?
`

func (q *Queries) EpisodeGetBySlug(ctx context.Context, slug string) (Episode, error) {
	row := q.db.QueryRowContext(ctx, episodeGetBySlug, slug)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.Type,
		&i.Airdate,
		&i.Runtime,
		&i.TVmazeURL,
		&i.TVmazeImageURL,
	)
	return i, err
}

const episodeListByEditionID = `-- name: EpisodeListByEditionID :many
SELECT id, slug, title, summary, type, airdate, runtime, tvmazeurl, tvmazeimageurl FROM Episode
WHERE ID IN (
	SELECT ID FROM SeasonEpisode
	WHERE SeasonID IN (SELECT ID FROM Season WHERE EditionID = ?)
)
ORDER BY ID
`

func (q *Queries) EpisodeListByEditionID(ctx context.Context, editionid string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, episodeListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.Type,
			&i.Airdate,
			&i.Runtime,
			&i.TVmazeURL,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeListBySeriesID = `-- name: EpisodeListBySeriesID :many
SELECT id, slug, title, summary, type, airdate, runtime, tvmazeurl, tvmazeimageurl FROM Episode
WHERE ID IN (
	SELECT ID FROM SeasonEpisode
	WHERE SeasonID IN (
		SELECT ID FROM Season
		WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
	)
)
ORDER BY ID
`

func (q *Queries) EpisodeListBySeriesID(ctx context.Context, seriesid string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, episodeListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.Type,
			&i.Airdate,
			&i.Runtime,
			&i.TVmazeURL,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeVideoCreate = `-- name: EpisodeVideoCreate :one
INSERT INTO EpisodeVideo (EpisodeID, VideoID)
VALUES (?, ?)
RETURNING episodeid, videoid
`

type EpisodeVideoCreateParams struct {
	EpisodeID string
	VideoID   string
}

func (q *Queries) EpisodeVideoCreate(ctx context.Context, arg EpisodeVideoCreateParams) (EpisodeVideo, error) {
	row := q.db.QueryRowContext(ctx, episodeVideoCreate, arg.EpisodeID, arg.VideoID)
	var i EpisodeVideo
	err := row.Scan(&i.EpisodeID, &i.VideoID)
	return i, err
}

const episodeVideoListByEditionID = `-- name: EpisodeVideoListByEditionID :many
SELECT episodeid, videoid FROM EpisodeVideo
WHERE EpisodeID IN (
	SELECT EpisodeID FROM SeasonEpisode
	WHERE SeasonID IN (SELECT ID FROM Season WHERE EditionID = ?)
)
`

func (q *Queries) EpisodeVideoListByEditionID(ctx context.Context, editionid string) ([]EpisodeVideo, error) {
	rows, err := q.db.QueryContext(ctx, episodeVideoListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeVideo
	for rows.Next() {
		var i EpisodeVideo
		if err := rows.Scan(&i.EpisodeID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeVideoListBySeriesID = `-- name: EpisodeVideoListBySeriesID :many
SELECT episodeid, videoid FROM EpisodeVideo
WHERE EpisodeID IN (
	SELECT EpisodeID FROM SeasonEpisode
	WHERE SeasonID IN (
		SELECT ID FROM Season
		WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
	)
)
`

func (q *Queries) EpisodeVideoListBySeriesID(ctx context.Context, seriesid string) ([]EpisodeVideo, error) {
	rows, err := q.db.QueryContext(ctx, episodeVideoListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeVideo
	for rows.Next() {
		var i EpisodeVideo
		if err := rows.Scan(&i.EpisodeID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const episodeVideoListByVideoID = `-- name: EpisodeVideoListByVideoID :many
SELECT episodeid, videoid FROM EpisodeVideo
WHERE VideoID = ?
`

func (q *Queries) EpisodeVideoListByVideoID(ctx context.Context, videoid string) ([]EpisodeVideo, error) {
	rows, err := q.db.QueryContext(ctx, episodeVideoListByVideoID, videoid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeVideo
	for rows.Next() {
		var i EpisodeVideo
		if err := rows.Scan(&i.EpisodeID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieCreate = `-- name: MovieCreate :one
INSERT INTO Movie (ID, Slug, TMDBID, IMDBID)
VALUES (?, ?, ?, ?)
RETURNING id, slug, tmdbid, imdbid
`

type MovieCreateParams struct {
	ID     string
	Slug   string
	TMDBID *int64
	IMDBID *string
}

func (q *Queries) MovieCreate(ctx context.Context, arg MovieCreateParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, movieCreate,
		arg.ID,
		arg.Slug,
		arg.TMDBID,
		arg.IMDBID,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TMDBID,
		&i.IMDBID,
	)
	return i, err
}

const movieEditionCreate = `-- name: MovieEditionCreate :one
INSERT INTO MovieEdition (Title, Label, Slug, MovieID, Summary, Year, Runtime, ImageURL)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, movieid, slug, title, label, summary, year, runtime, imageurl
`

type MovieEditionCreateParams struct {
	Title    string
	Label    string
	Slug     string
	MovieID  string
	Summary  string
	Year     string
	Runtime  int64
	ImageURL string
}

func (q *Queries) MovieEditionCreate(ctx context.Context, arg MovieEditionCreateParams) (MovieEdition, error) {
	row := q.db.QueryRowContext(ctx, movieEditionCreate,
		arg.Title,
		arg.Label,
		arg.Slug,
		arg.MovieID,
		arg.Summary,
		arg.Year,
		arg.Runtime,
		arg.ImageURL,
	)
	var i MovieEdition
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Slug,
		&i.Title,
		&i.Label,
		&i.Summary,
		&i.Year,
		&i.Runtime,
		&i.ImageURL,
	)
	return i, err
}

const movieEditionGet = `-- name: MovieEditionGet :one
SELECT id, movieid, slug, title, label, summary, year, runtime, imageurl FROM MovieEdition WHERE ID = ?
`

func (q *Queries) MovieEditionGet(ctx context.Context, id string) (MovieEdition, error) {
	row := q.db.QueryRowContext(ctx, movieEditionGet, id)
	var i MovieEdition
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Slug,
		&i.Title,
		&i.Label,
		&i.Summary,
		&i.Year,
		&i.Runtime,
		&i.ImageURL,
	)
	return i, err
}

const movieEditionGetDefault = `-- name: MovieEditionGetDefault :one
SELECT id, movieid, slug, title, label, summary, year, runtime, imageurl FROM MovieEdition WHERE MovieID = ? AND Slug = ''
`

func (q *Queries) MovieEditionGetDefault(ctx context.Context, movieid string) (MovieEdition, error) {
	row := q.db.QueryRowContext(ctx, movieEditionGetDefault, movieid)
	var i MovieEdition
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Slug,
		&i.Title,
		&i.Label,
		&i.Summary,
		&i.Year,
		&i.Runtime,
		&i.ImageURL,
	)
	return i, err
}

const movieEditionLabelSet = `-- name: MovieEditionLabelSet :exec
UPDATE MovieEdition SET Label = ? WHERE ID = ?
`

type MovieEditionLabelSetParams struct {
	Label string
	ID    string
}

func (q *Queries) MovieEditionLabelSet(ctx context.Context, arg MovieEditionLabelSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionLabelSet, arg.Label, arg.ID)
	return err
}

const movieEditionListByMovieID = `-- name: MovieEditionListByMovieID :many
SELECT id, movieid, slug, title, label, summary, year, runtime, imageurl FROM MovieEdition WHERE MovieID = ?
`

func (q *Queries) MovieEditionListByMovieID(ctx context.Context, movieid string) ([]MovieEdition, error) {
	rows, err := q.db.QueryContext(ctx, movieEditionListByMovieID, movieid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieEdition
	for rows.Next() {
		var i MovieEdition
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Slug,
			&i.Title,
			&i.Label,
			&i.Summary,
			&i.Year,
			&i.Runtime,
			&i.ImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieEditionListDefault = `-- name: MovieEditionListDefault :many
SELECT id, movieid, slug, title, label, summary, year, runtime, imageurl FROM MovieEdition WHERE Slug = ''
`

func (q *Queries) MovieEditionListDefault(ctx context.Context) ([]MovieEdition, error) {
	rows, err := q.db.QueryContext(ctx, movieEditionListDefault)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieEdition
	for rows.Next() {
		var i MovieEdition
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Slug,
			&i.Title,
			&i.Label,
			&i.Summary,
			&i.Year,
			&i.Runtime,
			&i.ImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieEditionRuntimeSet = `-- name: MovieEditionRuntimeSet :exec
UPDATE MovieEdition SET Runtime = ? WHERE ID = ?
`

type MovieEditionRuntimeSetParams struct {
	Runtime int64
	ID      string
}

func (q *Queries) MovieEditionRuntimeSet(ctx context.Context, arg MovieEditionRuntimeSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionRuntimeSet, arg.Runtime, arg.ID)
	return err
}

const movieEditionSlugExists = `-- name: MovieEditionSlugExists :one
SELECT COUNT(*) FROM MovieEdition WHERE MovieID = ? AND Slug = ?
`

type MovieEditionSlugExistsParams struct {
	MovieID string
	Slug    string
}

func (q *Queries) MovieEditionSlugExists(ctx context.Context, arg MovieEditionSlugExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, movieEditionSlugExists, arg.MovieID, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const movieEditionSlugSet = `-- name: MovieEditionSlugSet :exec
UPDATE MovieEdition SET Slug = ? WHERE ID = ?
`

type MovieEditionSlugSetParams struct {
	Slug string
	ID   string
}

func (q *Queries) MovieEditionSlugSet(ctx context.Context, arg MovieEditionSlugSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionSlugSet, arg.Slug, arg.ID)
	return err
}

const movieEditionSummarySet = `-- name: MovieEditionSummarySet :exec
UPDATE MovieEdition SET Summary = ? WHERE ID = ?
`

type MovieEditionSummarySetParams struct {
	Summary string
	ID      string
}

func (q *Queries) MovieEditionSummarySet(ctx context.Context, arg MovieEditionSummarySetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionSummarySet, arg.Summary, arg.ID)
	return err
}

const movieEditionTitleSet = `-- name: MovieEditionTitleSet :exec
UPDATE MovieEdition SET Title = ? WHERE ID = ?
`

type MovieEditionTitleSetParams struct {
	Title string
	ID    string
}

func (q *Queries) MovieEditionTitleSet(ctx context.Context, arg MovieEditionTitleSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionTitleSet, arg.Title, arg.ID)
	return err
}

const movieEditionYearSet = `-- name: MovieEditionYearSet :exec
UPDATE MovieEdition SET Year = ? WHERE ID = ?
`

type MovieEditionYearSetParams struct {
	Year string
	ID   string
}

func (q *Queries) MovieEditionYearSet(ctx context.Context, arg MovieEditionYearSetParams) error {
	_, err := q.db.ExecContext(ctx, movieEditionYearSet, arg.Year, arg.ID)
	return err
}

const movieGet = `-- name: MovieGet :one
SELECT id, slug, tmdbid, imdbid FROM Movie WHERE ID = ?
`

func (q *Queries) MovieGet(ctx context.Context, id string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, movieGet, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TMDBID,
		&i.IMDBID,
	)
	return i, err
}

const movieGetByEditionID = `-- name: MovieGetByEditionID :one
SELECT id, slug, tmdbid, imdbid FROM Movie
WHERE ID IN (SELECT MovieID FROM MovieEdition WHERE MovieEdition.ID = ?)
`

func (q *Queries) MovieGetByEditionID(ctx context.Context, id string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, movieGetByEditionID, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TMDBID,
		&i.IMDBID,
	)
	return i, err
}

const movieGetBySlug = `-- name: MovieGetBySlug :one
SELECT id, slug, tmdbid, imdbid FROM Movie WHERE Slug = ?
`

func (q *Queries) MovieGetBySlug(ctx context.Context, slug string) (Movie, error) {
	row := q.db.QueryRowContext(ctx, movieGetBySlug, slug)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TMDBID,
		&i.IMDBID,
	)
	return i, err
}

const movieList = `-- name: MovieList :many
SELECT id, slug, tmdbid, imdbid FROM Movie
ORDER BY Slug
`

func (q *Queries) MovieList(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, movieList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TMDBID,
			&i.IMDBID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieListByTMDBID = `-- name: MovieListByTMDBID :many
SELECT id, slug, tmdbid, imdbid FROM Movie WHERE TMDBID IN (/*SLICE:ids*/?)
`

func (q *Queries) MovieListByTMDBID(ctx context.Context, ids []*int64) ([]Movie, error) {
	query := movieListByTMDBID
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TMDBID,
			&i.IMDBID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieSlugExists = `-- name: MovieSlugExists :one
SELECT COUNT(*) FROM Movie WHERE Slug = ?
`

func (q *Queries) MovieSlugExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, movieSlugExists, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const movieSlugSet = `-- name: MovieSlugSet :exec
UPDATE Movie SET Slug = ? WHERE ID = ?
`

type MovieSlugSetParams struct {
	Slug string
	ID   string
}

func (q *Queries) MovieSlugSet(ctx context.Context, arg MovieSlugSetParams) error {
	_, err := q.db.ExecContext(ctx, movieSlugSet, arg.Slug, arg.ID)
	return err
}

const movieVideoCreate = `-- name: MovieVideoCreate :one
INSERT INTO MovieVideo (MovieEditionID, VideoID)
VALUES (?, ?)
RETURNING movieeditionid, videoid
`

type MovieVideoCreateParams struct {
	MovieEditionID string
	VideoID        string
}

func (q *Queries) MovieVideoCreate(ctx context.Context, arg MovieVideoCreateParams) (MovieVideo, error) {
	row := q.db.QueryRowContext(ctx, movieVideoCreate, arg.MovieEditionID, arg.VideoID)
	var i MovieVideo
	err := row.Scan(&i.MovieEditionID, &i.VideoID)
	return i, err
}

const movieVideoListByMovieEditionID = `-- name: MovieVideoListByMovieEditionID :many
SELECT movieeditionid, videoid FROM MovieVideo
WHERE MovieEditionID = ?
`

func (q *Queries) MovieVideoListByMovieEditionID(ctx context.Context, movieeditionid string) ([]MovieVideo, error) {
	rows, err := q.db.QueryContext(ctx, movieVideoListByMovieEditionID, movieeditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieVideo
	for rows.Next() {
		var i MovieVideo
		if err := rows.Scan(&i.MovieEditionID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieVideoListByMovieID = `-- name: MovieVideoListByMovieID :many
SELECT movieeditionid, videoid FROM MovieVideo
WHERE MovieEditionID IN (SELECT ID FROM MovieEdition WHERE MovieID = ?)
`

func (q *Queries) MovieVideoListByMovieID(ctx context.Context, movieid string) ([]MovieVideo, error) {
	rows, err := q.db.QueryContext(ctx, movieVideoListByMovieID, movieid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieVideo
	for rows.Next() {
		var i MovieVideo
		if err := rows.Scan(&i.MovieEditionID, &i.VideoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseCreate = `-- name: ReleaseCreate :one
INSERT INTO Release
(
	Name,
	InfoHash
)
VALUES (?, ?)
RETURNING id, name, infohash
`

type ReleaseCreateParams struct {
	Name     string
	InfoHash *string
}

func (q *Queries) ReleaseCreate(ctx context.Context, arg ReleaseCreateParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, releaseCreate, arg.Name, arg.InfoHash)
	var i Release
	err := row.Scan(&i.ID, &i.Name, &i.InfoHash)
	return i, err
}

const releaseGet = `-- name: ReleaseGet :one
SELECT id, name, infohash FROM Release WHERE ID = ?
`

func (q *Queries) ReleaseGet(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, releaseGet, id)
	var i Release
	err := row.Scan(&i.ID, &i.Name, &i.InfoHash)
	return i, err
}

const releaseGetByInfoHash = `-- name: ReleaseGetByInfoHash :one
SELECT id, name, infohash FROM Release WHERE InfoHash = ?
`

func (q *Queries) ReleaseGetByInfoHash(ctx context.Context, infohash *string) (Release, error) {
	row := q.db.QueryRowContext(ctx, releaseGetByInfoHash, infohash)
	var i Release
	err := row.Scan(&i.ID, &i.Name, &i.InfoHash)
	return i, err
}

const renditionForStreamingCountUnencoded = `-- name: RenditionForStreamingCountUnencoded :one
SELECT COUNT(*) FROM RenditionForStreaming
WHERE VideoID = ? AND Hash = ''
`

func (q *Queries) RenditionForStreamingCountUnencoded(ctx context.Context, videoid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingCountUnencoded, videoid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const renditionForStreamingCreate = `-- name: RenditionForStreamingCreate :one
INSERT INTO RenditionForStreaming (
	VideoID,
	Remux,
	Codec,
	TargetBitrate,
	MaxHeight,
	MaxFPS,
	CopyAudio,
	SurroundAudio,
	Priority
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority
`

type RenditionForStreamingCreateParams struct {
	VideoID       string
	Remux         int64
	Codec         string
	TargetBitrate int64
	MaxHeight     int64
	MaxFPS        int64
	CopyAudio     int64
	SurroundAudio int64
	Priority      int64
}

func (q *Queries) RenditionForStreamingCreate(ctx context.Context, arg RenditionForStreamingCreateParams) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingCreate,
		arg.VideoID,
		arg.Remux,
		arg.Codec,
		arg.TargetBitrate,
		arg.MaxHeight,
		arg.MaxFPS,
		arg.CopyAudio,
		arg.SurroundAudio,
		arg.Priority,
	)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.SurroundAudio,
		&i.Hash,
		&i.Playlist,
		&i.Priority,
	)
	return i, err
}

const renditionForStreamingDeleteByVideoID = `-- name: RenditionForStreamingDeleteByVideoID :exec
DELETE FROM RenditionForStreaming WHERE VideoID = ?
`

func (q *Queries) RenditionForStreamingDeleteByVideoID(ctx context.Context, videoid string) error {
	_, err := q.db.ExecContext(ctx, renditionForStreamingDeleteByVideoID, videoid)
	return err
}

const renditionForStreamingGet = `-- name: RenditionForStreamingGet :one
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE ID = ?
`

func (q *Queries) RenditionForStreamingGet(ctx context.Context, id string) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingGet, id)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.SurroundAudio,
		&i.Hash,
		&i.Playlist,
		&i.Priority,
	)
	return i, err
}

const renditionForStreamingListByMovieEditionID = `-- name: RenditionForStreamingListByMovieEditionID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID IN (SELECT VideoID FROM MovieVideo WHERE MovieEditionID = ?)
`

func (q *Queries) RenditionForStreamingListByMovieEditionID(ctx context.Context, movieeditionid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListByMovieEditionID, movieeditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingListByMovieID = `-- name: RenditionForStreamingListByMovieID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID IN (
	SELECT VideoID FROM MovieVideo
	WHERE MovieEditionID IN (SELECT ID FROM MovieEdition WHERE MovieID = ?)
)
`

func (q *Queries) RenditionForStreamingListByMovieID(ctx context.Context, movieid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListByMovieID, movieid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingListByVideoID = `-- name: RenditionForStreamingListByVideoID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID  IN (SELECT VideoID FROM EpisodeVideo WHERE EpisodeID = ?)
`

func (q *Queries) RenditionForStreamingListByVideoID(ctx context.Context, episodeid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListByVideoID, episodeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingListDirectByVideoID = `-- name: RenditionForStreamingListDirectByVideoID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID = ?
`

func (q *Queries) RenditionForStreamingListDirectByVideoID(ctx context.Context, videoid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListDirectByVideoID, videoid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingListEncodedByVideoID = `-- name: RenditionForStreamingListEncodedByVideoID :many
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID = ? AND Hash != ''
`

func (q *Queries) RenditionForStreamingListEncodedByVideoID(ctx context.Context, videoid string) ([]RenditionForStreaming, error) {
	rows, err := q.db.QueryContext(ctx, renditionForStreamingListEncodedByVideoID, videoid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenditionForStreaming
	for rows.Next() {
		var i RenditionForStreaming
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Remux,
			&i.Codec,
			&i.TargetBitrate,
			&i.MaxHeight,
			&i.MaxFPS,
			&i.CopyAudio,
			&i.SurroundAudio,
			&i.Hash,
			&i.Playlist,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renditionForStreamingNextUnencoded = `-- name: RenditionForStreamingNextUnencoded :one
SELECT id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority FROM RenditionForStreaming
WHERE VideoID = ? AND Hash = ''
ORDER BY Priority ASC LIMIT 1
`

func (q *Queries) RenditionForStreamingNextUnencoded(ctx context.Context, videoid string) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingNextUnencoded, videoid)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.SurroundAudio,
		&i.Hash,
		&i.Playlist,
		&i.Priority,
	)
	return i, err
}

const renditionForStreamingUpdateEncode = `-- name: RenditionForStreamingUpdateEncode :one
UPDATE RenditionForStreaming
SET Hash = ?, Playlist = ?
WHERE ID = ?
RETURNING id, videoid, remux, codec, targetbitrate, maxheight, maxfps, copyaudio, surroundaudio, hash, playlist, priority
`

type RenditionForStreamingUpdateEncodeParams struct {
	Hash     string
	Playlist string
	ID       string
}

func (q *Queries) RenditionForStreamingUpdateEncode(ctx context.Context, arg RenditionForStreamingUpdateEncodeParams) (RenditionForStreaming, error) {
	row := q.db.QueryRowContext(ctx, renditionForStreamingUpdateEncode, arg.Hash, arg.Playlist, arg.ID)
	var i RenditionForStreaming
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Remux,
		&i.Codec,
		&i.TargetBitrate,
		&i.MaxHeight,
		&i.MaxFPS,
		&i.CopyAudio,
		&i.SurroundAudio,
		&i.Hash,
		&i.Playlist,
		&i.Priority,
	)
	return i, err
}

const schemaVersionGet = `-- name: SchemaVersionGet :one
SELECT version, digest FROM schema LIMIT 1
`

type SchemaVersionGetRow struct {
	Version string
	Digest  string
}

func (q *Queries) SchemaVersionGet(ctx context.Context) (SchemaVersionGetRow, error) {
	row := q.db.QueryRowContext(ctx, schemaVersionGet)
	var i SchemaVersionGetRow
	err := row.Scan(&i.Version, &i.Digest)
	return i, err
}

const schemaVersionSet = `-- name: SchemaVersionSet :exec
UPDATE schema SET version = ?, digest = ?
`

type SchemaVersionSetParams struct {
	Version string
	Digest  string
}

func (q *Queries) SchemaVersionSet(ctx context.Context, arg SchemaVersionSetParams) error {
	_, err := q.db.ExecContext(ctx, schemaVersionSet, arg.Version, arg.Digest)
	return err
}

const seasonCreate = `-- name: SeasonCreate :one
INSERT INTO Season
(
	EditionID,
	SortKey,
	Name,
	Number,
	TVmazeURL,
	Summary,
	EpisodeOrder,
	PremieredOn,
	EndedOn,
	TVmazeImageURL
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, editionid, sortkey, name, number, tvmazeurl, summary, episodeorder, premieredon, endedon, tvmazeimageurl
`

type SeasonCreateParams struct {
	EditionID      string
	SortKey        string
	Name           string
	Number         int64
	TVmazeURL      *string
	Summary        string
	EpisodeOrder   int64
	PremieredOn    *string
	EndedOn        *string
	TVmazeImageURL string
}

func (q *Queries) SeasonCreate(ctx context.Context, arg SeasonCreateParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, seasonCreate,
		arg.EditionID,
		arg.SortKey,
		arg.Name,
		arg.Number,
		arg.TVmazeURL,
		arg.Summary,
		arg.EpisodeOrder,
		arg.PremieredOn,
		arg.EndedOn,
		arg.TVmazeImageURL,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.SortKey,
		&i.Name,
		&i.Number,
		&i.TVmazeURL,
		&i.Summary,
		&i.EpisodeOrder,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeImageURL,
	)
	return i, err
}

const seasonEpisodeCreate = `-- name: SeasonEpisodeCreate :exec
INSERT INTO SeasonEpisode (SeasonID, EpisodeID, SortKey, Label, Number)
VALUES (?, ?, ?, ?, ?)
`

type SeasonEpisodeCreateParams struct {
	SeasonID  string
	EpisodeID string
	SortKey   string
	Label     string
	Number    *int64
}

func (q *Queries) SeasonEpisodeCreate(ctx context.Context, arg SeasonEpisodeCreateParams) error {
	_, err := q.db.ExecContext(ctx, seasonEpisodeCreate,
		arg.SeasonID,
		arg.EpisodeID,
		arg.SortKey,
		arg.Label,
		arg.Number,
	)
	return err
}

const seasonEpisodeListByEditionID = `-- name: SeasonEpisodeListByEditionID :many
SELECT seasonid, episodeid, sortkey, label, number FROM SeasonEpisode
WHERE SeasonID IN (SELECT ID FROM Season WHERE EditionID = ?)
ORDER BY SortKey
`

func (q *Queries) SeasonEpisodeListByEditionID(ctx context.Context, editionid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonEpisodeListByEpisodeID = `-- name: SeasonEpisodeListByEpisodeID :many
SELECT seasonid, episodeid, sortkey, label, number FROM SeasonEpisode WHERE EpisodeID = ?
`

func (q *Queries) SeasonEpisodeListByEpisodeID(ctx context.Context, episodeid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListByEpisodeID, episodeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonEpisodeListBySeriesID = `-- name: SeasonEpisodeListBySeriesID :many
SELECT seasonid, episodeid, sortkey, label, number FROM SeasonEpisode
WHERE SeasonID IN (
	SELECT ID FROM Season
	WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
)
ORDER BY SortKey
`

func (q *Queries) SeasonEpisodeListBySeriesID(ctx context.Context, seriesid string) ([]SeasonEpisode, error) {
	rows, err := q.db.QueryContext(ctx, seasonEpisodeListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeasonEpisode
	for rows.Next() {
		var i SeasonEpisode
		if err := rows.Scan(
			&i.SeasonID,
			&i.EpisodeID,
			&i.SortKey,
			&i.Label,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonGet = `-- name: SeasonGet :one
SELECT id, editionid, sortkey, name, number, tvmazeurl, summary, episodeorder, premieredon, endedon, tvmazeimageurl FROM Season WHERE ID = ?
`

func (q *Queries) SeasonGet(ctx context.Context, id string) (Season, error) {
	row := q.db.QueryRowContext(ctx, seasonGet, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.SortKey,
		&i.Name,
		&i.Number,
		&i.TVmazeURL,
		&i.Summary,
		&i.EpisodeOrder,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeImageURL,
	)
	return i, err
}

const seasonListByEditionID = `-- name: SeasonListByEditionID :many
SELECT id, editionid, sortkey, name, number, tvmazeurl, summary, episodeorder, premieredon, endedon, tvmazeimageurl FROM Season WHERE EditionID = ?
ORDER BY SortKey
`

func (q *Queries) SeasonListByEditionID(ctx context.Context, editionid string) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, seasonListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.SortKey,
			&i.Name,
			&i.Number,
			&i.TVmazeURL,
			&i.Summary,
			&i.EpisodeOrder,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonListBySeriesID = `-- name: SeasonListBySeriesID :many
SELECT id, editionid, sortkey, name, number, tvmazeurl, summary, episodeorder, premieredon, endedon, tvmazeimageurl FROM Season
WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
ORDER BY SortKey
`

func (q *Queries) SeasonListBySeriesID(ctx context.Context, seriesid string) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, seasonListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.SortKey,
			&i.Name,
			&i.Number,
			&i.TVmazeURL,
			&i.Summary,
			&i.EpisodeOrder,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesCreate = `-- name: SeriesCreate :one
INSERT INTO Series
(
	ID,
	Slug,
	Title,
	Status,
	Language,
	PremieredOn,
	EndedOn,
	TVmazeID,
	TVmazeURL,
	TVmazeUpdatedAt,
	IMDBID,
	TVDBID,
	TVRageID
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, title, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid
`

type SeriesCreateParams struct {
	ID              string
	Slug            string
	Title           string
	Status          string
	Language        string
	PremieredOn     *string
	EndedOn         *string
	TVmazeID        *int64
	TVmazeURL       *string
	TVmazeUpdatedAt int64
	IMDBID          *string
	TVDBID          *int64
	TVRageID        *int64
}

func (q *Queries) SeriesCreate(ctx context.Context, arg SeriesCreateParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesCreate,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Status,
		arg.Language,
		arg.PremieredOn,
		arg.EndedOn,
		arg.TVmazeID,
		arg.TVmazeURL,
		arg.TVmazeUpdatedAt,
		arg.IMDBID,
		arg.TVDBID,
		arg.TVRageID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Language,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.TVmazeURL,
		&i.TVmazeUpdatedAt,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesEditionCreate = `-- name: SeriesEditionCreate :one
INSERT INTO SeriesEdition (Label, Slug, SeriesID, Summary, TVmazeImageURL)
VALUES (?, ?, ?, ?, ?)
RETURNING id, seriesid, slug, label, summary, tvmazeimageurl
`

type SeriesEditionCreateParams struct {
	Label          string
	Slug           string
	SeriesID       string
	Summary        string
	TVmazeImageURL string
}

func (q *Queries) SeriesEditionCreate(ctx context.Context, arg SeriesEditionCreateParams) (SeriesEdition, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionCreate,
		arg.Label,
		arg.Slug,
		arg.SeriesID,
		arg.Summary,
		arg.TVmazeImageURL,
	)
	var i SeriesEdition
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Slug,
		&i.Label,
		&i.Summary,
		&i.TVmazeImageURL,
	)
	return i, err
}

const seriesEditionGet = `-- name: SeriesEditionGet :one
SELECT id, seriesid, slug, label, summary, tvmazeimageurl FROM SeriesEdition WHERE ID = ?
`

func (q *Queries) SeriesEditionGet(ctx context.Context, id string) (SeriesEdition, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionGet, id)
	var i SeriesEdition
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Slug,
		&i.Label,
		&i.Summary,
		&i.TVmazeImageURL,
	)
	return i, err
}

const seriesEditionGetBySlug = `-- name: SeriesEditionGetBySlug :one
SELECT seriesedition.id, seriesedition.seriesid, seriesedition.slug, seriesedition.label, seriesedition.summary, seriesedition.tvmazeimageurl FROM SeriesEdition
JOIN Series ON Series.ID = SeriesEdition.SeriesID
WHERE Series.Slug = ?1 AND SeriesEdition.Slug = ?2
`

type SeriesEditionGetBySlugParams struct {
	SeriesSlug  string
	EditionSlug string
}

func (q *Queries) SeriesEditionGetBySlug(ctx context.Context, arg SeriesEditionGetBySlugParams) (SeriesEdition, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionGetBySlug, arg.SeriesSlug, arg.EditionSlug)
	var i SeriesEdition
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Slug,
		&i.Label,
		&i.Summary,
		&i.TVmazeImageURL,
	)
	return i, err
}

const seriesEditionLabelSet = `-- name: SeriesEditionLabelSet :exec
UPDATE SeriesEdition SET Label = ? WHERE ID = ?
`

type SeriesEditionLabelSetParams struct {
	Label string
	ID    string
}

func (q *Queries) SeriesEditionLabelSet(ctx context.Context, arg SeriesEditionLabelSetParams) error {
	_, err := q.db.ExecContext(ctx, seriesEditionLabelSet, arg.Label, arg.ID)
	return err
}

const seriesEditionListBySeriesID = `-- name: SeriesEditionListBySeriesID :many
SELECT id, seriesid, slug, label, summary, tvmazeimageurl FROM SeriesEdition WHERE SeriesID = ?
`

func (q *Queries) SeriesEditionListBySeriesID(ctx context.Context, seriesid string) ([]SeriesEdition, error) {
	rows, err := q.db.QueryContext(ctx, seriesEditionListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesEdition
	for rows.Next() {
		var i SeriesEdition
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Slug,
			&i.Label,
			&i.Summary,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesEditionListDefault = `-- name: SeriesEditionListDefault :many
SELECT id, seriesid, slug, label, summary, tvmazeimageurl FROM SeriesEdition WHERE Slug = ''
`

func (q *Queries) SeriesEditionListDefault(ctx context.Context) ([]SeriesEdition, error) {
	rows, err := q.db.QueryContext(ctx, seriesEditionListDefault)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeriesEdition
	for rows.Next() {
		var i SeriesEdition
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Slug,
			&i.Label,
			&i.Summary,
			&i.TVmazeImageURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesEditionSlugExists = `-- name: SeriesEditionSlugExists :one
SELECT COUNT(*) FROM SeriesEdition WHERE SeriesID = ? AND Slug = ?
`

type SeriesEditionSlugExistsParams struct {
	SeriesID string
	Slug     string
}

func (q *Queries) SeriesEditionSlugExists(ctx context.Context, arg SeriesEditionSlugExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, seriesEditionSlugExists, arg.SeriesID, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seriesEditionSlugSet = `-- name: SeriesEditionSlugSet :exec
UPDATE SeriesEdition SET Slug = ? WHERE ID = ?
`

type SeriesEditionSlugSetParams struct {
	Slug string
	ID   string
}

func (q *Queries) SeriesEditionSlugSet(ctx context.Context, arg SeriesEditionSlugSetParams) error {
	_, err := q.db.ExecContext(ctx, seriesEditionSlugSet, arg.Slug, arg.ID)
	return err
}

const seriesGenreAdd = `-- name: SeriesGenreAdd :exec
INSERT INTO SeriesGenre (SeriesID, GenreName) VALUES (?, ?)
`

type SeriesGenreAddParams struct {
	SeriesID  string
	GenreName string
}

func (q *Queries) SeriesGenreAdd(ctx context.Context, arg SeriesGenreAddParams) error {
	_, err := q.db.ExecContext(ctx, seriesGenreAdd, arg.SeriesID, arg.GenreName)
	return err
}

const seriesGenreList = `-- name: SeriesGenreList :many
SELECT GenreName FROM SeriesGenre WHERE SeriesID = ?
`

func (q *Queries) SeriesGenreList(ctx context.Context, seriesid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, seriesGenreList, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var genrename string
		if err := rows.Scan(&genrename); err != nil {
			return nil, err
		}
		items = append(items, genrename)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesGet = `-- name: SeriesGet :one
SELECT id, slug, title, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series WHERE ID = ?
`

func (q *Queries) SeriesGet(ctx context.Context, id string) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGet, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Language,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.TVmazeURL,
		&i.TVmazeUpdatedAt,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesGetByEditionID = `-- name: SeriesGetByEditionID :one
SELECT id, slug, title, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series
WHERE ID IN (SELECT SeriesID FROM SeriesEdition WHERE SeriesEdition.ID = ?)
`

func (q *Queries) SeriesGetByEditionID(ctx context.Context, id string) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGetByEditionID, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Language,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.TVmazeURL,
		&i.TVmazeUpdatedAt,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesGetBySlug = `-- name: SeriesGetBySlug :one
SELECT id, slug, title, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series WHERE Slug = ?
`

func (q *Queries) SeriesGetBySlug(ctx context.Context, slug string) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGetBySlug, slug)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Language,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.TVmazeURL,
		&i.TVmazeUpdatedAt,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesGetByTVmazeID = `-- name: SeriesGetByTVmazeID :one
SELECT id, slug, title, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series WHERE TVmazeID = ?
`

func (q *Queries) SeriesGetByTVmazeID(ctx context.Context, tvmazeid *int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, seriesGetByTVmazeID, tvmazeid)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Language,
		&i.PremieredOn,
		&i.EndedOn,
		&i.TVmazeID,
		&i.TVmazeURL,
		&i.TVmazeUpdatedAt,
		&i.IMDBID,
		&i.TVDBID,
		&i.TVRageID,
	)
	return i, err
}

const seriesList = `-- name: SeriesList :many
SELECT id, slug, title, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series
`

func (q *Queries) SeriesList(ctx context.Context) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, seriesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.Language,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeID,
			&i.TVmazeURL,
			&i.TVmazeUpdatedAt,
			&i.IMDBID,
			&i.TVDBID,
			&i.TVRageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesListByTVmazeID = `-- name: SeriesListByTVmazeID :many
SELECT id, slug, title, status, language, premieredon, endedon, tvmazeid, tvmazeurl, tvmazeupdatedat, imdbid, tvdbid, tvrageid FROM Series WHERE TVmazeID IN (/*SLICE:ids*/?)
`

func (q *Queries) SeriesListByTVmazeID(ctx context.Context, ids []*int64) ([]Series, error) {
	query := seriesListByTVmazeID
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.Language,
			&i.PremieredOn,
			&i.EndedOn,
			&i.TVmazeID,
			&i.TVmazeURL,
			&i.TVmazeUpdatedAt,
			&i.IMDBID,
			&i.TVDBID,
			&i.TVRageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesSlugExists = `-- name: SeriesSlugExists :one
SELECT COUNT(*) FROM Series WHERE Slug = ?
`

func (q *Queries) SeriesSlugExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, seriesSlugExists, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seriesSlugSet = `-- name: SeriesSlugSet :exec
UPDATE Series SET Slug = ? WHERE ID = ?
`

type SeriesSlugSetParams struct {
	Slug string
	ID   string
}

func (q *Queries) SeriesSlugSet(ctx context.Context, arg SeriesSlugSetParams) error {
	_, err := q.db.ExecContext(ctx, seriesSlugSet, arg.Slug, arg.ID)
	return err
}

const seriesTitleSet = `-- name: SeriesTitleSet :exec
UPDATE Series SET Title = ? WHERE ID = ?
`

type SeriesTitleSetParams struct {
	Title string
	ID    string
}

func (q *Queries) SeriesTitleSet(ctx context.Context, arg SeriesTitleSetParams) error {
	_, err := q.db.ExecContext(ctx, seriesTitleSet, arg.Title, arg.ID)
	return err
}

const settingListByGroup = `-- name: SettingListByGroup :many
SELECT "key", "Group", value FROM Setting WHERE "Group" = ?
`

func (q *Queries) SettingListByGroup(ctx context.Context, group string) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, settingListByGroup, group)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Group, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settingSet = `-- name: SettingSet :exec
INSERT INTO Setting (Key, "Group", Value) VALUES (?, ?, ?)
ON CONFLICT (Key) DO UPDATE SET Value = ?3
`

type SettingSetParams struct {
	Key   string
	Group string
	Value string
}

func (q *Queries) SettingSet(ctx context.Context, arg SettingSetParams) error {
	_, err := q.db.ExecContext(ctx, settingSet, arg.Key, arg.Group, arg.Value)
	return err
}

const storageCreate = `-- name: StorageCreate :exec
INSERT INTO Storage (Path, Contents) VALUES (?, ?)
`

type StorageCreateParams struct {
	Path     string
	Contents string
}

func (q *Queries) StorageCreate(ctx context.Context, arg StorageCreateParams) error {
	_, err := q.db.ExecContext(ctx, storageCreate, arg.Path, arg.Contents)
	return err
}

const storageList = `-- name: StorageList :many
SELECT path, contents FROM Storage
`

func (q *Queries) StorageList(ctx context.Context) ([]Storage, error) {
	rows, err := q.db.QueryContext(ctx, storageList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storage
	for rows.Next() {
		var i Storage
		if err := rows.Scan(&i.Path, &i.Contents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskCreate = `-- name: TaskCreate :one
INSERT INTO Task (Type, Args, Priority, Queue, NextRun) VALUES (?, ?, ?, ?, ?)
RETURNING id, type, args, failures, nextrun, failuredesc, priority, queue, running
`

type TaskCreateParams struct {
	Type     string
	Args     string
	Priority int64
	Queue    string
	NextRun  int64
}

func (q *Queries) TaskCreate(ctx context.Context, arg TaskCreateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskCreate,
		arg.Type,
		arg.Args,
		arg.Priority,
		arg.Queue,
		arg.NextRun,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskDelete = `-- name: TaskDelete :exec
DELETE FROM Task WHERE ID = ?
`

func (q *Queries) TaskDelete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, taskDelete, id)
	return err
}

const taskGet = `-- name: TaskGet :one
SELECT id, type, args, failures, nextrun, failuredesc, priority, queue, running FROM Task WHERE ID = ?
`

func (q *Queries) TaskGet(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskGet, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskList = `-- name: TaskList :many
SELECT id, type, args, failures, nextrun, failuredesc, priority, queue, running FROM Task
WHERE Running = 0
`

func (q *Queries) TaskList(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, taskList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Args,
			&i.Failures,
			&i.NextRun,
			&i.FailureDesc,
			&i.Priority,
			&i.Queue,
			&i.Running,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskLock = `-- name: TaskLock :one
UPDATE Task SET Running = 1
WHERE ID = ? AND Running = 0
RETURNING id, type, args, failures, nextrun, failuredesc, priority, queue, running
`

func (q *Queries) TaskLock(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskLock, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskNext = `-- name: TaskNext :one
SELECT id, type, args, failures, nextrun, failuredesc, priority, queue, running FROM Task
WHERE Queue = ? AND Running = 0 AND NextRun <= ?
ORDER BY Priority, ID
LIMIT 1
`

type TaskNextParams struct {
	Queue   string
	NextRun int64
}

func (q *Queries) TaskNext(ctx context.Context, arg TaskNextParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskNext, arg.Queue, arg.NextRun)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskReschedule = `-- name: TaskReschedule :one
UPDATE Task SET
	Failures = ?,
	NextRun = ?,
	FailureDesc = ?
WHERE ID = ?
RETURNING id, type, args, failures, nextrun, failuredesc, priority, queue, running
`

type TaskRescheduleParams struct {
	Failures    int64
	NextRun     int64
	FailureDesc *string
	ID          string
}

func (q *Queries) TaskReschedule(ctx context.Context, arg TaskRescheduleParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, taskReschedule,
		arg.Failures,
		arg.NextRun,
		arg.FailureDesc,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Args,
		&i.Failures,
		&i.NextRun,
		&i.FailureDesc,
		&i.Priority,
		&i.Queue,
		&i.Running,
	)
	return i, err
}

const taskResetRunning = `-- name: TaskResetRunning :exec
UPDATE Task SET Running = 0 WHERE Running = 1
`

func (q *Queries) TaskResetRunning(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, taskResetRunning)
	return err
}

const taskSaveOneOff = `-- name: TaskSaveOneOff :exec
UPDATE Task SET
	Failures = ?,
	FailureDesc = ?
WHERE ID = ?
`

type TaskSaveOneOffParams struct {
	Failures    int64
	FailureDesc *string
	ID          string
}

func (q *Queries) TaskSaveOneOff(ctx context.Context, arg TaskSaveOneOffParams) error {
	_, err := q.db.ExecContext(ctx, taskSaveOneOff, arg.Failures, arg.FailureDesc, arg.ID)
	return err
}

const taskSetNextRun = `-- name: TaskSetNextRun :exec
UPDATE Task SET NextRun = ? WHERE ID = ?
`

type TaskSetNextRunParams struct {
	NextRun int64
	ID      string
}

func (q *Queries) TaskSetNextRun(ctx context.Context, arg TaskSetNextRunParams) error {
	_, err := q.db.ExecContext(ctx, taskSetNextRun, arg.NextRun, arg.ID)
	return err
}

const taskUnlock = `-- name: TaskUnlock :exec
UPDATE Task SET Running = 0 WHERE ID = ?
`

func (q *Queries) TaskUnlock(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, taskUnlock, id)
	return err
}

const videoCreate = `-- name: VideoCreate :one
INSERT INTO Video
(
	ReleaseID,
	ReleasePath
)
VALUES (?, ?)
RETURNING id, releaseid, releasepath, originalhash, mvplaylist
`

type VideoCreateParams struct {
	ReleaseID   string
	ReleasePath string
}

func (q *Queries) VideoCreate(ctx context.Context, arg VideoCreateParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoCreate, arg.ReleaseID, arg.ReleasePath)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}

const videoGet = `-- name: VideoGet :one
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video WHERE ID = ?
`

func (q *Queries) VideoGet(ctx context.Context, id string) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoGet, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}

const videoGetByReleasePath = `-- name: VideoGetByReleasePath :one
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video WHERE ReleaseID = ? AND ReleasePath = ?
`

type VideoGetByReleasePathParams struct {
	ReleaseID   string
	ReleasePath string
}

func (q *Queries) VideoGetByReleasePath(ctx context.Context, arg VideoGetByReleasePathParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoGetByReleasePath, arg.ReleaseID, arg.ReleasePath)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}

const videoListByEditionID = `-- name: VideoListByEditionID :many
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video
WHERE ID IN (
	SELECT VideoID FROM EpisodeVideo
	WHERE EpisodeID IN (
		SELECT EpisodeID FROM SeasonEpisode
		WHERE SeasonID IN (SELECT ID FROM Season WHERE EditionID = ?)
	)
)
`

func (q *Queries) VideoListByEditionID(ctx context.Context, editionid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListByEditionID, editionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ReleasePath,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoListByEpisodeID = `-- name: VideoListByEpisodeID :many
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video
WHERE ID IN (SELECT VideoID FROM EpisodeVideo WHERE EpisodeID = ?)
`

func (q *Queries) VideoListByEpisodeID(ctx context.Context, episodeid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListByEpisodeID, episodeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ReleasePath,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoListByMovieEditionID = `-- name: VideoListByMovieEditionID :many
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video
WHERE ID IN (SELECT VideoID FROM MovieVideo WHERE MovieEditionID = ?)
`

func (q *Queries) VideoListByMovieEditionID(ctx context.Context, movieeditionid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListByMovieEditionID, movieeditionid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ReleasePath,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoListByMovieID = `-- name: VideoListByMovieID :many
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video
WHERE ID IN (
	SELECT VideoID FROM MovieVideo
	WHERE MovieEditionID IN (SELECT ID FROM MovieEdition WHERE MovieID = ?)
)
`

func (q *Queries) VideoListByMovieID(ctx context.Context, movieid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListByMovieID, movieid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ReleasePath,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoListBySeriesID = `-- name: VideoListBySeriesID :many
SELECT id, releaseid, releasepath, originalhash, mvplaylist FROM Video
WHERE ID IN (
	SELECT VideoID FROM EpisodeVideo
	WHERE EpisodeID IN (
		SELECT EpisodeID FROM SeasonEpisode
		WHERE SeasonID IN (
			SELECT ID FROM Season
			WHERE EditionID IN (SELECT ID FROM SeriesEdition WHERE SeriesID = ?)
		)
	)
)
`

func (q *Queries) VideoListBySeriesID(ctx context.Context, seriesid string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, videoListBySeriesID, seriesid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ReleasePath,
			&i.OriginalHash,
			&i.MVPlaylist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videoUpdateMVPlaylist = `-- name: VideoUpdateMVPlaylist :one
UPDATE Video SET MVPlaylist = ? WHERE ID = ?
RETURNING id, releaseid, releasepath, originalhash, mvplaylist
`

type VideoUpdateMVPlaylistParams struct {
	MVPlaylist string
	ID         string
}

func (q *Queries) VideoUpdateMVPlaylist(ctx context.Context, arg VideoUpdateMVPlaylistParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoUpdateMVPlaylist, arg.MVPlaylist, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}

const videoUpdateOriginalHash = `-- name: VideoUpdateOriginalHash :one
UPDATE Video SET OriginalHash = ? WHERE ID = ?
RETURNING id, releaseid, releasepath, originalhash, mvplaylist
`

type VideoUpdateOriginalHashParams struct {
	OriginalHash string
	ID           string
}

func (q *Queries) VideoUpdateOriginalHash(ctx context.Context, arg VideoUpdateOriginalHashParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, videoUpdateOriginalHash, arg.OriginalHash, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ReleasePath,
		&i.OriginalHash,
		&i.MVPlaylist,
	)
	return i, err
}
