package ui

import (
	"cmp"

	"ily.dev/domi"
	"ily.dev/domi/attr"
	"ily.dev/domi/html"

	"ily.dev/act3/xui/internal/sheet"
)

// Theme color tokens.
const (
	Muted  Color = "var(--ui-color-muted)"
	Accent Color = "var(--ui-color-accent)"
	Danger Color = "var(--ui-color-danger)"
)

// Color is a CSS color.
// It can be any valid CSS color expression,
// such as a literal like "#fff" or a variable like "var(--my-color)".
//
// Colors are used in view modifiers
// to affect the background and foreground colors.
//
// Color also implements [View].
// As a view, a Color fills the available space.
//
// The zero Color is equivalent to black ("#000").
type Color string

// Color implements [View] without embedding base. Modifiers with a possible
// effect delegate to the solid fill the color renders as; the rest — text
// styling, fills a color already requests — are no-ops, preferring the
// smaller markup. The assertion keeps the method set complete as View grows.
var _ View = Color("")

func (c Color) nodes() []node { return c.view() }

// view is the view a Color renders as: a solid view of the color.
func (c Color) view() base { return base{colorFillNode{color: c}} }

// Frame positions c inside an invisible frame
// with the given dimensions and alignment.
//
// Note that type [Alignment] satisfies FrameOption.
func (c Color) Frame(o ...FrameOption) View { return c.view().Frame(o...) }

// FrameBounds positions c inside an invisible frame
// with the given bounds and alignment.
//
// Note that type [Alignment] satisfies FrameBoundsOption.
func (c Color) FrameBounds(o ...FrameBoundsOption) View { return c.view().FrameBounds(o...) }

// FixedSize fixes c at its ideal size.
// This can cause it to exceed the bounds of its container.
func (c Color) FixedSize() View { return c.view().FixedSize() }

// Padding adds the empty space defined by s around c.
// If more than one value s is provided, they are added together.
func (c Color) Padding(s ...EdgeSpace) View { return c.view().Padding(s...) }

// LayerUnder displays u under c at alignment a.
// Opaque regions of c obscure u where they overlap.
func (c Color) LayerUnder(a Alignment, u View) View { return c.view().LayerUnder(a, u) }

// Background fills the background of c with bg.
func (c Color) Background(bg Color) View { return c.view().Background(bg) }

// LayerOver displays o over c at alignment a.
// Opaque regions of o obscure c where they overlap.
func (c Color) LayerOver(a Alignment, o View) View { return c.view().LayerOver(a, o) }

// Font sets the font size for text in c.
// Note that a Color contains no text, so this has no effect.
func (c Color) Font(FontSize) View { return c }

// Foreground uses c to draw foreground elements in c, such as text.
// Note that a Color contains no text, so this has no effect.
func (c Color) Foreground(Color) View { return c }

// Opacity sets c's opacity to x, from 0 (transparent) to 1 (opaque).
func (c Color) Opacity(x float64) View { return c.view().Opacity(x) }

// BorderShape sets the shape of c's border.
func (c Color) BorderShape(s Shape) View { return c.view().BorderShape(s) }

// Modify applies the given modifiers to c in order from left to right.
func (c Color) Modify(mods ...Modifier) View { return c.view().Modify(mods...) }

// Tag sets the HTML tag name
// of the outermost HTML element generated by c.
// If c already has a tag name, Tag panics.
func (c Color) Tag(name string) View { return c.view().Tag(name) }

// Class adds the given CSS classes
// to the outermost HTML element generated by c.
func (c Color) Class(classes ...string) View { return c.view().Class(classes...) }

// Attr adds the given HTML attributes
// to the outermost HTML element generated by c.
func (c Color) Attr(a ...domi.Attr) View { return c.view().Attr(a...) }

// colorFillNode is the box a Color lowers to as a view, requesting fill on
// both axes. Like a replaced element's content, the color paints as an inner
// element covering the box rather than as the box's own background, so a
// [View.Background] applied to the color lands under it — ordinary CSS
// painting order, with no property doing double duty.
type colorFillNode struct{ color Color }

func (f colorFillNode) render(rc renderContext) box {
	// A color adapts to any space and has no content-derived size of
	// its own; an axis with unbounded available space takes a 10px
	// default, and the rest adapt.
	a := []domi.Attr{attr.Class("ui-color")}
	if rc.unbounded.hasAll(Horizontal) {
		a = append(a, attr.Class("ui-color-ideal-x"))
	}
	if rc.unbounded.hasAll(Vertical) {
		a = append(a, attr.Class("ui-color-ideal-y"))
	}
	paint := rc.sheet.ClassFor(sheet.Style("background-color", cmp.Or(string(f.color), "#000")))
	// The box consumes a border shape but realizes it on the paint
	// element, the only thing it draws.
	return box{
		fills:   (Horizontal | Vertical) &^ rc.unbounded,
		attrs:   domi.Group(a...),
		content: html.Div(attr.Class("ui-color-paint"), rc.shapeClass(), attr.Class(paint)),
	}
}
