package ui

import (
	"cmp"

	"ily.dev/domi"
	"ily.dev/domi/attr"
)

// A Modifier configures the behavior of a View.
// It can be applied with [View.Modify].
//
// It is usually more convenient to call modifier methods directly on View.
type Modifier interface {
	modify(node) node
}

// A nodeEnv adjusts the environment for its subtree.
type nodeEnv struct {
	f    func(environment) environment
	node node
}

func (m nodeEnv) render(env environment) box {
	return m.node.render(m.f(env))
}

// A nodeTransform adjusts the environment for its subtree, like nodeEnv.
// Additionally, if the environment has any paint modifiers
// (as indicated by boxenv.paint),
// it first emits a layout-preserving wrapper box
// that applies all env modifiers,
// thus clearing any pending paint modifiers
// before applying f and rendering node.
type nodeTransform struct {
	f    func(environment) environment
	node node
}

func (m nodeTransform) render(env environment) box {
	if !env.hasPaint {
		return m.node.render(m.f(env))
	}
	return wrapMod(env, nodeEnv{f: m.f, node: m.node})
}

// Modify applies the given modifiers to v in order from left to right.
func (v base) Modify(mods ...Modifier) View {
	for _, m := range mods {
		out := make(base, len(v))
		for i, n := range v {
			out[i] = m.modify(n)
		}
		v = out
	}
	return v
}

// Attr adds the given HTML attributes
// to the outermost HTML element generated by v.
func (v base) Attr(a ...domi.Attr) View { return v.Modify(modAttr{attr: domi.Group(a...)}) }

// Background fills the background of v with c.
func (v base) Background(c Color) View { return v.Modify(Background(c)) }

// BorderShape sets the shape of v's border.
func (v base) BorderShape(s Shape) View { return v.Modify(BorderShape(s)) }

// BorderStroke draws a line
// of the given width and color
// over the inside edge of v.
func (v base) BorderStroke(px float64, c Color) View { return v.Modify(BorderStroke(px, c)) }

// Class adds the given CSS classes
// to the outermost HTML element generated by v.
func (v base) Class(c ...string) View { return v.Modify(modAttr{attr: attr.Class(c...)}) }

// FixedSize fixes v at its ideal size.
// This can cause it to exceed the bounds of its container.
func (v base) FixedSize() View {
	return v.
		Modify(modFixedSize{Horizontal | Vertical}).
		Class("ui-fixed-size")
}

// Font sets the font size for text in v.
func (v base) Font(f FontSize) View { return v.Modify(Font(f)) }

// Foreground uses c to draw foreground elements in v,
// such as text.
func (v base) Foreground(c Color) View { return v.Modify(Foreground(c)) }

// Opacity sets v's opacity to x, from 0 (transparent) to 1 (opaque).
func (v base) Opacity(x float64) View { return v.Modify(Opacity(x)) }

// Tag sets the HTML tag name
// of the outermost HTML element generated by v.
func (v base) Tag(name string) View { return v.Modify(modTag{name: name}) }

// NOTE: no exported construcor.
type modAttr struct{ attr domi.Attr }

func (m modAttr) modify(n node) node { return nodeEnv{f: m.environment, node: n} }

func (m modAttr) environment(env environment) environment {
	env.add(m.attr)
	return env
}

type modBackground struct{ c Color }

// Background fills the background of a view with c.
func Background(c Color) Modifier { return modBackground{c} }

func (m modBackground) modify(n node) node { return nodeEnv{f: m.environment, node: n} }

func (m modBackground) environment(env environment) environment {
	if m.c != "" {
		env.bg = append(env.bg, m.c)
		env.hasPaint = true
	}
	return env
}

type modBorderShape struct{ s Shape }

// BorderShape sets the shape of a view's border.
func BorderShape(s Shape) Modifier { return modBorderShape{s} }

func (m modBorderShape) modify(n node) node { return nodeTransform{f: m.environment, node: n} }

func (m modBorderShape) environment(env environment) environment {
	env.shape = m.s
	return env
}

type modBorderStroke struct {
	px float64
	c  Color
}

// BorderStroke draws a line
// of the given width and color
// over the inside edge of a view.
//
// The stroke paints over the view's content,
// inside its border shape.
// It takes no layout space.
// To add a border around the outside of a view,
// add padding inside the border.
func BorderStroke(px float64, c Color) Modifier { return modBorderStroke{px, c} }

func (m modBorderStroke) modify(n node) node { return nodeEnv{f: m.environment, node: n} }

func (m modBorderStroke) environment(env environment) environment {
	if m.px > 0 {
		env.stroke = append(env.stroke, stroke{m.px, m.c})
		env.hasPaint = true
	}
	return env
}

// NOTE: no exported construcor.
type modFixedSize struct{ axes AxisSet }

func (m modFixedSize) modify(n node) node { return nodeEnv{f: m.environment, node: n} }

// environment gives the subtree unbounded available space on the given axes,
// so the subtree resolves to its ideal size there (see [build]).
// The subtree's outermost box is a fill boundary:
// it must sit in its real container at that resolved size,
// even when the container has slack to offer.
func (m modFixedSize) environment(env environment) environment {
	env.unbounded |= m.axes
	env.fillMask |= m.axes
	// Note that a box can override max-content with its own declaration.
	if m.axes.hasAll(Horizontal) {
		env.style.Set("width", "max-content")
	}
	if m.axes.hasAll(Vertical) {
		env.style.Set("height", "max-content")
	}
	return env
}

type modFont struct{ f FontSize }

// Font sets the font size for text in a view.
func Font(f FontSize) Modifier { return modFont{f} }

func (m modFont) modify(n node) node { return nodeEnv{f: m.environment, node: n} }

func (m modFont) environment(env environment) environment {
	if m.f != "" {
		env.font = m.f
	}
	return env
}

type modForeground struct{ c Color }

// Foreground uses c to draw foreground elements in a view,
// such as text.
func Foreground(c Color) Modifier { return modForeground{c} }

func (m modForeground) modify(n node) node { return nodeEnv{f: m.environment, node: n} }

func (m modForeground) environment(env environment) environment {
	if m.c != "" {
		env.fg = &m.c
	}
	return env
}

type modOpacity struct{ x float64 }

// Opacity sets a view's opacity to x, from 0 (transparent) to 1 (opaque).
func Opacity(x float64) Modifier { return modOpacity{x} }

func (m modOpacity) modify(n node) node { return nodeTransform{f: m.environment, node: n} }

func (m modOpacity) environment(env environment) environment {
	a := 1 - env.trans
	env.trans = 1 - m.x*a
	return env
}

// NOTE: no exported constructor.
// modStyle emits one CSS declaration onto a subview's outermost box.
// Containers can use it to apply a style to their direct subviews.
type modStyle struct{ property, value string }

func (m modStyle) modify(n node) node { return nodeEnv{f: m.environment, node: n} }

func (m modStyle) environment(env environment) environment {
	env.style.Set(m.property, m.value)
	return env
}

// NOTE: no exported construcor.
type modTag struct{ name string }

func (m modTag) modify(n node) node { return nodeEnv{f: m.environment, node: n} }

func (m modTag) environment(env environment) environment {
	env.tag = m.name
	return env
}

type modTagDefault struct{ name string }

func (m modTagDefault) modify(n node) node { return nodeEnv{f: m.environment, node: n} }

func (m modTagDefault) environment(env environment) environment {
	env.tag = cmp.Or(env.tag, m.name)
	return env
}
