package ui

import (
	"fmt"

	"ily.dev/domi"
	"ily.dev/domi/attr"
)

// A Modifier configures the behavior of a View.
// It can be applied with [View.Modify].
//
// It is usually more convenient to call modifier methods directly on View.
//
// A style modifier behaves as if it were applied to a
// layout-transparent element wrapping the modified view.
// The renderer may collapse modifiers onto a single element
// only where that preserves the wrapper semantics.
type Modifier interface {
	applyTo(box) box
}

// contextual is implemented by modifiers and wrappers that adjust the
// render context their subtree sees, on top of their effect on the box
// itself: the box acts bottom-up, the context flows top-down.
type contextual interface {
	context(renderContext) renderContext
}

// nodeMod applies a modifier to its node's box.
type nodeMod struct {
	mod  Modifier
	node node
}

func (m nodeMod) render(rc renderContext) box {
	if w, ok := m.mod.(elementWrapper); ok {
		return nodeWrap{node: m.node, wrapper: w}.render(rc)
	}
	if c, ok := m.mod.(contextual); ok {
		rc = c.context(rc)
	}
	x := m.node.render(rc)
	if x.raw != nil {
		panic(fmt.Sprintf("ui: %T applied to a Domi view, which has no ui-managed element", m.mod))
	}
	return m.mod.applyTo(x)
}

// Modify applies the given modifiers to v in order from left to right.
func (v base) Modify(mods ...Modifier) View {
	for _, m := range mods {
		out := make(base, len(v))
		for i, n := range v {
			out[i] = nodeMod{mod: m, node: n}
		}
		v = out
	}
	return v
}

// Attr adds the given HTML attributes
// to the outermost HTML element generated by v.
func (v base) Attr(a ...domi.Attr) View { return v.Modify(modAttr{attr: domi.Group(a...)}) }

// Background fills the background of v with c.
func (v base) Background(c Color) View { return v.Modify(Background(c)) }

// BorderShape sets the shape of v's border.
func (v base) BorderShape(s Shape) View { return v.Modify(BorderShape(s)) }

// Class adds the given CSS classes
// to the outermost HTML element generated by v.
func (v base) Class(c ...string) View { return v.Modify(modAttr{attr: attr.Class(c...)}) }

// FixedSize fixes v at its ideal size.
// This can cause it to exceed the bounds of its container.
func (v base) FixedSize() View { return v.Modify(modFixedSize{}) }

// Font sets the font size for text in v.
func (v base) Font(f FontSize) View { return v.Modify(Font(f)) }

// Foreground uses c to draw foreground elements in v,
// such as text.
func (v base) Foreground(c Color) View { return v.Modify(Foreground(c)) }

// Opacity sets v's opacity to x, from 0 (transparent) to 1 (opaque).
func (v base) Opacity(x float64) View { return v.Modify(Opacity(x)) }

// Tag sets the HTML tag name
// of the outermost HTML element generated by v.
// If v already has a tag name, Tag panics.
func (v base) Tag(name string) View { return v.Modify(modTag{name: name}) }

// wraps marks a modifier that lowers to its own wrapper element.
// Its applyTo is never called: [nodeMod] routes wrapper modifiers
// through [nodeWrap] instead.
type wraps struct{}

func (wraps) applyTo(box) box { panic("unreached") }

// NOTE: no exported construcor.
type modAttr struct{ attr domi.Attr }

func (m modAttr) applyTo(x box) box {
	x.add(m.attr)
	return x
}

type modBackground struct {
	wraps
	c Color
}

// Background fills the background of a view with c.
func Background(c Color) Modifier { return modBackground{c: c} }

func (m modBackground) wrapElement(_ renderContext, content domi.Node, f, r AxisSet) box {
	b := box{fills: f, rigid: r, attrs: attr.Class("ui-mod"), content: content}
	if m.c != "" {
		b.setStyle("background-color", string(m.c))
	}
	return b
}

type modBorderShape struct{ s Shape }

// BorderShape sets the shape of a view's border.
//
// The shape is drawn by the modified view itself:
// it inherits down to the first box under the modifier,
// which consumes it and paints itself in the given shape.
// A repeated BorderShape is therefore inert:
// the innermost shape is written last and wins.
// BorderShape does not clip;
// content that overflows the shape is drawn in full.
func BorderShape(s Shape) Modifier { return modBorderShape{s} }

// applyTo is the identity: the shape acts through the context.
func (m modBorderShape) applyTo(x box) box { return x }

func (m modBorderShape) context(rc renderContext) renderContext {
	rc.shape.Set(m.s)
	return rc
}

// NOTE: no exported construcor.
type modFixedSize struct{}

func (modFixedSize) applyTo(x box) box {
	x.add(attr.Class("ui-fixed-size"))
	x.fills = 0
	x.rigid = Horizontal | Vertical
	return x
}

func (modFixedSize) context(rc renderContext) renderContext {
	rc.unbounded = Horizontal | Vertical
	return rc
}

type modFont struct {
	wraps
	f FontSize
}

// Font sets the font size for text in a view.
func Font(f FontSize) Modifier { return modFont{f: f} }

func (m modFont) wrapElement(_ renderContext, content domi.Node, f, r AxisSet) box {
	a := attr.Class("ui-mod")
	if c := m.f.class(); c != "" {
		a = attr.Class("ui-mod", c)
	}
	return box{fills: f, rigid: r, attrs: a, content: content}
}

type modForeground struct {
	wraps
	c Color
}

// Foreground uses c to draw foreground elements in a view,
// such as text.
func Foreground(c Color) Modifier { return modForeground{c: c} }

func (m modForeground) wrapElement(_ renderContext, content domi.Node, f, r AxisSet) box {
	b := box{fills: f, rigid: r, attrs: attr.Class("ui-mod"), content: content}
	if m.c != "" {
		b.setStyle("color", string(m.c))
	}
	return b
}

type modOpacity struct {
	wraps
	x float64
}

// Opacity sets a view's opacity to x, from 0 (transparent) to 1 (opaque).
// Nested opacities multiply:
// v.Opacity(0.5).Opacity(0.5) draws v at a quarter of full opacity.
func Opacity(x float64) Modifier { return modOpacity{x: x} }

func (m modOpacity) wrapElement(_ renderContext, content domi.Node, f, r AxisSet) box {
	b := box{fills: f, rigid: r, attrs: attr.Class("ui-mod"), content: content}
	b.setStyle("opacity", fmt.Sprintf("%g", m.x))
	return b
}

// NOTE: no exported construcor.
type modTag struct{ name string }

func (m modTag) applyTo(x box) box {
	if x.tag != "" {
		panic(fmt.Sprintf("ui: Tag(%q) on a view already tagged %q", m.name, x.tag))
	}
	x.tag = m.name
	return x
}
