package ui

import (
	"cmp"

	"ily.dev/act3/xui/internal/boxutil"
	"ily.dev/domi"
	"ily.dev/domi/attr"
	"ily.dev/domi/html"
)

// A View is a user interface element,
// with modifiers to change its appearance and behavior.
//
// Views are immutable.
// A modifier always returns a new view
// that is a modified version of the underlying view.
//
// You can create custom views by writing functions that return View values.
//
//	func MyView() View {
//	    return Text("hello, world!")
//	}
//
// Compose the View by combining one or more of the built-in views
// provided in this package,
// like the Text view above,
// plus other custom view functions you define.
type View interface {
	// Background fills the background of the receiver.
	Background(Color) View

	// BorderShape sets the shape of the receiver's border.
	BorderShape(Shape) View

	// FixedSize fixes the receiver at its ideal size.
	FixedSize() View

	// Font sets the font size for text in the receiver.
	Font(FontSize) View

	// Foreground uses c to draw foreground elements in the receiver,
	// such as text.
	Foreground(c Color) View

	// Frame positions the receiver inside an invisible frame with the
	// given dimensions and alignment.
	//
	// Note that type Alignment satisfies FrameOption.
	Frame(...FrameOption) View

	// FrameBounds positions the receiver inside an invisible frame with
	// the given bounds and alignment.
	//
	// Note that type Alignment satisfies FrameBoundsOption.
	FrameBounds(...FrameBoundsOption) View

	// LayerOver displays o over the receiver. Opaque regions of o
	// obscure the receiver where they overlap.
	//
	// The given Alignment sets the position of o relative to the receiver.
	LayerOver(a Alignment, o View) View

	// LayerUnder displays u under the receiver. Opaque regions of the
	// receiver obscure u where they overlap.
	//
	// The given Alignment sets the position of u relative to the receiver.
	LayerUnder(a Alignment, u View) View

	// Opacity sets the receiver's opacity to x, from 0 (transparent) to
	// 1 (opaque).
	Opacity(x float64) View

	// Padding adds the empty space defined by s around the receiver. If
	// more than one value s is provided, they are added together.
	Padding(s ...EdgeSpace) View

	// Modify applies the given modifiers to the receiver in order from
	// left to right.
	Modify(...Modifier) View

	// Attr adds the given HTML attributes to the outermost HTML element
	// generated by the receiver.
	Attr(...domi.Attr) View

	// Class adds the given CSS classes to the outermost HTML element
	// generated by the receiver.
	Class(...string) View

	// Tag sets the HTML tag name of the outermost HTML element
	// generated by the receiver. If the receiver already has a tag
	// name, Tag panics.
	Tag(string) View

	nodes() []node
}

// base is the shared concrete View implementation.
// A view is a list of nodes rendered in sequence.
// Most views hold a single node, but  [Group] and [For] hold one per member.
// An applied modifier modifies each node individually.
type base []node

func (v base) nodes() []node { return v }

// A node is a unary view.
// Its whole job is to lower itself to a single box.
type node interface {
	render(renderContext) box
}

type containerKind int

const (
	containerGrid containerKind = iota
	containerFlex
)

// renderContext carries the top-down state of a lowering pass.
type renderContext struct {
	lc        layoutContext
	container containerKind
	unbounded AxisSet
}

// A box is an HTML element under construction.
type box struct {
	tag      string
	key      string
	fills    AxisSet // A fill request is the physical axes a box wants to fill.
	rigid    AxisSet
	attrs    domi.Attr
	modClass boxutil.ClassSet
	content  domi.Node
	raw      domi.Node
}

func (x *box) add(a domi.Attr)   { x.attrs = domi.Group(x.attrs, a) }
func (x *box) addStyle(s string) { x.add(attr.Style(s)) }

// subviewsRendered is a generic combinator for lists of subviews.
// It renders the given views and merges their fill requests.
func subviewsRendered(rc renderContext, vs ...View) (domi.Node, AxisSet) {
	var ns []domi.Node
	var f AxisSet
	for _, v := range vs {
		for _, n := range v.nodes() {
			x := n.render(rc)
			f |= x.fills
			ns = append(ns, x.build(rc))
		}
	}
	return domi.Fragment(ns...), f
}

// build builds x as an HTML node.
func (x box) build(rc renderContext) domi.Node {
	n := x.raw
	if n == nil {
		a := domi.Group(x.modClass.Attr(), x.fills.fillAttr(rc), x.rigid.rigidAttr(rc))
		n = domi.Tag(cmp.Or(x.tag, "div"), x.attrs, a)(x.content)
	}
	if x.key != "" {
		n = domi.WithKey(x.key, n)
	}
	return n
}

// Render returns an HTML element representing v.
func Render(v View) domi.Node {
	content, _ := subviewsRendered(renderContext{}, v)
	return html.Div(attr.Class("ui ui-theme"))(content)
}
