package ui

import (
	"cmp"
	"slices"
	"strconv"
	"strings"

	"ily.dev/domi"
	"ily.dev/domi/attr"

	"ily.dev/act3/xui/internal/sheet"
)

// A View is a user interface element,
// with modifiers to change its appearance and behavior.
//
// Views are immutable.
// A modifier always returns a new view
// that is a modified version of the underlying view.
//
// You can create custom views by writing functions that return View values.
//
//	func MyView() View {
//	    return Text("hello, world!")
//	}
//
// Compose the View by combining one or more of the built-in views
// provided in this package,
// like the Text view above,
// plus other custom view functions you define.
type View interface {
	// Background fills the background of the receiver.
	Background(Color) View

	// BorderShape sets the shape of the receiver's border.
	BorderShape(Shape) View

	// FixedSize fixes the receiver at its ideal size.
	FixedSize() View

	// Font sets the font size for text in the receiver.
	Font(FontSize) View

	// Foreground uses c to draw foreground elements in the receiver,
	// such as text.
	Foreground(c Color) View

	// Frame positions the receiver inside an invisible frame with the
	// given dimensions and alignment.
	//
	// Note that type Alignment satisfies FrameOption.
	Frame(...FrameOption) View

	// FrameBounds positions the receiver inside an invisible frame with
	// the given bounds and alignment.
	//
	// Note that type Alignment satisfies FrameBoundsOption.
	FrameBounds(...FrameBoundsOption) View

	// LayerOver displays o over the receiver. Opaque regions of o
	// obscure the receiver where they overlap.
	//
	// The given Alignment sets the position of o relative to the receiver.
	LayerOver(a Alignment, o View) View

	// LayerUnder displays u under the receiver. Opaque regions of the
	// receiver obscure u where they overlap.
	//
	// The given Alignment sets the position of u relative to the receiver.
	LayerUnder(a Alignment, u View) View

	// Opacity sets the receiver's opacity to x, from 0 (transparent) to
	// 1 (opaque).
	Opacity(x float64) View

	// Padding adds the empty space defined by s around the receiver. If
	// more than one value s is provided, they are added together.
	Padding(s ...EdgeSpace) View

	// Modify applies the given modifiers to the receiver in order from
	// left to right.
	Modify(...Modifier) View

	// Attr adds the given HTML attributes to the outermost HTML element
	// generated by the receiver.
	Attr(...domi.Attr) View

	// Class adds the given CSS classes to the outermost HTML element
	// generated by the receiver.
	Class(...string) View

	// Tag sets the HTML tag name of the outermost HTML element
	// generated by the receiver.
	Tag(string) View

	nodes() []node
}

// base is the shared concrete View implementation.
// A view is a list of nodes rendered in sequence.
// Most views hold a single node, but  [Group] and [For] hold one per member.
// An applied modifier modifies each node individually.
type base []node

func (v base) nodes() []node { return v }

// A node is a unary view.
// Its whole job is to lower itself to a single box.
type node interface {
	render(environment) box
}

type containerKind int

const (
	containerGrid containerKind = iota
	containerFlex
)

// environment carries the top-down state of a lowering pass.
type environment struct {
	lc        layoutContext
	container containerKind
	unbounded AxisSet
	sheet     *sheet.Sheet
	boxenv    // must be zeroed before rendering a subview
}

// boxenv contains environment values
// that must be cleared before rendering a subview.
// They are "one-shot" or "one-box" values.
type boxenv struct {
	tag   string
	attrs domi.Attr
	style sheet.StyleSet
	fg    *Color
	bg    []Color
	shape *Shape
	font  FontSize
	trans float64

	hasPaint bool // set by every paint modifier
}

// add prepends attributes to the environment,
// keeping an inner writer's attributes before an outer's,
// so they land on the box in application order.
func (env *environment) add(a ...domi.Attr) {
	env.attrs = domi.Group(domi.Group(a...), env.attrs)
}

// A plan is an HTML element under construction.
type plan struct {
	content domi.Node
	fills   AxisSet // A fill request is the physical axes a box wants to fill.
	rigid   AxisSet
}

// A box is a rendered node.
// It contains the HTML node,
// plus ancillary data needed by its consumer.
type box struct {
	node  domi.Node
	fills AxisSet
	rigid AxisSet
}

// subviewsRendered is a generic combinator for lists of subviews.
// It renders the given views and merges their fill requests.
// It strips env's box values before any subview renders,
// so they cannot land on a subview's box.
func subviewsRendered(env environment, vs ...View) (domi.Node, AxisSet) {
	env.boxenv = boxenv{}
	var ns []domi.Node
	var f AxisSet
	for _, v := range vs {
		for _, n := range v.nodes() {
			b := n.render(env)
			f |= b.fills
			ns = append(ns, b.node)
		}
	}
	return domi.Fragment(ns...), f
}

// build returns the box described by env and p.
func build(env environment, p plan) box {
	a := env.attrs
	if c := env.font.class(); c != "" {
		a = domi.Group(a, attr.Class(c))
	}
	// A fill request on an unbounded axis is meaningless, so clear it.
	fills := p.fills &^ env.unbounded
	// A box is always rigid on an unbounded axis.
	rigid := p.rigid | env.unbounded
	ss := env.style
	addBackgroundStylesTo(&ss, env.bg)
	if env.shape != nil && *env.shape != Rectangle {
		ss.Set("border-radius", env.shape.radius())
	}
	if env.fg != nil {
		ss.Set("color", string(*env.fg))
	}
	if env.trans > 0 {
		ss.Set("opacity", strconv.FormatFloat(1-env.trans, 'g', 4, 64))
	}
	var style domi.Attr
	if !ss.IsEmpty() {
		style = attr.Class(env.sheet.ClassFor(ss))
	}
	// Keep the generated class after the named classes in rendered output.
	a = domi.Group(a, fills.fillAttr(env), rigid.rigidAttr(env), style)
	return box{
		node:  domi.Tag(cmp.Or(env.tag, "div"), a)(p.content),
		fills: fills,
		rigid: rigid,
	}
}

// addBackgroundStylesTo adds the declarations for the paint stack bg:
// the outermost color as background-color,
// and the inner colors as image layers listed innermost first.
func addBackgroundStylesTo(ss *sheet.StyleSet, bg []Color) {
	if len(bg) == 0 {
		return
	}
	ss.Set("background-color", string(bg[0]))
	if len(bg) == 1 {
		return
	}
	var img []string
	for _, c := range slices.Backward(bg[1:]) {
		img = append(img, "linear-gradient("+string(c)+","+string(c)+")")
	}
	ss.Set("background-image", strings.Join(img, ","))
}
