package ui

import (
	"cmp"
	"slices"
	"strconv"
	"strings"

	"ily.dev/domi"
	"ily.dev/domi/attr"

	"ily.dev/act3/xui/internal/sheet"
)

// A View is a user interface element,
// with modifiers to change its appearance and behavior.
//
// Views are immutable.
// A modifier always returns a new view
// that is a modified version of the underlying view.
//
// You can create custom views by writing functions that return View values.
//
//	func MyView() View {
//	    return Text("hello, world!")
//	}
//
// Compose the View by combining one or more of the built-in views
// provided in this package,
// like the Text view above,
// plus other custom view functions you define.
type View interface {
	// Background fills the background of the receiver.
	Background(Color) View

	// BorderShape sets the shape of the receiver's border.
	BorderShape(Shape) View

	// BorderStroke draws a line of the given width and color over the
	// inside edge of the receiver.
	BorderStroke(px float64, c Color) View

	// FixedSize fixes the receiver at its ideal size.
	FixedSize() View

	// Font sets the font size for text in the receiver.
	Font(FontSize) View

	// Foreground uses c to draw foreground elements in the receiver,
	// such as text.
	Foreground(c Color) View

	// Frame positions the receiver inside an invisible frame with the
	// given dimensions and alignment.
	//
	// Note that type Alignment satisfies FrameOption.
	Frame(...FrameOption) View

	// FrameBounds positions the receiver inside an invisible frame with
	// the given bounds and alignment.
	//
	// Note that type Alignment satisfies FrameBoundsOption.
	FrameBounds(...FrameBoundsOption) View

	// LayerOver displays o over the receiver. Opaque regions of o
	// obscure the receiver where they overlap.
	//
	// The given Alignment sets the position of o relative to the receiver.
	LayerOver(a Alignment, o View) View

	// LayerUnder displays u under the receiver. Opaque regions of the
	// receiver obscure u where they overlap.
	//
	// The given Alignment sets the position of u relative to the receiver.
	LayerUnder(a Alignment, u View) View

	// Opacity sets the receiver's opacity to x, from 0 (transparent) to
	// 1 (opaque).
	Opacity(x float64) View

	// Padding adds the empty space defined by s around the receiver. If
	// more than one value s is provided, they are added together.
	Padding(s ...EdgeSpace) View

	// Modify applies the given modifiers to the receiver in order from
	// left to right.
	Modify(...Modifier) View

	// Attr adds the given HTML attributes to the outermost HTML element
	// generated by the receiver.
	Attr(...domi.Attr) View

	// Class adds the given CSS classes to the outermost HTML element
	// generated by the receiver.
	Class(...string) View

	// Tag sets the HTML tag name of the outermost HTML element
	// generated by the receiver.
	Tag(string) View

	nodes() []node
}

// base is the shared concrete View implementation.
// A view is a list of nodes rendered in sequence.
// Most views hold a single node, but  [Group] and [For] hold one per member.
// An applied modifier modifies each node individually.
type base []node

func (v base) nodes() []node { return v }

// A node is a unary view.
// Its whole job is to lower itself to a single box.
type node interface {
	render(environment) box
}

type containerKind int

const (
	containerGrid containerKind = iota
	containerFlex
)

// environment carries the top-down state of a lowering pass.
type environment struct {
	lc        layoutContext
	container containerKind
	unbounded AxisSet
	sheet     *sheet.Sheet
	boxenv    // must be zeroed before rendering a subview
}

// boxenv contains environment values
// that must be cleared before rendering a subview.
// They are "one-shot" or "one-box" values.
type boxenv struct {
	tag    string
	attrs  domi.Attr
	style  sheet.StyleSet
	fg     *Color
	bg     []Color
	stroke []stroke
	shape  Shape
	font   FontSize
	trans  float64

	// fillMask is the set of axes to be stripped
	// from the box's fill request.
	// It is set at the outermost box of an unbounded subtree.
	fillMask AxisSet
	hasPaint bool // set by every paint modifier
}

// A stroke is one pending border line.
type stroke struct {
	px float64
	c  Color
}

// add prepends attributes to the environment,
// keeping an inner writer's attributes before an outer's,
// so they land on the box in application order.
func (env *environment) add(a ...domi.Attr) {
	env.attrs = domi.Group(domi.Group(a...), env.attrs)
}

// A plan is an HTML element under construction.
type plan struct {
	content domi.Node
	fills   AxisSet // A fill request is the physical axes a box wants to fill.
	rigid   AxisSet
	ideal   rect // ideal is a box's size when available space is unbounded.
}

// A box is a rendered node.
// It contains the HTML node,
// plus ancillary data needed by its consumer.
type box struct {
	node  domi.Node
	fills AxisSet
	rigid AxisSet
}

// subviewsRendered is a generic combinator for lists of subviews.
// It renders the given views and merges their fill requests.
// It strips env's box values before any subview renders,
// so they cannot land on a subview's box.
func subviewsRendered(env environment, vs ...View) (domi.Node, AxisSet) {
	env.boxenv = boxenv{}
	var ns []domi.Node
	var f AxisSet
	for _, v := range vs {
		for _, n := range v.nodes() {
			b := n.render(env)
			f |= b.fills
			ns = append(ns, b.node)
		}
	}
	return domi.Fragment(ns...), f
}

// build returns the box described by env and p.
func build(env environment, p plan) box {
	a := env.attrs
	fills := p.fills &^ env.fillMask
	// A box is always rigid on an unbounded axis.
	rigid := p.rigid | env.unbounded
	ss := env.style
	env.font.setStyles(&ss)
	addIdealStylesTo(&ss, p.ideal, env.unbounded, fills)
	addBackgroundStylesTo(&ss, env.bg)
	addStrokeStylesTo(&ss, env.stroke)
	if env.shape != Rectangle {
		ss.Set("border-radius", env.shape.radius())
	}
	if env.fg != nil {
		ss.Set("color", string(*env.fg))
	}
	if env.trans > 0 {
		ss.Set("opacity", strconv.FormatFloat(1-env.trans, 'g', 4, 64))
	}
	fills.addFillStylesTo(&ss, env)
	rigid.addRigidStylesTo(&ss, env)
	// Keep the generated class after the named classes in rendered output.
	a = domi.Group(a, attr.Class(env.sheet.ClassFor(ss)))
	return box{
		node:  domi.Tag(cmp.Or(env.tag, "div"), a)(p.content),
		fills: fills,
		rigid: rigid,
	}
}

// addIdealStylesTo adds CSS declarations for a box's ideal size.
// An ideal size applies only on an axis with unbounded available space.
// A box with no fill request simply uses its ideal size.
// A box with a fill request can expand beyond its ideal size.
// It contributes the ideal as a minimum length
// to the enclosing container's resolved extent,
// then expands to that extent.
func addIdealStylesTo(ss *sheet.StyleSet, i rect, unbounded, fills AxisSet) {
	for _, a := range [...]struct {
		axis AxisSet
		name string
		size size
	}{
		{Horizontal, "width", i.width},
		{Vertical, "height", i.height},
	} {
		if !a.size.definite || !unbounded.hasAll(a.axis) {
			continue
		}
		if fills.hasAll(a.axis) {
			ss.Set("min-"+a.name, a.size.css())
		} else {
			ss.Set(a.name, a.size.css())
		}
	}
}

// addStrokeStylesTo adds the declarations for the stroke stack:
// an ::after carrier covering the box,
// drawing the strokes as a shadow list, listed outermost first,
// so an outer stroke paints over an inner one.
func addStrokeStylesTo(ss *sheet.StyleSet, s []stroke) {
	if len(s) == 0 {
		return
	}
	var shadows []string
	for _, s := range s {
		shadows = append(shadows, "inset 0 0 0 "+cssPx(s.px)+" "+string(cmp.Or(s.c, "#000")))
	}
	ss.Set("position", "relative")
	ss.SetPseudo("::after", "content", `""`)
	ss.SetPseudo("::after", "position", "absolute")
	ss.SetPseudo("::after", "inset", "0")
	ss.SetPseudo("::after", "border-radius", "inherit")
	ss.SetPseudo("::after", "pointer-events", "none")
	ss.SetPseudo("::after", "box-shadow", strings.Join(shadows, ","))
}

// addBackgroundStylesTo adds the declarations for the paint stack bg:
// the outermost color as background-color,
// and the inner colors as image layers listed innermost first.
func addBackgroundStylesTo(ss *sheet.StyleSet, bg []Color) {
	if len(bg) == 0 {
		return
	}
	ss.Set("background-color", string(bg[0]))
	if len(bg) == 1 {
		return
	}
	var img []string
	for _, c := range slices.Backward(bg[1:]) {
		img = append(img, "linear-gradient("+string(c)+","+string(c)+")")
	}
	ss.Set("background-image", strings.Join(img, ","))
}
